INTERFACE

SUBROUTINE ACDRAG (YDCST, YDML_PHY_MF,KIDIA,KFDIA,KLON,KTDIA,KLEV,&
& PAPRS,PAPRSF,PDELP,PNBVNO,PRDELP,PU,PV,&
& PRCORI,PGETRL,PGWDCS,PVRLAN,PVRLDI,&
& PSTRDU,PSTRDV,PRAPTRAJ)
USE MODEL_PHYSICS_MF_MOD , ONLY : MODEL_PHYSICS_MF_TYPE
USE PARKIND1  ,ONLY : JPIM     ,JPRB    ,JPRD
USE YOMCST   , ONLY : TCST
IMPLICIT NONE
TYPE(TCST),        INTENT(IN)    :: YDCST
TYPE(MODEL_PHYSICS_MF_TYPE),INTENT(IN):: YDML_PHY_MF
INTEGER(KIND=JPIM),INTENT(IN)    :: KLON
INTEGER(KIND=JPIM),INTENT(IN)    :: KLEV
INTEGER(KIND=JPIM),INTENT(IN)    :: KIDIA
INTEGER(KIND=JPIM),INTENT(IN)    :: KFDIA
INTEGER(KIND=JPIM),INTENT(IN)    :: KTDIA
REAL(KIND=JPRB)   ,INTENT(IN)    :: PAPRS(KLON,0:KLEV)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PAPRSF(KLON,KLEV)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PDELP(KLON,KLEV)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PNBVNO(KLON,0:KLEV)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PRDELP(KLON,KLEV)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PU(KLON,KLEV)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PV(KLON,KLEV)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PRCORI(KLON)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PGETRL(KLON)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PGWDCS(KLON)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PVRLAN(KLON)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PVRLDI(KLON)
REAL(KIND=JPRB)   ,INTENT(OUT)   :: PSTRDU(KLON,0:KLEV)
REAL(KIND=JPRB)   ,INTENT(OUT)   :: PSTRDV(KLON,0:KLEV)
REAL(KIND=JPRB)   ,INTENT(OUT)   :: PRAPTRAJ(KLON,0:KLEV)
END SUBROUTINE ACDRAG


SUBROUTINE ACDRAG_OPENACC (YDCST, YDML_PHY_MF, KIDIA, KFDIA, KLON, KTDIA, KLEV, PAPRS, PAPRSF, PDELP, PNBVNO&
&, PRDELP, PU, PV, PRCORI, PGETRL, PGWDCS, PVRLAN, PVRLDI, PSTRDU, PSTRDV, PRAPTRAJ, YDSTACK)
USE MODEL_PHYSICS_MF_MOD,ONLY:MODEL_PHYSICS_MF_TYPE
USE PARKIND1,ONLY:JPIM, JPRB, JPRD
USE YOMCST,ONLY:TCST
USE FXTRAN_ACDC_STACK_MOD
USE FXTRAN_ACDC_ABORT_MOD
IMPLICIT NONE
!$ACC ROUTINE (ACDRAG_OPENACC) SEQ
TYPE (TCST), INTENT (IN)::YDCST
TYPE (MODEL_PHYSICS_MF_TYPE), INTENT (IN)::YDML_PHY_MF
INTEGER (KIND=JPIM), INTENT (IN)::KLON
INTEGER (KIND=JPIM), INTENT (IN)::KLEV
INTEGER (KIND=JPIM), INTENT (IN)::KIDIA
INTEGER (KIND=JPIM), INTENT (IN)::KFDIA
INTEGER (KIND=JPIM), INTENT (IN)::KTDIA
REAL (KIND=JPRB), INTENT (IN)::PAPRS (KLON, 0:KLEV)
REAL (KIND=JPRB), INTENT (IN)::PAPRSF (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PDELP (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PNBVNO (KLON, 0:KLEV)
REAL (KIND=JPRB), INTENT (IN)::PRDELP (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PU (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PV (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PRCORI (KLON)
REAL (KIND=JPRB), INTENT (IN)::PGETRL (KLON)
REAL (KIND=JPRB), INTENT (IN)::PGWDCS (KLON)
REAL (KIND=JPRB), INTENT (IN)::PVRLAN (KLON)
REAL (KIND=JPRB), INTENT (IN)::PVRLDI (KLON)
REAL (KIND=JPRB), INTENT (OUT)::PSTRDU (KLON, 0:KLEV)
REAL (KIND=JPRB), INTENT (OUT)::PSTRDV (KLON, 0:KLEV)
REAL (KIND=JPRB), INTENT (OUT)::PRAPTRAJ (KLON, 0:KLEV)
TYPE(FXTRAN_ACDC_STACK), INTENT (IN) :: YDSTACK

END SUBROUTINE ACDRAG_OPENACC


SUBROUTINE ACDRAG_OPENACC_BITREPRO (YDCST, YDML_PHY_MF, KIDIA, KFDIA, KLON&
&, KTDIA, KLEV, PAPRS, PAPRSF, PDELP, PNBVNO, PRDELP, PU, PV, PRCORI, PGETRL&
&, PGWDCS, PVRLAN, PVRLDI, PSTRDU, PSTRDV, PRAPTRAJ, YDSTACK)
USE MODEL_PHYSICS_MF_MOD,ONLY:MODEL_PHYSICS_MF_TYPE
USE PARKIND1,ONLY:JPIM, JPRB, JPRD
USE YOMCST,ONLY:TCST
USE FXTRAN_ACDC_STACK_MOD
USE FXTRAN_ACDC_ABORT_MOD
IMPLICIT NONE
!$ACC ROUTINE (ACDRAG_OPENACC_BITREPRO) SEQ
TYPE (TCST), INTENT (IN)::YDCST
TYPE (MODEL_PHYSICS_MF_TYPE), INTENT (IN)::YDML_PHY_MF
INTEGER (KIND=JPIM), INTENT (IN)::KLON
INTEGER (KIND=JPIM), INTENT (IN)::KLEV
INTEGER (KIND=JPIM), INTENT (IN)::KIDIA
INTEGER (KIND=JPIM), INTENT (IN)::KFDIA
INTEGER (KIND=JPIM), INTENT (IN)::KTDIA
REAL (KIND=JPRB), INTENT (IN)::PAPRS (KLON, 0:KLEV)
REAL (KIND=JPRB), INTENT (IN)::PAPRSF (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PDELP (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PNBVNO (KLON, 0:KLEV)
REAL (KIND=JPRB), INTENT (IN)::PRDELP (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PU (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PV (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PRCORI (KLON)
REAL (KIND=JPRB), INTENT (IN)::PGETRL (KLON)
REAL (KIND=JPRB), INTENT (IN)::PGWDCS (KLON)
REAL (KIND=JPRB), INTENT (IN)::PVRLAN (KLON)
REAL (KIND=JPRB), INTENT (IN)::PVRLDI (KLON)
REAL (KIND=JPRB), INTENT (OUT)::PSTRDU (KLON, 0:KLEV)
REAL (KIND=JPRB), INTENT (OUT)::PSTRDV (KLON, 0:KLEV)
REAL (KIND=JPRB), INTENT (OUT)::PRAPTRAJ (KLON, 0:KLEV)
TYPE(FXTRAN_ACDC_STACK), INTENT (IN) :: YDSTACK

END SUBROUTINE ACDRAG_OPENACC_BITREPRO


SUBROUTINE ACDRAG_MANYBLOCKS (YDCST, YDML_PHY_MF, KIDIA, KFDIA, KLON, KTDIA&
&, KLEV, PAPRS, PAPRSF, PDELP, PNBVNO, PRDELP, PU, PV, PRCORI, PGETRL, PGWDCS&
&, PVRLAN, PVRLDI, PSTRDU, PSTRDV, PRAPTRAJ, LDACC, KGPBLKS, YDOFFSET)
USE MODEL_PHYSICS_MF_MOD,ONLY:MODEL_PHYSICS_MF_TYPE
USE PARKIND1,ONLY:JPIM, JPRB, JPRD
USE YOMCST,ONLY:TCST
USE FXTRAN_ACDC_STACK_MOD
USE FXTRAN_ACDC_ABORT_MOD

IMPLICIT NONE
TYPE (TCST), INTENT (IN)::YDCST
TYPE (MODEL_PHYSICS_MF_TYPE), INTENT (IN)::YDML_PHY_MF
INTEGER (KIND=JPIM), INTENT (IN)::KLON
INTEGER (KIND=JPIM), INTENT (IN)::KLEV
INTEGER (KIND=JPIM), INTENT (IN)::KIDIA
INTEGER (KIND=JPIM), INTENT (IN)::KFDIA
INTEGER (KIND=JPIM), INTENT (IN)::KTDIA
REAL (KIND=JPRB), INTENT (IN)::PAPRS (:, 0:, :)
REAL (KIND=JPRB), INTENT (IN)::PAPRSF (:, :, :)
REAL (KIND=JPRB), INTENT (IN)::PDELP (:, :, :)
REAL (KIND=JPRB), INTENT (IN)::PNBVNO (:, 0:, :)
REAL (KIND=JPRB), INTENT (IN)::PRDELP (:, :, :)
REAL (KIND=JPRB), INTENT (IN)::PU (:, :, :)
REAL (KIND=JPRB), INTENT (IN)::PV (:, :, :)
REAL (KIND=JPRB), INTENT (IN)::PRCORI (:, :)
REAL (KIND=JPRB), INTENT (IN)::PGETRL (:, :)
REAL (KIND=JPRB), INTENT (IN)::PGWDCS (:, :)
REAL (KIND=JPRB), INTENT (IN)::PVRLAN (:, :)
REAL (KIND=JPRB), INTENT (IN)::PVRLDI (:, :)
REAL (KIND=JPRB), INTENT (OUT)::PSTRDU (:, 0:, :)
REAL (KIND=JPRB), INTENT (OUT)::PSTRDV (:, 0:, :)
REAL (KIND=JPRB), INTENT (OUT)::PRAPTRAJ (:, 0:, :)
TYPE (FXTRAN_ACDC_STACK), INTENT (IN) :: YDOFFSET
INTEGER, INTENT (IN) :: KGPBLKS
LOGICAL, INTENT (IN) :: LDACC

END SUBROUTINE ACDRAG_MANYBLOCKS


SUBROUTINE ACDRAG_BITREPRO (YDCST, YDML_PHY_MF, KIDIA, KFDIA, KLON, KTDIA, KLEV, PAPRS, PAPRSF, PDELP&
&, PNBVNO, PRDELP, PU, PV, PRCORI, PGETRL, PGWDCS, PVRLAN, PVRLDI, PSTRDU, PSTRDV, PRAPTRAJ)
USE MODEL_PHYSICS_MF_MOD,ONLY:MODEL_PHYSICS_MF_TYPE
USE PARKIND1,ONLY:JPIM, JPRB, JPRD
USE YOMCST,ONLY:TCST
IMPLICIT NONE
TYPE (TCST), INTENT (IN)::YDCST
TYPE (MODEL_PHYSICS_MF_TYPE), INTENT (IN)::YDML_PHY_MF
INTEGER (KIND=JPIM), INTENT (IN)::KLON
INTEGER (KIND=JPIM), INTENT (IN)::KLEV
INTEGER (KIND=JPIM), INTENT (IN)::KIDIA
INTEGER (KIND=JPIM), INTENT (IN)::KFDIA
INTEGER (KIND=JPIM), INTENT (IN)::KTDIA
REAL (KIND=JPRB), INTENT (IN)::PAPRS (KLON, 0:KLEV)
REAL (KIND=JPRB), INTENT (IN)::PAPRSF (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PDELP (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PNBVNO (KLON, 0:KLEV)
REAL (KIND=JPRB), INTENT (IN)::PRDELP (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PU (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PV (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PRCORI (KLON)
REAL (KIND=JPRB), INTENT (IN)::PGETRL (KLON)
REAL (KIND=JPRB), INTENT (IN)::PGWDCS (KLON)
REAL (KIND=JPRB), INTENT (IN)::PVRLAN (KLON)
REAL (KIND=JPRB), INTENT (IN)::PVRLDI (KLON)
REAL (KIND=JPRB), INTENT (OUT)::PSTRDU (KLON, 0:KLEV)
REAL (KIND=JPRB), INTENT (OUT)::PSTRDV (KLON, 0:KLEV)
REAL (KIND=JPRB), INTENT (OUT)::PRAPTRAJ (KLON, 0:KLEV)
END SUBROUTINE ACDRAG_BITREPRO

END INTERFACE
