MODULE UTIL_TPHY_MOD

USE YOMPHY, ONLY : TPHY

INTERFACE ACDC_SAVE
MODULE PROCEDURE ACDC_SAVE_TPHY
END INTERFACE

INTERFACE ACDC_LOAD
MODULE PROCEDURE ACDC_LOAD_TPHY
END INTERFACE

INTERFACE ACDC_COPY
MODULE PROCEDURE ACDC_COPY_TPHY
END INTERFACE




INTERFACE ACDC_WIPE
MODULE PROCEDURE ACDC_WIPE_TPHY
END INTERFACE


CONTAINS

SUBROUTINE ACDC_SAVE_TPHY (SELF, KLUN)

IMPLICIT NONE
TYPE (TPHY), INTENT (IN), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN

WRITE (KLUN) SELF%NPHYREP
WRITE (KLUN) SELF%LGLT
WRITE (KLUN) SELF%LNEWD
END SUBROUTINE

SUBROUTINE ACDC_LOAD_TPHY (SELF, KLUN)

IMPLICIT NONE
TYPE (TPHY), INTENT (OUT), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN

READ (KLUN) SELF%NPHYREP
READ (KLUN) SELF%LGLT
READ (KLUN) SELF%LNEWD
END SUBROUTINE

SUBROUTINE ACDC_COPY_TPHY (SELF, LDCREATED, LDFIELDAPI)

IMPLICIT NONE
TYPE (TPHY), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
LOGICAL :: LLCREATED
LOGICAL :: LLFIELDAPI
LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$ACC ENTER DATA CREATE (SELF)
  !$ACC UPDATE DEVICE (SELF)
ENDIF

END SUBROUTINE







SUBROUTINE ACDC_WIPE_TPHY (SELF, LDDELETED, LDFIELDAPI)

IMPLICIT NONE
TYPE (TPHY), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
LOGICAL :: LLDELETED
LOGICAL :: LLFIELDAPI
LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$ACC EXIT DATA DELETE (SELF)
ENDIF
END SUBROUTINE



END MODULE
