
SUBROUTINE ACDRAG_MANYBLOCKS (YDCST, YDML_PHY_MF, KIDIA, KFDIA, KLON, KTDIA&
&, KLEV, PAPRS, PAPRSF, PDELP, PNBVNO, PRDELP, PU, PV, PRCORI, PGETRL, PGWDCS&
&, PVRLAN, PVRLDI, PSTRDU, PSTRDV, PRAPTRAJ, LDACC, KGPBLKS, YDOFFSET)
USE MODEL_PHYSICS_MF_MOD,ONLY:MODEL_PHYSICS_MF_TYPE
USE PARKIND1,ONLY:JPIM, JPRB, JPRD
USE YOMHOOK,ONLY:LHOOK, DR_HOOK, JPHOOK
USE YOMCST,ONLY:TCST
USE FXTRAN_ACDC_STACK_MOD
USE FXTRAN_ACDC_ABORT_MOD
#include "fxtran_acdc_stack.h"

IMPLICIT NONE



TYPE (TCST), INTENT (IN)::YDCST
TYPE (MODEL_PHYSICS_MF_TYPE), INTENT (IN)::YDML_PHY_MF
INTEGER (KIND=JPIM), INTENT (IN)::KLON
INTEGER (KIND=JPIM), INTENT (IN)::KLEV
INTEGER (KIND=JPIM), INTENT (IN)::KIDIA
INTEGER (KIND=JPIM), INTENT (IN)::KFDIA
INTEGER (KIND=JPIM), INTENT (IN)::KTDIA
REAL (KIND=JPRB), INTENT (IN)::PAPRS (:, 0:, :) ! (KLON, 0:KLEV)
REAL (KIND=JPRB), INTENT (IN)::PAPRSF (:, :, :) ! (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PDELP (:, :, :) ! (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PNBVNO (:, 0:, :) ! (KLON, 0:KLEV)
REAL (KIND=JPRB), INTENT (IN)::PRDELP (:, :, :) ! (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PU (:, :, :) ! (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PV (:, :, :) ! (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PRCORI (:, :) ! (KLON)
REAL (KIND=JPRB), INTENT (IN)::PGETRL (:, :) ! (KLON)
REAL (KIND=JPRB), INTENT (IN)::PGWDCS (:, :) ! (KLON)
REAL (KIND=JPRB), INTENT (IN)::PVRLAN (:, :) ! (KLON)
REAL (KIND=JPRB), INTENT (IN)::PVRLDI (:, :) ! (KLON)
REAL (KIND=JPRB), INTENT (OUT)::PSTRDU (:, 0:, :) ! (KLON, 0:KLEV)
REAL (KIND=JPRB), INTENT (OUT)::PSTRDV (:, 0:, :) ! (KLON, 0:KLEV)
REAL (KIND=JPRB), INTENT (OUT)::PRAPTRAJ (:, 0:, :) ! (KLON, 0:KLEV)
TYPE (FXTRAN_ACDC_STACK), INTENT (IN) :: YDOFFSET
INTEGER, INTENT (IN) :: KGPBLKS
LOGICAL, INTENT (IN) :: LDACC
fxtran_acdc_temp (REAL(KIND=JPRB), ZZCV, (KLON,KGPBLKS))
fxtran_acdc_temp (REAL(KIND=JPRB), ZZCU, (KLON,KGPBLKS))
fxtran_acdc_temp (REAL(KIND=JPRB), ZZCR, (KLON,KGPBLKS))
fxtran_acdc_temp (REAL(KIND=JPRB), ZZBB, (KLON,KGPBLKS))
fxtran_acdc_temp (REAL(KIND=JPRB), ZZAA, (KLON,KGPBLKS))
fxtran_acdc_temp (REAL(KIND=JPRB), ZWGHTK, (KLON,KGPBLKS))
fxtran_acdc_temp (REAL(KIND=JPRB), ZVSUR, (KLON,KGPBLKS))
fxtran_acdc_temp (REAL(KIND=JPRB), ZUSUR, (KLON,KGPBLKS))
fxtran_acdc_temp (REAL(KIND=JPRB), ZUSR, (KLON,KGPBLKS))
fxtran_acdc_temp (REAL(KIND=JPRB), ZTST2, (KLON,KGPBLKS))
fxtran_acdc_temp (REAL(KIND=JPRB), ZTST1, (KLON,KGPBLKS))
fxtran_acdc_temp (REAL(KIND=JPRB), ZSUSR, (KLON,KGPBLKS))
fxtran_acdc_temp (REAL(KIND=JPRB), ZSUMV, (KLON,KGPBLKS))
fxtran_acdc_temp (REAL(KIND=JPRB), ZSUMU, (KLON,KGPBLKS))
fxtran_acdc_temp (REAL(KIND=JPRB), ZSUMF, (KLON,KGPBLKS))
fxtran_acdc_temp (REAL(KIND=JPRB), ZSUMD, (KLON,KGPBLKS))
fxtran_acdc_temp (REAL(KIND=JPRB), ZSUM, (KLON,KGPBLKS))
fxtran_acdc_temp (REAL(KIND=JPRB), ZSTVS, (KLON,KGPBLKS))
fxtran_acdc_temp (REAL(KIND=JPRB), ZSTUS, (KLON,KGPBLKS))
fxtran_acdc_temp (REAL(KIND=JPRB), ZSTS, (KLON,KGPBLKS))
fxtran_acdc_temp (REAL(KIND=JPRB), ZSTM, (KLON,KGPBLKS))
fxtran_acdc_temp (REAL(KIND=JPRB), ZREF, (KLON,KGPBLKS))
fxtran_acdc_temp (REAL(KIND=JPRB), ZPR2, (KLON,KGPBLKS))
fxtran_acdc_temp (REAL(KIND=JPRB), ZPR1, (KLON,KGPBLKS))
fxtran_acdc_temp (REAL(KIND=JPRB), ZOBST, (KLON,KGPBLKS))
fxtran_acdc_temp (REAL(KIND=JPRB), ZFACS, (KLON,KGPBLKS))
fxtran_acdc_temp (REAL(KIND=JPRB), ZDS2, (KLON,KGPBLKS))
fxtran_acdc_temp (REAL(KIND=JPRB), ZDS1, (KLON,KGPBLKS))
fxtran_acdc_temp (REAL(KIND=JPRB), ZWGHT, (KLON,0:KLEV,KGPBLKS))
fxtran_acdc_temp (REAL(KIND=JPRB), ZV, (KLON,KLEV,KGPBLKS))
fxtran_acdc_temp (REAL(KIND=JPRB), ZU, (KLON,KLEV,KGPBLKS))
fxtran_acdc_temp (REAL(KIND=JPRB), ZRAPP, (KLON,0:KLEV,KGPBLKS))
fxtran_acdc_temp (REAL(KIND=JPRB), ZPOID, (KLON,KLEV,KGPBLKS))
fxtran_acdc_temp (REAL(KIND=JPRB), ZNFNO, (KLON,0:KLEV,KGPBLKS))
fxtran_acdc_temp (REAL(KIND=JPRB), ZIPOI, (KLON,KLEV,KGPBLKS))
INTEGER (KIND=JPIM)::JLON
INTEGER (KIND=JPIM)::JLEV
REAL (KIND=JPRB)::ZRZR
REAL (KIND=JPRB)::ZZPR
REAL (KIND=JPRB)::ZX
REAL (KIND=JPRB)::ZVSTAR
REAL (KIND=JPRB)::ZUSTAR
REAL (KIND=JPRB)::ZTUNE
fxtran_acdc_temp (REAL(KIND=JPRB), ZTEMPF, (KLON,KGPBLKS))
REAL (KIND=JPRB)::ZRZ
REAL (KIND=JPRB)::ZPRRAP
REAL (KIND=JPRB)::ZPBLF
REAL (KIND=JPRB)::ZPBL
REAL (KIND=JPRB)::ZLIFTG
REAL (KIND=JPRB)::ZLIFT
REAL (KIND=JPRB)::ZGDTI
REAL (KIND=JPRB)::ZGDT
REAL (KIND=JPRB)::ZFORCL
REAL (KIND=JPRB)::ZFORCB
REAL (KIND=JPRB)::ZFORCA
REAL (KIND=JPRB)::ZEPS6
REAL (KIND=JPRB)::ZEPS5
REAL (KIND=JPRB)::ZEPS4
REAL (KIND=JPRB)::ZEPS3
REAL (KIND=JPRB)::ZEPS2
REAL (KIND=JPRB)::ZEPS1
REAL (KIND=JPRB)::ZDX
REAL (KIND=JPRB)::ZDV
REAL (KIND=JPRB)::ZDU
REAL (KIND=JPRB)::ZDIFSV
REAL (KIND=JPRB)::ZDIFSU
REAL (KIND=JPRB)::ZDIFSR
REAL (KIND=JPRB)::ZDEL2
REAL (KIND=JPRB)::ZDEL1
REAL (KIND=JPRB)::ZD
REAL (KIND=JPRB)::ZBETA
REAL (KIND=JPRB)::ZAUSR
REAL (KIND=JPRB)::ZARGLI
REAL (KIND=JPRB)::ZALTI
REAL (KIND=JPRB)::ZALPHA
REAL (KIND=JPRB)::ZALP2
REAL (KIND=JPRB)::ZALP1
REAL (KIND=JPRB)::ZA
fxtran_acdc_temp (REAL(KIND=JPRB), ZCOS, (KLON,KGPBLKS))
LOGICAL::LLTEST
REAL (KIND=JPHOOK)::ZHOOK_HANDLE
TYPE (FXTRAN_ACDC_STACK) :: YLSTACK0
TYPE (FXTRAN_ACDC_STACK) :: YLSTACK
TYPE (FXTRAN_ACDC_STACK) :: YLOFFSET
INTEGER :: JBLK

!$ACC DATA &
!$ACC&IF (LDACC) &
!$ACC&PRESENT (PAPRS, PAPRSF, PDELP, PGETRL, PGWDCS, PNBVNO, PRAPTRAJ, PRCORI, PRDELP, &
!$ACC&         PSTRDU, PSTRDV, PU, PV, PVRLAN, PVRLDI, YDCST, YDML_PHY_MF) 

#ifdef __PGI
YLSTACK = fxtran_acdc_stack_init (YLSTACK, 1, 1, YDOFFSET)
#endif
YLSTACK0 = YLSTACK
fxtran_acdc_stack_alloc (ZCOS)
fxtran_acdc_stack_alloc (ZTEMPF)
fxtran_acdc_stack_alloc (ZIPOI)
fxtran_acdc_stack_alloc (ZNFNO)
fxtran_acdc_stack_alloc (ZPOID)
fxtran_acdc_stack_alloc (ZRAPP)
fxtran_acdc_stack_alloc (ZU)
fxtran_acdc_stack_alloc (ZV)
fxtran_acdc_stack_alloc (ZWGHT)
fxtran_acdc_stack_alloc (ZDS1)
fxtran_acdc_stack_alloc (ZDS2)
fxtran_acdc_stack_alloc (ZFACS)
fxtran_acdc_stack_alloc (ZOBST)
fxtran_acdc_stack_alloc (ZPR1)
fxtran_acdc_stack_alloc (ZPR2)
fxtran_acdc_stack_alloc (ZREF)
fxtran_acdc_stack_alloc (ZSTM)
fxtran_acdc_stack_alloc (ZSTS)
fxtran_acdc_stack_alloc (ZSTUS)
fxtran_acdc_stack_alloc (ZSTVS)
fxtran_acdc_stack_alloc (ZSUM)
fxtran_acdc_stack_alloc (ZSUMD)
fxtran_acdc_stack_alloc (ZSUMF)
fxtran_acdc_stack_alloc (ZSUMU)
fxtran_acdc_stack_alloc (ZSUMV)
fxtran_acdc_stack_alloc (ZSUSR)
fxtran_acdc_stack_alloc (ZTST1)
fxtran_acdc_stack_alloc (ZTST2)
fxtran_acdc_stack_alloc (ZUSR)
fxtran_acdc_stack_alloc (ZUSUR)
fxtran_acdc_stack_alloc (ZVSUR)
fxtran_acdc_stack_alloc (ZWGHTK)
fxtran_acdc_stack_alloc (ZZAA)
fxtran_acdc_stack_alloc (ZZBB)
fxtran_acdc_stack_alloc (ZZCR)
fxtran_acdc_stack_alloc (ZZCU)
fxtran_acdc_stack_alloc (ZZCV)
YLOFFSET = YLSTACK - YLSTACK0 + YDOFFSET


!$ACC DATA &
!$ACC&IF (LDACC) &
!$ACC&PRESENT (ZCOS, ZDS1, ZDS2, ZFACS, ZIPOI, ZNFNO, ZOBST, ZPOID, ZPR1, ZPR2, ZRAPP, ZREF, &
!$ACC&         ZSTM, ZSTS, ZSTUS, ZSTVS, ZSUM, ZSUMD, ZSUMF, ZSUMU, ZSUMV, ZSUSR, ZTEMPF, &
!$ACC&         ZTST1, ZTST2, ZU, ZUSR, ZUSUR, ZV, ZVSUR, ZWGHT, ZWGHTK, ZZAA, ZZBB, ZZCR, &
!$ACC&         ZZCU, ZZCV) 

IF (LHOOK) CALL DR_HOOK ('ACDRAG_MANYBLOCKS', 0, ZHOOK_HANDLE)


!$ACC PARALLEL LOOP GANG &
!$ACC&IF (LDACC) &
!$ACC&PRIVATE (JBLK) &
!$ACC&VECTOR_LENGTH (KLON) 


DO JBLK = 1, KGPBLKS
  
  !$ACC LOOP VECTOR &
  !$ACC&PRIVATE (JLON) 

  

  DO JLON = KIDIA, MERGE (KLON, KFDIA, JBLK < KGPBLKS)
    PRAPTRAJ (JLON,:, JBLK)=0.0
  ENDDO

ENDDO

ZGDT=YDCST%RG*YDML_PHY_MF%YRPHY2%TSPHY
ZGDTI=1.0_JPRB/ZGDT

IF (YDML_PHY_MF%YRPHY0%GWDPROF==0.0_JPRB) THEN
  ZZPR=0.5_JPRB
ELSE
  ZZPR=((1.0_JPRB+YDML_PHY_MF%YRPHY0%GWDPROF)*LOG (1.0_JPRB+YDML_PHY_MF%YRPHY0&
  &%GWDPROF)-YDML_PHY_MF%YRPHY0%GWDPROF)/YDML_PHY_MF%YRPHY0%GWDPROF**2
ENDIF

ZLIFT=YDML_PHY_MF%YRPHY0%GWDLT*YDML_PHY_MF%YRPHY2%TSPHY/(YDML_PHY_MF%YRPHY0%HOBST*ZZPR)
ZLIFTG=YDML_PHY_MF%YRPHY0%GWDLT/(YDML_PHY_MF%YRPHY0%HOBST*ZZPR)

IF (.NOT.YDML_PHY_MF%YRPHY%LGLT) THEN
  ZLIFTG=0.0_JPRB
ENDIF

ZALP1=0.75_JPRB+0.25_JPRB*LOG (16._JPRB)
ZALP2=3.5_JPRB*YDCST%RPI-LOG (16._JPRB)-8._JPRB
ZDEL1=2.75_JPRB-0.75_JPRB*LOG (16._JPRB)
ZDEL2=-0.25_JPRB*YDCST%RPI-LOG (16._JPRB)+4._JPRB
ZEPS1=1.E-06_JPRB
ZEPS2=1.E-04_JPRB
ZEPS3=1.E-09_JPRB
ZEPS4=1.E-05_JPRB
ZEPS5=1.E-02_JPRB

IF (JPRB==JPRD) THEN
  ZEPS6=1.E-12_JPRB
ELSE
  ZEPS6=1.E-6_JPRB
ENDIF

ZARGLI=1.E+06_JPRB
ZBETA=MIN (YDML_PHY_MF%YRPHY0%GWDVALI, 1.0_JPRB-ZEPS6)

!$ACC PARALLEL LOOP GANG &
!$ACC&IF (LDACC) &
!$ACC&PRIVATE (JBLK) &
!$ACC&VECTOR_LENGTH (KLON) 


DO JBLK = 1, KGPBLKS
  
  !$ACC LOOP VECTOR &
  !$ACC&PRIVATE (JLEV, JLON) 

  

  DO JLON = KIDIA, MERGE (KLON, KFDIA, JBLK < KGPBLKS)

    DO JLEV=KTDIA, KLEV
      
      ZPOID (JLON, JLEV, JBLK)=PDELP (JLON, JLEV, JBLK)*ZGDTI
      ZIPOI (JLON, JLEV, JBLK)=PRDELP (JLON, JLEV, JBLK)*ZGDT
      ZWGHT (JLON, JLEV, JBLK)=0.0_JPRB
    
    ENDDO

    
    ZOBST (JLON, JBLK)=MIN (PAPRS (JLON, KLEV, JBLK)-PAPRSF (JLON, KTDIA, JBLK), MAX (PAPRS (JLON, KLEV, JBLK&
    &)-PAPRSF (JLON, KLEV, JBLK), YDML_PHY_MF%YRPHY0%HOBST*PGETRL (JLON, JBLK)*PGWDCS (JLON, JBLK)))
    ZWGHT (JLON, KLEV, JBLK)=(PAPRS (JLON, KLEV, JBLK)-PAPRSF (JLON, KLEV, JBLK))/ZOBST (JLON, JBLK)
    ZWGHT (JLON, KLEV, JBLK)=ZWGHT (JLON, KLEV, JBLK)*(1.0_JPRB-ZBETA)
    ZWGHTK (JLON, JBLK)=ZWGHT (JLON, KLEV, JBLK)
    ZSUMU (JLON, JBLK)=ZWGHT (JLON, KLEV, JBLK)*PU (JLON, KLEV, JBLK)
    ZSUMV (JLON, JBLK)=ZWGHT (JLON, KLEV, JBLK)*PV (JLON, KLEV, JBLK)
    ZSUMF (JLON, JBLK)=ZWGHT (JLON, KLEV, JBLK)*PNBVNO (JLON, KLEV, JBLK)
  
  ENDDO

ENDDO



!$ACC PARALLEL LOOP GANG &
!$ACC&IF (LDACC) &
!$ACC&PRIVATE (JBLK) &
!$ACC&VECTOR_LENGTH (KLON) 


DO JBLK = 1, KGPBLKS
  
  !$ACC LOOP VECTOR &
  !$ACC&PRIVATE (JLEV, JLON, LLTEST, ZALTI) 

  

  DO JLON = KIDIA, MERGE (KLON, KFDIA, JBLK < KGPBLKS)

    DO JLEV=KLEV-1, KTDIA,-1

      IF (JLEV==KLEV-1) THEN
        LLTEST=.TRUE.
      ELSE
        LLTEST=ZWGHT (JLON, JLEV+1, JBLK)>0.0_JPRB
      ENDIF


      IF (LLTEST) THEN
        
        ZWGHT (JLON, JLEV, JBLK)=MAX (0.0_JPRB,(PAPRSF (JLON, JLEV+1, JBLK)-MAX (PAPRSF (JLON&
        &, JLEV, JBLK), PAPRS (JLON, KLEV, JBLK)-ZOBST (JLON, JBLK)))/ZOBST (JLON, JBLK))
        ZALTI=MIN (1.0_JPRB,(PAPRS (JLON, KLEV, JBLK)-PAPRS (JLON, JLEV, JBLK))/ZOBST (JLON, JBLK))
        ZWGHT (JLON, JLEV, JBLK)=ZWGHT (JLON, JLEV, JBLK)*(1.0_JPRB-ZBETA*&
        &((1.0_JPRB-ZALTI)/(1.0_JPRB+YDML_PHY_MF%YRPHY0%GWDPROF*ZALTI)))
        ZWGHTK (JLON, JBLK)=ZWGHTK (JLON, JBLK)+ZWGHT (JLON, JLEV, JBLK)
        ZSUMU (JLON, JBLK)=ZSUMU (JLON, JBLK)+0.5_JPRB*ZWGHT (JLON, JLEV&
        &, JBLK)*(PU (JLON, JLEV, JBLK)+PU (JLON, JLEV+1, JBLK))
        ZSUMV (JLON, JBLK)=ZSUMV (JLON, JBLK)+0.5_JPRB*ZWGHT (JLON, JLEV&
        &, JBLK)*(PV (JLON, JLEV, JBLK)+PV (JLON, JLEV+1, JBLK))
        ZSUMF (JLON, JBLK)=ZSUMF (JLON, JBLK)+ZWGHT (JLON, JLEV, JBLK)*PNBVNO (JLON, JLEV, JBLK)
      
      ENDIF

    ENDDO

  ENDDO

ENDDO


!$ACC PARALLEL LOOP GANG &
!$ACC&IF (LDACC) &
!$ACC&PRIVATE (JBLK) &
!$ACC&VECTOR_LENGTH (KLON) 


DO JBLK = 1, KGPBLKS
  
  !$ACC LOOP VECTOR &
  !$ACC&PRIVATE (JLEV, JLON, ZPBLF) 

  

  DO JLON = KIDIA, MERGE (KLON, KFDIA, JBLK < KGPBLKS)

    DO JLEV=KTDIA, KLEV
      
      ZWGHT (JLON, JLEV, JBLK)=ZWGHT (JLON, JLEV, JBLK)*(1.0_JPRB/ZWGHTK (JLON, JBLK))
    
    ENDDO

    
    ZSUMU (JLON, JBLK)=ZSUMU (JLON, JBLK)*(1.0_JPRB/ZWGHTK (JLON, JBLK))
    ZSUMV (JLON, JBLK)=ZSUMV (JLON, JBLK)*(1.0_JPRB/ZWGHTK (JLON, JBLK))
    ZSUMF (JLON, JBLK)=ZSUMF (JLON, JBLK)*(1.0_JPRB/ZWGHTK (JLON, JBLK))
    
    
    ZNFNO (JLON, KLEV, JBLK)=SQRT (MAX (0.0_JPRB, ZSUMF (JLON, JBLK)))
    ZPBLF=1.0_JPRB-MIN (1.0_JPRB,(PAPRS (JLON, KLEV, JBLK&
    &)-PAPRSF (JLON, KLEV, JBLK))/ZOBST (JLON, JBLK))
    ZU (JLON, KLEV, JBLK)=PU (JLON, KLEV, JBLK)+ZPBLF*(ZSUMU (JLON, JBLK)-PU (JLON, KLEV, JBLK))
    ZV (JLON, KLEV, JBLK)=PV (JLON, KLEV, JBLK)+ZPBLF*(ZSUMV (JLON, JBLK)-PV (JLON, KLEV, JBLK))
  
  ENDDO

ENDDO




!$ACC PARALLEL LOOP GANG &
!$ACC&IF (LDACC) &
!$ACC&PRIVATE (JBLK) &
!$ACC&VECTOR_LENGTH (KLON) 


DO JBLK = 1, KGPBLKS
  
  !$ACC LOOP VECTOR &
  !$ACC&PRIVATE (JLEV, JLON, ZPBL, ZPBLF) 

  

  DO JLON = KIDIA, MERGE (KLON, KFDIA, JBLK < KGPBLKS)

    DO JLEV=KLEV-1, KTDIA,-1
      
      ZPBL=1.0_JPRB-MIN (1.0_JPRB,(PAPRS (JLON, KLEV, JBLK)-PAPRS (JLON, JLEV, JBLK))/ZOBST (JLON, JBLK))
      ZNFNO (JLON, JLEV, JBLK)=SQRT (MAX (0.0_JPRB, PNBVNO (JLON, JLEV&
      &, JBLK)+ZPBL*(ZSUMF (JLON, JBLK)-PNBVNO (JLON, JLEV, JBLK))))
      ZPBLF=1.0_JPRB-MIN (1.0_JPRB,(PAPRS (JLON, KLEV, JBLK&
      &)-PAPRSF (JLON, JLEV, JBLK))/ZOBST (JLON, JBLK))
      ZU (JLON, JLEV, JBLK)=PU (JLON, JLEV, JBLK)+ZPBLF*(ZSUMU (JLON, JBLK)-PU (JLON, JLEV, JBLK))
      ZV (JLON, JLEV, JBLK)=PV (JLON, JLEV, JBLK)+ZPBLF*(ZSUMV (JLON, JBLK)-PV (JLON, JLEV, JBLK))
    
    ENDDO

  ENDDO

ENDDO


!$ACC PARALLEL LOOP GANG &
!$ACC&IF (LDACC) &
!$ACC&PRIVATE (JBLK) &
!$ACC&VECTOR_LENGTH (KLON) 


DO JBLK = 1, KGPBLKS
  
  !$ACC LOOP VECTOR &
  !$ACC&PRIVATE (JLON, ZA, ZD, ZTUNE, ZUSTAR, ZVSTAR) 

  

  DO JLON = KIDIA, MERGE (KLON, KFDIA, JBLK < KGPBLKS)
    
    ZUSTAR=ZSUMU (JLON, JBLK)*COS (2.0_JPRB*PVRLDI (JLON, JBLK)&
    &)+ZSUMV (JLON, JBLK)*SIN (2.0_JPRB*PVRLDI (JLON, JBLK))
    ZVSTAR=ZSUMU (JLON, JBLK)*SIN (2.0_JPRB*PVRLDI (JLON, JBLK)&
    &)-ZSUMV (JLON, JBLK)*COS (2.0_JPRB*PVRLDI (JLON, JBLK))
    ZA=PVRLAN (JLON, JBLK)**2+0.5_JPRB*(4._JPRB*(1.0_JPRB-PVRLAN (JLON, JBLK))*(1&
    &.0_JPRB+ZALP1*PVRLAN (JLON, JBLK))+PVRLAN (JLON, JBLK)*LOG (1.0_JPRB/MAX (ZEPS1&
    &, PVRLAN (JLON, JBLK)))*(1.0_JPRB+ZALP2*PVRLAN (JLON, JBLK)))/YDCST%RPI
    ZD=0.5_JPRB*(4._JPRB*(1.0_JPRB-PVRLAN (JLON, JBLK))*(1.0_JPRB+ZDEL1*PVRLAN&
    & (JLON, JBLK))-3._JPRB*PVRLAN (JLON, JBLK)*LOG (1.0_JPRB/MAX (ZEPS1, PVRLAN&
    & (JLON, JBLK)))*(1.0_JPRB+ZDEL2*PVRLAN (JLON, JBLK)))/YDCST%RPI
    ZUSUR (JLON, JBLK)=ZA*ZSUMU (JLON, JBLK)+ZD*ZUSTAR
    ZVSUR (JLON, JBLK)=ZA*ZSUMV (JLON, JBLK)+ZD*ZVSTAR
    ZSUSR (JLON, JBLK)=MAX (ZEPS2, ZSUMU (JLON, JBLK)*ZUSUR&
    & (JLON, JBLK)+ZSUMV (JLON, JBLK)*ZVSUR (JLON, JBLK))
    ZUSR (JLON, JBLK)=SQRT (ZUSUR (JLON, JBLK)**2+ZVSUR (JLON, JBLK)**2)
    ZFACS (JLON, JBLK)=ZNFNO (JLON, KLEV, JBLK)/ZSUSR (JLON, JBLK)**3
    ZRAPP (JLON, KLEV, JBLK)=1.0_JPRB
    ZSTUS (JLON, JBLK)=YDML_PHY_MF%YRPHY0%GWDSE*PGWDCS (JLON, JBLK)**2*ZNFNO&
    & (JLON, KLEV, JBLK)*PGETRL (JLON, JBLK)*ZUSUR (JLON, JBLK)
    ZSTVS (JLON, JBLK)=YDML_PHY_MF%YRPHY0%GWDSE*PGWDCS (JLON, JBLK)**2*ZNFNO&
    & (JLON, KLEV, JBLK)*PGETRL (JLON, JBLK)*ZVSUR (JLON, JBLK)
    ZTST1 (JLON, JBLK)=1.0_JPRB
    ZPR1 (JLON, JBLK)=PAPRSF (JLON, KLEV, JBLK)
    ZSUM (JLON, JBLK)=(PAPRS (JLON, KLEV, JBLK)-PAPRSF (JLON, KLEV, JBLK&
    &))*ZNFNO (JLON, KLEV, JBLK)*ZUSR (JLON, JBLK)/ZSUSR (JLON, JBLK)
    ZTST2 (JLON, JBLK)=1.0_JPRB
    ZPR2 (JLON, JBLK)=PAPRSF (JLON, KLEV, JBLK)
    ZREF (JLON, JBLK)=1.0_JPRB
    ZTUNE=YDML_PHY_MF%YRPHY0%GWDBC*(ZUSR (JLON, JBLK)**2/ZSUSR (JLON, JBLK))**2
    ZTEMPF (JLON, JBLK)=ZUSR (JLON, JBLK)/MAX (ZEPS5, ZTUNE*YDML_PHY_MF%YRPHY0%HOBST&
    &*PGETRL (JLON, JBLK)*PGWDCS (JLON, JBLK)*ZNFNO (JLON, KLEV, JBLK))
    ZZBB (JLON, JBLK)=MAX (0.0_JPRB, 1.0_JPRB-MAX (ZTEMPF (JLON, JBLK), ZEPS6))
    ZZAA (JLON, JBLK)=YDML_PHY_MF%YRPHY0%GWDCD*ZZBB (JLON, JBLK)*ZTUNE*(1.0_JPRB-ZZBB (JLON, JBLK))

    IF (YDML_PHY_MF%YRPHY%LNEWD) THEN
      ZSTUS (JLON, JBLK)=ZSTUS (JLON, JBLK)*(1.0_JPRB-ZZBB &
      &(JLON, JBLK))/MAX (1.0_JPRB, ZTEMPF (JLON, JBLK))
      ZSTVS (JLON, JBLK)=ZSTVS (JLON, JBLK)*(1.0_JPRB-ZZBB &
      &(JLON, JBLK))/MAX (1.0_JPRB, ZTEMPF (JLON, JBLK))
      ZZAA (JLON, JBLK)=YDML_PHY_MF%YRPHY0%GWDCD*ZZBB (JLON, JBLK)
    ENDIF

  
  ENDDO

ENDDO


!$ACC PARALLEL LOOP GANG &
!$ACC&IF (LDACC) &
!$ACC&PRIVATE (JBLK) &
!$ACC&VECTOR_LENGTH (KLON) 


DO JBLK = 1, KGPBLKS
  
  !$ACC LOOP VECTOR &
  !$ACC&PRIVATE (JLEV, JLON) 

  

  DO JLON = KIDIA, MERGE (KLON, KFDIA, JBLK < KGPBLKS)

    DO JLEV=0, KLEV
      
      PRAPTRAJ (JLON, JLEV, JBLK)=YDML_PHY_MF%YRPHY0%GWDSE*PGWDCS (JLON&
      &, JBLK)**2*ZNFNO (JLON, KLEV, JBLK)*PGETRL (JLON, JBLK)

      

      IF (YDML_PHY_MF%YRPHY%LNEWD) THEN
        
        PRAPTRAJ (JLON, JLEV, JBLK)=PRAPTRAJ (JLON, JLEV, JBLK)*(1.0_JPRB&
        &-ZZBB (JLON, JBLK))/MAX (1.0_JPRB, ZTEMPF (JLON, JBLK))
      
      ENDIF

    ENDDO

  ENDDO

ENDDO


!$ACC PARALLEL LOOP GANG &
!$ACC&IF (LDACC) &
!$ACC&PRIVATE (JBLK) &
!$ACC&VECTOR_LENGTH (KLON) 


DO JBLK = 1, KGPBLKS
  
  !$ACC LOOP VECTOR &
  !$ACC&PRIVATE (JLEV, JLON, ZAUSR, ZPRRAP) 

  

  DO JLON = KIDIA, MERGE (KLON, KFDIA, JBLK < KGPBLKS)

    DO JLEV=KLEV-1, KTDIA,-1
      
      ZAUSR=0.5_JPRB*((ZU (JLON, JLEV, JBLK)+ZU (JLON, JLEV+1, JBLK))*ZUSUR (JLON, JBLK&
      &)+(ZV (JLON, JLEV, JBLK)+ZV (JLON, JLEV+1, JBLK))*ZVSUR (JLON, JBLK))
      ZPRRAP=ZFACS (JLON, JBLK)*ZAUSR**3/MAX (ZEPS3, ZNFNO (JLON, JLEV, JBLK))
      ZRAPP (JLON, JLEV, JBLK)=MAX (0.0_JPRB, MIN (ZRAPP (JLON, JLEV+1, JBLK), ZPRRAP))
      ZTST1 (JLON, JBLK)=ZTST1 (JLON, JBLK)*MAX (0.0_JPRB, SIGN (1.0_JPRB, ZPRRAP-1.0_JPRB))
      ZPR1 (JLON, JBLK)=ZPR1 (JLON, JBLK)+ZTST1 (JLON, JBLK)*(PAPRSF (JLON, JLEV, JBLK)-ZPR1 (JLON, JBLK))
      ZSUM (JLON, JBLK)=ZSUM (JLON, JBLK)+ZTST1 (JLON, JBLK)*(PAPRSF (JLON, JLEV+1, JBLK)-PAPRSF&
      & (JLON, JLEV, JBLK))*ZNFNO (JLON, JLEV, JBLK)*ZUSR (JLON, JBLK)/MAX (ZEPS2, ZAUSR)
      ZTST2 (JLON, JBLK)=ZTST2 (JLON, JBLK)*(1.0_JPRB-MAX (0.0_JPRB&
      &, SIGN (1.0_JPRB, 0.0_JPRB-ZNFNO (JLON, JLEV, JBLK))))
      ZPR2 (JLON, JBLK)=ZPR2 (JLON, JBLK)+ZTST2 (JLON, JBLK)*(PAPRSF (JLON, JLEV, JBLK)-ZPR2 (JLON, JBLK))
      ZREF (JLON, JBLK)=ZREF (JLON, JBLK)+ZTST2 (JLON, JBLK)*(ZRAPP (JLON, JLEV, JBLK)-ZREF (JLON, JBLK))
    
    ENDDO

  ENDDO

ENDDO


!$ACC PARALLEL LOOP GANG &
!$ACC&IF (LDACC) &
!$ACC&PRIVATE (JBLK) &
!$ACC&VECTOR_LENGTH (KLON) 


DO JBLK = 1, KGPBLKS
  
  !$ACC LOOP VECTOR &
  !$ACC&PRIVATE (JLON) 

  

  DO JLON = KIDIA, MERGE (KLON, KFDIA, JBLK < KGPBLKS)
    
    PSTRDU (JLON, KTDIA-1, JBLK)=0.0_JPRB
    PSTRDV (JLON, KTDIA-1, JBLK)=0.0_JPRB
    ZRAPP (JLON, KTDIA-1, JBLK)=0.0_JPRB
    PRAPTRAJ (JLON, KTDIA-1, JBLK)=0.0_JPRB
    ZSTM (JLON, JBLK)=1.0_JPRB/SQRT (1.0_JPRB+MAX (0.0_JPRB, SIGN (1.0_JPRB, ZPR1&
    & (JLON, JBLK)-ZPR2 (JLON, JBLK)-ZEPS4))*YDML_PHY_MF%YRPHY0%GWDAMP*(2.0_JPRB&
    &*SIN (MIN (ZARGLI, ZSUM (JLON, JBLK)))+YDML_PHY_MF%YRPHY0%GWDAMP))

    IF (YDML_PHY_MF%YRPHY%LNEWD) THEN
      ZSTM (JLON, JBLK)=ZSTM (JLON, JBLK)/(1.0_JPRB-ZZBB (JLON, JBLK))
      ZREF (JLON, JBLK)=ZREF (JLON, JBLK)/(1.0_JPRB-ZZBB (JLON, JBLK))
    ENDIF

    ZDS1 (JLON, JBLK)=MAX (0.0_JPRB, ZSTM (JLON, JBLK)-1.0_JPRB&
    &)/(PAPRS (JLON, KLEV, JBLK)-ZPR1 (JLON, JBLK))
    ZSTS (JLON, JBLK)=MIN (ZREF (JLON, JBLK)*(1.0_JPRB-ZTST2 (JLON, JBLK)), ZSTM (JLON, JBLK))
    ZDS2 (JLON, JBLK)=ZSTS (JLON, JBLK)/(PAPRS (JLON, KLEV, JBLK)-ZPR2 (JLON, JBLK))
    
    
    ZZCR (JLON, JBLK)=ZRAPP (JLON, KLEV, JBLK)*ZSTM (JLON, JBLK)
  
  ENDDO

ENDDO



!$ACC PARALLEL LOOP GANG &
!$ACC&IF (LDACC) &
!$ACC&PRIVATE (JBLK) &
!$ACC&VECTOR_LENGTH (KLON) 


DO JBLK = 1, KGPBLKS
  
  !$ACC LOOP VECTOR &
  !$ACC&PRIVATE (JLEV, JLON, ZRZ, ZRZR) 

  

  DO JLON = KIDIA, MERGE (KLON, KFDIA, JBLK < KGPBLKS)

    DO JLEV=KTDIA, KLEV
      
      ZRAPP (JLON, JLEV, JBLK)=ZDS2 (JLON, JBLK)*MAX (0.0_JPRB, PAPRS (JLON, JLEV, JBLK)-ZPR2 (JLON&
      &, JBLK))+MAX (0.0_JPRB, MIN (ZSTM (JLON, JBLK), ZRAPP (JLON, JLEV, JBLK)+ZDS1 (JLON, JBLK&
      &)*MAX (0.0_JPRB, PAPRS (JLON, JLEV, JBLK)-ZPR1 (JLON, JBLK)))-ZSTS (JLON, JBLK))
      ZRZ=(PAPRS (JLON, KLEV, JBLK)-PAPRS (JLON, JLEV, JBLK))/MAX (ZEPS4, ZZBB (JLON&
      &, JBLK)*YDML_PHY_MF%YRPHY0%HOBST*PGETRL (JLON, JBLK)*PGWDCS (JLON, JBLK))

      IF (.NOT.YDML_PHY_MF%YRPHY%LNEWD) THEN
        ZZCR (JLON, JBLK)=ZRAPP (JLON, JLEV, JBLK)
        ZRZR=1.0_JPRB
        ZRZ=MIN (1.0_JPRB, ZRZ)
      ELSE
        ZRZR=SQRT (ZZBB (JLON, JBLK)/(1.0_JPRB+ZRZ**2*ZZBB (JLON, JBLK)*(1.0_JPRB-ZZBB (JLON, JBLK))))
      ENDIF

      ZRAPP (JLON, JLEV, JBLK)=ZRAPP (JLON, JLEV, JBLK)+ZZCR (JLON, JBLK)*(ZZAA (JLON, JBLK)*SQRT (MAX (0&
      &.0_JPRB,(1.0_JPRB-ZRZ*ZRZR)**3/(1.0_JPRB+ZRZ*YDML_PHY_MF%YRPHY0%GWDPROF*ZZBB (JLON, JBLK)))))
    
    ENDDO

    
    ZZCR (JLON, JBLK)=ZRAPP (JLON, KTDIA-1, JBLK)
  
  ENDDO

ENDDO



!$ACC PARALLEL LOOP GANG &
!$ACC&IF (LDACC) &
!$ACC&PRIVATE (JBLK) &
!$ACC&VECTOR_LENGTH (KLON) 


DO JBLK = 1, KGPBLKS
  
  !$ACC LOOP VECTOR &
  !$ACC&PRIVATE (JLEV, JLON, ZALTI, ZDIFSR) 

  

  DO JLON = KIDIA, MERGE (KLON, KFDIA, JBLK < KGPBLKS)

    DO JLEV=KTDIA, KLEV
      
      ZDIFSR=ZRAPP (JLON, JLEV, JBLK)-ZZCR (JLON, JBLK)
      ZZCR (JLON, JBLK)=ZRAPP (JLON, JLEV, JBLK)
      ZALTI=MIN (1.0_JPRB,(PAPRS (JLON, KLEV, JBLK)-PAPRSF (JLON, JLEV, JBLK))/ZOBST (JLON, JBLK))
      ZRAPP (JLON, JLEV, JBLK)=ZRAPP (JLON, JLEV-1, JBLK)+ZDIFSR*(1.0_JPRB+ZLIFTG&
      &*(1.0_JPRB-ZALTI)/(1.0_JPRB+ZALTI*YDML_PHY_MF%YRPHY0%GWDPROF))*(1.0_JPRB-ZBETA&
      &*((1.0_JPRB-ZALTI)/(1.0_JPRB+YDML_PHY_MF%YRPHY0%GWDPROF*ZALTI)))
      PSTRDU (JLON, JLEV, JBLK)=ZRAPP (JLON, JLEV, JBLK)*ZSTUS (JLON, JBLK)
      PSTRDV (JLON, JLEV, JBLK)=ZRAPP (JLON, JLEV, JBLK)*ZSTVS (JLON, JBLK)
      PRAPTRAJ (JLON, JLEV, JBLK)=PRAPTRAJ (JLON, JLEV, JBLK)*ZRAPP (JLON, JLEV, JBLK)
    
    ENDDO

    
    ZSUMD (JLON, JBLK)=0.5_JPRB*ZWGHT (JLON, KTDIA, JBLK)*ZIPOI (JLON, KTDIA&
    &, JBLK)*(ZRAPP (JLON, KTDIA, JBLK)-ZRAPP (JLON, KTDIA-1, JBLK))

    

    DO JLEV=KTDIA+1, KLEV
      
      ZSUMD (JLON, JBLK)=ZSUMD (JLON, JBLK)+0.5_JPRB*(ZWGHT (JLON, JLEV, JBLK)+ZWGHT (JLON, JLEV-1&
      &, JBLK))*ZIPOI (JLON, JLEV, JBLK)*(ZRAPP (JLON, JLEV, JBLK)-ZRAPP (JLON, JLEV-1, JBLK))
    
    ENDDO

  ENDDO

ENDDO




!$ACC PARALLEL LOOP GANG &
!$ACC&IF (LDACC) &
!$ACC&PRIVATE (JBLK) &
!$ACC&VECTOR_LENGTH (KLON) 


DO JBLK = 1, KGPBLKS
  
  !$ACC LOOP VECTOR &
  !$ACC&PRIVATE (JLEV, JLON) 

  

  DO JLON = KIDIA, MERGE (KLON, KFDIA, JBLK < KGPBLKS)
    
    ZSUMD (JLON, JBLK)=ZSUMD (JLON, JBLK)+0.5_JPRB*ZWGHT (JLON, KLEV, JBLK)*ZIPOI&
    & (JLON, KLEV, JBLK)*(ZRAPP (JLON, KLEV, JBLK)-ZRAPP (JLON, KLEV-1, JBLK))
    
    
    ZSUMD (JLON, JBLK)=ZSUMD (JLON, JBLK)*SQRT (ZSTUS (JLON, JBLK)**2+ZSTVS (JLON, JBLK)**2)
    ZRAPP (JLON, KLEV, JBLK)=1.0_JPRB/(1.0_JPRB+ZSUMD (JLON, JBLK)*ZUSR (JLON, JBLK)/ZSUSR (JLON, JBLK))

    

    DO JLEV=KTDIA, KLEV
      
      PSTRDU (JLON, JLEV, JBLK)=PSTRDU (JLON, JLEV, JBLK)*ZRAPP (JLON, KLEV, JBLK)
      PSTRDV (JLON, JLEV, JBLK)=PSTRDV (JLON, JLEV, JBLK)*ZRAPP (JLON, KLEV, JBLK)
      PRAPTRAJ (JLON, JLEV, JBLK)=PRAPTRAJ (JLON, JLEV, JBLK)*ZRAPP (JLON, KLEV, JBLK)
    
    ENDDO

  ENDDO

ENDDO




!$ACC PARALLEL LOOP GANG &
!$ACC&IF (LDACC) &
!$ACC&PRIVATE (JBLK) &
!$ACC&VECTOR_LENGTH (KLON) 


DO JBLK = 1, KGPBLKS
  
  !$ACC LOOP VECTOR &
  !$ACC&PRIVATE (JLEV, JLON, ZALPHA, ZDU, ZDV, ZDX, ZX) 

  

  DO JLON = KIDIA, MERGE (KLON, KFDIA, JBLK < KGPBLKS)

    DO JLEV=KTDIA, KLEV
      
      ZDU=ZIPOI (JLON, JLEV, JBLK)*(PSTRDU (JLON, JLEV-1, JBLK)-PSTRDU (JLON, JLEV, JBLK))
      ZDV=ZIPOI (JLON, JLEV, JBLK)*(PSTRDV (JLON, JLEV-1, JBLK)-PSTRDV (JLON, JLEV, JBLK))
      ZDX=ZIPOI (JLON, JLEV, JBLK)*(ZUSUR (JLON, JBLK)*PSTRDU (JLON,&
      & JLEV, JBLK)+ZVSUR (JLON, JBLK)*PSTRDV (JLON, JLEV, JBLK))
      ZX=ZUSUR (JLON, JBLK)*PU (JLON, JLEV, JBLK)+ZVSUR (JLON, JBLK)*PV (JLON, JLEV, JBLK)
      ZALPHA=1.0_JPRB/(1.0_JPRB+ZDX/MAX (ZEPS2, ZX))
      PSTRDU (JLON, JLEV, JBLK)=PSTRDU (JLON, JLEV-1, JBLK)-ZPOID (JLON, JLEV, JBLK)*ZALPHA*ZDU
      PSTRDV (JLON, JLEV, JBLK)=PSTRDV (JLON, JLEV-1, JBLK)-ZPOID (JLON, JLEV, JBLK)*ZALPHA*ZDV
    
    ENDDO

    
    ZZCU (JLON, JBLK)=PSTRDU (JLON, KTDIA-1, JBLK)
    ZZCV (JLON, JBLK)=PSTRDV (JLON, KTDIA-1, JBLK)
  
  ENDDO

ENDDO



!$ACC PARALLEL LOOP GANG &
!$ACC&IF (LDACC) &
!$ACC&PRIVATE (JBLK) &
!$ACC&VECTOR_LENGTH (KLON) 


DO JBLK = 1, KGPBLKS
  
  !$ACC LOOP VECTOR &
  !$ACC&PRIVATE (JLEV, JLON, ZALTI, ZDIFSU, ZDIFSV, ZFORCA, ZFORCB, ZFORCL) 

  

  DO JLON = KIDIA, MERGE (KLON, KFDIA, JBLK < KGPBLKS)

    DO JLEV=KTDIA, KLEV
      
      ZDIFSU=PSTRDU (JLON, JLEV, JBLK)-ZZCU (JLON, JBLK)
      ZDIFSV=PSTRDV (JLON, JLEV, JBLK)-ZZCV (JLON, JBLK)
      ZZCU (JLON, JBLK)=PSTRDU (JLON, JLEV, JBLK)
      ZZCV (JLON, JBLK)=PSTRDV (JLON, JLEV, JBLK)
      ZALTI=MIN (1.0_JPRB,(PAPRS (JLON, KLEV, JBLK)-PAPRSF (JLON, JLEV, JBLK))/ZOBST (JLON, JBLK))
      ZFORCL=ZLIFT*PRCORI (JLON, JBLK)*(1.0_JPRB-ZALTI)/(1.0_JPRB+ZALTI*YDML_PHY_MF%YRPHY0%GWDPROF)
      ZFORCA=ZFORCL/(1.0_JPRB+0.25_JPRB*ZFORCL**2)
      ZFORCB=0.5_JPRB*ZFORCL*ZFORCA
      PSTRDU (JLON, JLEV, JBLK)=PSTRDU (JLON, JLEV-1, JBLK)+ZDIFSU+ZPOID (JLON, JLEV&
      &, JBLK)*(ZFORCB*PU (JLON, JLEV, JBLK)-ZFORCA*PV (JLON, JLEV, JBLK))
      PSTRDV (JLON, JLEV, JBLK)=PSTRDV (JLON, JLEV-1, JBLK)+ZDIFSV+ZPOID (JLON, JLEV&
      &, JBLK)*(ZFORCB*PV (JLON, JLEV, JBLK)+ZFORCA*PU (JLON, JLEV, JBLK))
    
    ENDDO

  ENDDO

ENDDO


IF (LHOOK) CALL DR_HOOK ('ACDRAG_MANYBLOCKS', 1, ZHOOK_HANDLE)
!$ACC END DATA

!$ACC END DATA

END SUBROUTINE ACDRAG_MANYBLOCKS
