!OPTIONS XOPT(NOEVAL)
PROGRAM MAIN_ACDRAG  

USE MODEL_PHYSICS_MF_MOD , ONLY : MODEL_PHYSICS_MF_TYPE
USE PARKIND1  ,ONLY : JPIM     ,JPRB    ,JPRD
USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK, JPHOOK

USE YOMCST   , ONLY : TCST
USE YOMDATA
USE UTIL_TCST_MOD !contains save method for TCST type
USE UTIL_MODEL_PHYSICS_MF_TYPE_MOD !contains save method for MODEL_PHYSICS_MF_TYPE

USE XRD_GETOPTIONS
USE XRD_UNIX_ENV

#include "fxtran_acdc_stack.h"

USE FXTRAN_ACDC_STACK_MOD

USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY : STDOUT => OUTPUT_UNIT

!-----------------------------------------------------------------------

IMPLICIT NONE
#include "acdrag.intfb.h"

TYPE(TCST) :: YDCST
TYPE(MODEL_PHYSICS_MF_TYPE) :: YDML_PHY_MF
REAL(KIND=JPRB), POINTER, DIMENSION(:, :, :) :: ZZAPRS
REAL(KIND=JPRB), POINTER, DIMENSION(:, :, :) :: ZZAPRSF
REAL(KIND=JPRB), POINTER, DIMENSION(:, :, :) :: ZZDELP
REAL(KIND=JPRB), POINTER, DIMENSION(:, :, :) :: ZZNBVNO
REAL(KIND=JPRB), POINTER, DIMENSION(:, :, :) :: ZZRDELP
REAL(KIND=JPRB), POINTER, DIMENSION(:, :, :) :: ZZU
REAL(KIND=JPRB), POINTER, DIMENSION(:, :, :) :: ZZV
REAL(KIND=JPRB), POINTER, DIMENSION(:, :) :: ZZRCORI
REAL(KIND=JPRB), POINTER, DIMENSION(:, :) :: ZZGETRL
REAL(KIND=JPRB), POINTER, DIMENSION(:, :) :: ZZGWDCS
REAL(KIND=JPRB), POINTER, DIMENSION(:, :) :: ZZVRLAN
REAL(KIND=JPRB), POINTER, DIMENSION(:, :) :: ZZVRLDI
REAL(KIND=JPRB), POINTER, DIMENSION(:, :, :) :: ZZSTRDU
REAL(KIND=JPRB), POINTER, DIMENSION(:, :, :) :: ZZSTRDV
REAL(KIND=JPRB), POINTER, DIMENSION(:, :, :) :: ZZRAPTRAJ


!-----------------------------------------------------------------------

LOGICAL :: LLTEST
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

!-----------------------------------------------------------------------
INTEGER(KIND=JPIM) :: JLON, JLEV, JBLK, ITOP
INTEGER(KIND=JPIM) :: IGPBLKS
INTEGER(KIND=JPIM) :: ILUNCI, ILUNFI, ILUNFO, IOUT
INTEGER(KIND=JPIM) :: NPROMA, NGPBLKS,KLEV,KLON,KGPBLKS
INTEGER(KIND=JPIM) :: KIDIA,KFDIA,KTDIA
CHARACTER (LEN=128) :: CLOUT
CHARACTER (LEN=128) :: CLCASE_IN
CHARACTER (LEN=128) :: CLCASE_OUT
TYPE (DD12), POINTER :: YLD
LOGICAL :: LLVERBOSE, LLDIFF
INTEGER(KIND=JPIM), POINTER :: IBLOCKLIST (:)
TYPE(FXTRAN_ACDC_STACK) :: YLSTACK
TYPE(FXTRAN_ACDC_STACK) :: YLOFFSET
INTEGER(KIND=JPIM) :: ISIZE4, ISIZE8
CHARACTER*64 :: CLMETHOD
INTEGER(KIND=JPIM) :: ITIME, NTIME
LOGICAL :: LLSAVE, LLEXIST

LOGICAL :: LLACC
REAL(KIND=JPRB) :: TSC, TEC, TSD, TED, ZTC, ZTD

#ifdef ARCH
CHARACTER (LEN=*), PARAMETER :: CLARCH = ARCH
#else
CHARACTER (LEN=*), PARAMETER :: CLARCH = 'unkwown'
#endif


IF (LHOOK) CALL DR_HOOK('MAIN_ACDRAG',0,ZHOOK_HANDLE)
ASSOCIATE(HOBST=>YDML_PHY_MF%YRPHY0%HOBST, GWDBC=>YDML_PHY_MF%YRPHY0%GWDBC, GWDCD=>YDML_PHY_MF%YRPHY0%GWDCD, &
 & GWDLT=>YDML_PHY_MF%YRPHY0%GWDLT, GWDVALI=>YDML_PHY_MF%YRPHY0%GWDVALI, GWDPROF=>YDML_PHY_MF%YRPHY0%GWDPROF, &
 & GWDAMP=>YDML_PHY_MF%YRPHY0%GWDAMP, GWDSE=>YDML_PHY_MF%YRPHY0%GWDSE, &
 & TSPHY=>YDML_PHY_MF%YRPHY2%TSPHY, &
 & RG=>YDCST%RG, RPI=>YDCST%RPI, &
 & LNEWD=>YDML_PHY_MF%YRPHY%LNEWD, LGLT=>YDML_PHY_MF%YRPHY%LGLT)

YLD => NULL()

CALL INITOPTIONS

NPROMA  = 0; CALL GETOPTION("--nproma", NPROMA)
NGPBLKS = 0; CALL GETOPTION("--ngpblks", NGPBLKS)
CALL GETOPTION ("--case-in", CLCASE_IN, MND=.TRUE.)
CLCASE_OUT = ''; CALL GETOPTION ("--case-out", CLCASE_OUT)

CALL GETOPTION ("--verbose", LLVERBOSE)
CALL GETOPTION ("--diff", LLDIFF)
#ifdef PARKIND1_SINGLE
ISIZE4 = 80;
ISIZE8 = 10;
#else
ISIZE4 = 10;
ISIZE8 = 80;
#endif
CALL GETOPTION ("--stack-size-4", ISIZE4)
CALL GETOPTION ("--stack-size-8", ISIZE8)
NTIME = 1; CALL GETOPTION ("--times", NTIME)

CLMETHOD = 'openmp'; CALL GETOPTION ("--method", CLMETHOD)

IBLOCKLIST => NULL ()
CALL GETOPTION ("--block-list", IBLOCKLIST)

LLSAVE = CLCASE_OUT /= ''

IF (LLSAVE) THEN
  CALL XRD_MKDIR (TRIM (CLCASE_OUT))
ENDIF

CLOUT = '-'; CALL GETOPTION ("--out", CLOUT)

CALL CHECKOPTIONS

CALL LOADALL

IF (LLVERBOSE) THEN
WRITE (0, *) " NPROMA = ", NPROMA, " NGPBLKS = ", NGPBLKS, " KLEV = ", KLEV
WRITE (0, *) " ISIZE4 = ", ISIZE4, " ISIZE8 = ", ISIZE8, " NTIME = ", NTIME
ENDIF

IF (LLSAVE) THEN
  CALL SAVEIALL
ENDIF


CALL GET_TIME (TSD)

!$ACC DATA COPY( ZZAPRS, ZZAPRSF, ZZDELP, ZZNBVNO, ZZRDELP, ZZU, ZZV,  &
!$ACC      & ZZRCORI, ZZGETRL, ZZGWDCS, ZZVRLAN, ZZVRLDI, ZZSTRDU, ZZSTRDV, ZZRAPTRAJ) &
!$ACC& IF (TRIM (CLMETHOD) == 'openaccsinglecolumn' .OR. TRIM (CLMETHOD) == 'manyblocks' .OR. TRIM(CLMETHOD)=='openaccsc_bitrepro')


IF (TRIM (CLMETHOD) == 'openaccsinglecolumn' .OR. TRIM (CLMETHOD) == 'manyblocks' &
    &.OR. TRIM(CLMETHOD) == 'openaccsc_bitrepro' .OR. TRIM(CLMETHOD) == 'openmpsc_bitrepro') THEN
  CALL ACDC_COPY(YDCST)
  CALL ACDC_COPY(YDML_PHY_MF)   
  CALL YFXTRAN_ACDC_STACK%INIT(NPROMA,KLEV,NGPBLKS,ISIZE4,ISIZE8)
ENDIF

CALL GET_TIME (TSC)

DO ITIME = 1, NTIME

  IF (TRIM (CLMETHOD) == 'openmp') THEN

!$OMP PARALLEL DO PRIVATE (JBLK)
    DO JBLK = 1, NGPBLKS
      CALL ACDRAG(YDCST, YDML_PHY_MF,KIDIA,KFDIA,KLON,KTDIA,KLEV,&
      & ZZAPRS(:, :, JBLK), ZZAPRSF(:, :, JBLK),  &
      & ZZDELP(:, :, JBLK), ZZNBVNO(:, :, JBLK),  &
      & ZZRDELP(:, :, JBLK), ZZU(:, :, JBLK), ZZV(:, :, JBLK),  &
      & ZZRCORI(:, JBLK), ZZGETRL(:, JBLK), ZZGWDCS(:, JBLK),  &
      & ZZVRLAN(:, JBLK), ZZVRLDI(:, JBLK), ZZSTRDU(:, :, JBLK),  &
      & ZZSTRDV(:, :, JBLK), ZZRAPTRAJ(:, :, JBLK))
    ENDDO !jblk
!$OMP END PARALLEL DO

  ELSEIF (TRIM (CLMETHOD) == 'openaccsinglecolumn') THEN
    
    !$ACC PARALLEL LOOP GANG PRIVATE(JBLK) PRESENT(YFXTRAN_ACDC_STACK) VECTOR_LENGTH(NPROMA)
    DO JBLK=1,NGPBLKS
      !$ACC LOOP VECTOR PRIVATE(JLON,YLSTACK)
      DO JLON=1,NPROMA
        YLSTACK%L8=fxtran_acdc_stack_l8(YFXTRAN_ACDC_STACK,JBLK,NGPBLKS)
        YLSTACK%U8=fxtran_acdc_stack_u8(YFXTRAN_ACDC_STACK,JBLK,NGPBLKS)
        YLSTACK%L4=fxtran_acdc_stack_l4(YFXTRAN_ACDC_STACK,JBLK,NGPBLKS)
        YLSTACK%U4=fxtran_acdc_stack_u4(YFXTRAN_ACDC_STACK,JBLK,NGPBLKS)

        CALL ACDRAG_OPENACC(YDCST, YDML_PHY_MF,JLON,JLON,KLON,KTDIA,KLEV,&
        & ZZAPRS(:, :, JBLK), ZZAPRSF(:, :, JBLK),  &
        & ZZDELP(:, :, JBLK), ZZNBVNO(:, :, JBLK),  &
        & ZZRDELP(:, :, JBLK), ZZU(:, :, JBLK), ZZV(:, :, JBLK),  &
        & ZZRCORI(:, JBLK), ZZGETRL(:, JBLK), ZZGWDCS(:, JBLK),  &
        & ZZVRLAN(:, JBLK), ZZVRLDI(:, JBLK), ZZSTRDU(:, :, JBLK),  &
        & ZZSTRDV(:, :, JBLK), ZZRAPTRAJ(:, :, JBLK),YDSTACK=YLSTACK)

       ENDDO
     ENDDO

  ELSEIF (TRIM (CLMETHOD) == 'openmpsc_bitrepro') THEN
    
    !$OMP PARALLEL DO PRIVATE(JBLK,JLON,YLSTACK)
    DO JBLK=1,NGPBLKS
      DO JLON=1,NPROMA
        YLSTACK%L8=fxtran_acdc_stack_l8(YFXTRAN_ACDC_STACK,JBLK,NGPBLKS)
        YLSTACK%U8=fxtran_acdc_stack_u8(YFXTRAN_ACDC_STACK,JBLK,NGPBLKS)
        YLSTACK%L4=fxtran_acdc_stack_l4(YFXTRAN_ACDC_STACK,JBLK,NGPBLKS)
        YLSTACK%U4=fxtran_acdc_stack_u4(YFXTRAN_ACDC_STACK,JBLK,NGPBLKS)

        CALL ACDRAG_OPENACC_BITREPRO(YDCST, YDML_PHY_MF,JLON,JLON,KLON,KTDIA,KLEV,&
        & ZZAPRS(:, :, JBLK), ZZAPRSF(:, :, JBLK),  &
        & ZZDELP(:, :, JBLK), ZZNBVNO(:, :, JBLK),  &
        & ZZRDELP(:, :, JBLK), ZZU(:, :, JBLK), ZZV(:, :, JBLK),  &
        & ZZRCORI(:, JBLK), ZZGETRL(:, JBLK), ZZGWDCS(:, JBLK),  &
        & ZZVRLAN(:, JBLK), ZZVRLDI(:, JBLK), ZZSTRDU(:, :, JBLK),  &
        & ZZSTRDV(:, :, JBLK), ZZRAPTRAJ(:, :, JBLK),YDSTACK=YLSTACK)

       ENDDO
     ENDDO


  ELSEIF (TRIM (CLMETHOD) == 'openaccsc_bitrepro') THEN
    
    !$ACC PARALLEL LOOP GANG PRIVATE(JBLK) PRESENT(YFXTRAN_ACDC_STACK) VECTOR_LENGTH(NPROMA)
    DO JBLK=1,NGPBLKS
      !$ACC LOOP VECTOR PRIVATE(JLON,YLSTACK)
      DO JLON=1,NPROMA
        YLSTACK%L8=fxtran_acdc_stack_l8(YFXTRAN_ACDC_STACK,JBLK,NGPBLKS)
        YLSTACK%U8=fxtran_acdc_stack_u8(YFXTRAN_ACDC_STACK,JBLK,NGPBLKS)
        YLSTACK%L4=fxtran_acdc_stack_l4(YFXTRAN_ACDC_STACK,JBLK,NGPBLKS)
        YLSTACK%U4=fxtran_acdc_stack_u4(YFXTRAN_ACDC_STACK,JBLK,NGPBLKS)

        CALL ACDRAG_OPENACC_BITREPRO(YDCST, YDML_PHY_MF,JLON,JLON,KLON,KTDIA,KLEV,&
        & ZZAPRS(:, :, JBLK), ZZAPRSF(:, :, JBLK),  &
        & ZZDELP(:, :, JBLK), ZZNBVNO(:, :, JBLK),  &
        & ZZRDELP(:, :, JBLK), ZZU(:, :, JBLK), ZZV(:, :, JBLK),  &
        & ZZRCORI(:, JBLK), ZZGETRL(:, JBLK), ZZGWDCS(:, JBLK),  &
        & ZZVRLAN(:, JBLK), ZZVRLDI(:, JBLK), ZZSTRDU(:, :, JBLK),  &
        & ZZSTRDV(:, :, JBLK), ZZRAPTRAJ(:, :, JBLK),YDSTACK=YLSTACK)

       ENDDO
     ENDDO


  ELSEIF (TRIM (CLMETHOD) == 'manyblocks') THEN

      LLACC=.TRUE.
      YLOFFSET=FXTRAN_ACDC_STACK(0,0,0,0)
      CALL ACDRAG_MANYBLOCKS(YDCST, YDML_PHY_MF,KIDIA,KFDIA,KLON,KTDIA,KLEV,&
      & ZZAPRS, ZZAPRSF,  &
      & ZZDELP, ZZNBVNO,  &
      & ZZRDELP, ZZU, ZZV,  &
      & ZZRCORI, ZZGETRL, ZZGWDCS,  &
      & ZZVRLAN, ZZVRLDI, ZZSTRDU,  &
      & ZZSTRDV, ZZRAPTRAJ,LDACC=LLACC,KGPBLKS=NGPBLKS,YDOFFSET=YLOFFSET)


  ENDIF !method omp/acc
ENDDO !time

CALL GET_TIME (TEC)

IF (TRIM (CLMETHOD) == 'openaccsinglecolumn' .OR. TRIM (CLMETHOD) == 'manyblocks' .OR. TRIM(CLMETHOD)=='openaccsc_bitrepro') THEN
  CALL ACDC_WIPE(YDCST)
  CALL ACDC_WIPE(YDML_PHY_MF)    
ENDIF

!$ACC END DATA
CALL GET_TIME (TED)
ZTC = TEC - TSC
ZTD = TED - TSD

LLEXIST = .FALSE.

IF (CLOUT == '-') THEN
  IOUT = STDOUT
ELSE
  IOUT = 77
  INQUIRE (FILE=TRIM (CLOUT), EXIST=LLEXIST)
  IF (LLEXIST) THEN
    OPEN (IOUT, FILE=TRIM (CLOUT), FORM='FORMATTED', STATUS='OLD', POSITION='APPEND')
  ELSE
    OPEN (IOUT, FILE=TRIM (CLOUT), FORM='FORMATTED', STATUS='NEW')
  ENDIF
ENDIF

IF (.NOT. LLEXIST) &
WRITE (IOUT, '(A16,";",A32,";",A8,";",A8,";",A8,4(";",A20))') &
              & "CLARCH", "CLMETHOD", "NPROMA", "NGPBLKS", "NTIME", &
              & "ZTCTOT", "ZTC", "ZTDTOT", "ZTD"

WRITE (IOUT, '(A16,";",A32,";",I8,";",I8,";",I8,4(";",E20.10))') &
              & CLARCH,  TRIM (CLMETHOD), NPROMA, NGPBLKS, NTIME, &
              & ZTC, ZTC / REAL(NPROMA*NGPBLKS*NTIME, 8), &
              & ZTD, ZTD / REAL(NPROMA*NGPBLKS*NTIME, 8)

IF (IOUT /= STDOUT) THEN
  CLOSE (IOUT)
ENDIF


IF (LLDIFF) THEN
  CALL DIFFALL
ENDIF

IF (LLSAVE) THEN
  CALL SAVEOALL
ENDIF
WRITE (0, *) __FILE__, ':', __LINE__
IF (LHOOK) CALL DR_HOOK ('MAIN_ACDRAG', 1, ZHOOK_HANDLE)
END ASSOCIATE

CONTAINS

SUBROUTINE LOADALL

ILUNCI = 77
ILUNFI = 78

OPEN (ILUNCI, NAME=TRIM (CLCASE_IN)//'/ACDRAG.CONST.dat', FORM='UNFORMATTED')
OPEN (ILUNFI, NAME=TRIM (CLCASE_IN)//'/ACDRAG.IN.dat',    FORM='UNFORMATTED')

!load derived types and scalars


CALL ACDC_LOAD(YDCST, ILUNCI)
CALL ACDC_LOAD(YDML_PHY_MF, ILUNCI)
CALL LOAD(ILUNCI, KLON)
CALL LOAD(ILUNCI, KLEV)
CALL LOAD(ILUNCI, KIDIA)
CALL LOAD(ILUNCI, KFDIA)
CALL LOAD(ILUNCI, KTDIA)
CALL LOAD(ILUNCI, IGPBLKS)

WRITE (0, *) "KLON = ", KLON 
KGPBLKS=IGPBLKS
IF (NPROMA == 0) NPROMA = KLON
IF (NGPBLKS == 0) THEN
  IF (ASSOCIATED (IBLOCKLIST)) THEN
    NGPBLKS = SIZE (IBLOCKLIST)
  ELSE
    NGPBLKS = KGPBLKS
  ENDIF
ENDIF

IF ((NPROMA /= KLON) .OR. (NGPBLKS /= KGPBLKS) .OR. ASSOCIATED (IBLOCKLIST)) THEN

  ALLOCATE (YLD)

  IF (ASSOCIATED (IBLOCKLIST)) THEN
    CALL YLD%INIT ([KLON, KGPBLKS], [NPROMA, NGPBLKS], IBLOCKLIST)
  ELSE
    CALL YLD%INIT ([KLON, KGPBLKS], [NPROMA, NGPBLKS])
  ENDIF

  NPROMA = YLD%IPROMA2
  NGPBLKS = YLD%IGPBLKS2

ENDIF

KLON=NPROMA
KGPBLKS=NGPBLKS
KFDIA=KLON

!load arrays
CALL LOAD(ILUNFI, ZZAPRS, YDD=YLD)
CALL LOAD(ILUNFI, ZZAPRSF, YDD=YLD)
CALL LOAD(ILUNFI, ZZDELP, YDD=YLD)
CALL LOAD(ILUNFI, ZZNBVNO, YDD=YLD)
CALL LOAD(ILUNFI, ZZRDELP, YDD=YLD)
CALL LOAD(ILUNFI, ZZU, YDD=YLD)
CALL LOAD(ILUNFI, ZZV, YDD=YLD)
CALL LOAD(ILUNFI, ZZRCORI, YDD=YLD)
CALL LOAD(ILUNFI, ZZGETRL, YDD=YLD)
CALL LOAD(ILUNFI, ZZGWDCS, YDD=YLD)
CALL LOAD(ILUNFI, ZZVRLAN, YDD=YLD)
CALL LOAD(ILUNFI, ZZVRLDI, YDD=YLD)
CALL LOAD(ILUNFI, ZZSTRDU, YDD=YLD)
CALL LOAD(ILUNFI, ZZSTRDV, YDD=YLD)
CALL LOAD(ILUNFI, ZZRAPTRAJ, YDD=YLD)

CLOSE (ILUNFI)
CLOSE (ILUNCI)
OPEN (ILUNFI, NAME=TRIM (CLCASE_IN)//'/ACDRAG.IN.dat',FORM='UNFORMATTED')
END SUBROUTINE

SUBROUTINE DIFFALL
IF (LLVERBOSE) PRINT *, " DIFF..."
OPEN (ILUNFO, NAME=TRIM (CLCASE_IN)//'/ACDRAG.OUT.dat', FORM='UNFORMATTED')

CALL DIFF('ZZSTRDU', ZZSTRDU, KLUN=ILUNFO, YDD=YLD)
CALL DIFF('ZZSTRDV', ZZSTRDV, KLUN=ILUNFO, YDD=YLD)
CALL DIFF('ZZRAPTRAJ', ZZRAPTRAJ, KLUN=ILUNFO, YDD=YLD)
CLOSE(ILUNFO)

IF (LLVERBOSE) PRINT *, " ...DIFF"

END SUBROUTINE


SUBROUTINE SAVEIALL

ILUNCI = 77
ILUNFI = 78

OPEN (ILUNCI, NAME=TRIM (CLCASE_OUT)//'/ACDRAG.CONST.dat', FORM='UNFORMATTED')
OPEN (ILUNFI, NAME=TRIM (CLCASE_OUT)//'/ACDRAG.IN.dat',    FORM='UNFORMATTED')

CALL ACDC_SAVE(YDCST, ILUNCI)
CALL ACDC_SAVE(YDML_PHY_MF, ILUNCI)
CALL SAVE(KLON, ILUNCI)
CALL SAVE(KLEV, ILUNCI)
CALL SAVE(KIDIA, ILUNCI)
CALL SAVE(KFDIA, ILUNCI)
CALL SAVE(KTDIA, ILUNCI)
CALL SAVE(NGPBLKS,ILUNCI)

CALL SAVE(ZZAPRS, ILUNFI, KLBOUND=LBOUND(ZZAPRS))
CALL SAVE(ZZAPRSF, ILUNFI, KLBOUND=LBOUND(ZZAPRSF))
CALL SAVE(ZZDELP, ILUNFI, KLBOUND=LBOUND(ZZDELP))
CALL SAVE(ZZNBVNO, ILUNFI, KLBOUND=LBOUND(ZZNBVNO))
CALL SAVE(ZZRDELP, ILUNFI, KLBOUND=LBOUND(ZZRDELP))
CALL SAVE(ZZU, ILUNFI, KLBOUND=LBOUND(ZZU))
CALL SAVE(ZZV, ILUNFI, KLBOUND=LBOUND(ZZV))
CALL SAVE(ZZRCORI, ILUNFI, KLBOUND=LBOUND(ZZRCORI))
CALL SAVE(ZZGETRL, ILUNFI, KLBOUND=LBOUND(ZZGETRL))
CALL SAVE(ZZGWDCS, ILUNFI, KLBOUND=LBOUND(ZZGWDCS))
CALL SAVE(ZZVRLAN, ILUNFI, KLBOUND=LBOUND(ZZVRLAN))
CALL SAVE(ZZVRLDI, ILUNFI, KLBOUND=LBOUND(ZZVRLDI))
CALL SAVE(ZZSTRDU, ILUNFI, KLBOUND=LBOUND(ZZSTRDU))
CALL SAVE(ZZSTRDV, ILUNFI, KLBOUND=LBOUND(ZZSTRDV))
CALL SAVE(ZZRAPTRAJ, ILUNFI, KLBOUND=LBOUND(ZZRAPTRAJ))

CLOSE (ILUNFI)
CLOSE (ILUNCI)

END SUBROUTINE


SUBROUTINE SAVEOALL

ILUNFO = 79
OPEN (ILUNFO, NAME=TRIM (CLCASE_OUT)//'/ACDRAG.OUT.dat', FORM='UNFORMATTED')

CALL SAVE(ZZSTRDU, ILUNFO, KLBOUND=LBOUND(ZZSTRDU))
CALL SAVE(ZZSTRDV, ILUNFO, KLBOUND=LBOUND(ZZSTRDV))
CALL SAVE(ZZRAPTRAJ, ILUNFO, KLBOUND=LBOUND(ZZRAPTRAJ))
CLOSE (ILUNFO)
 
END SUBROUTINE

END PROGRAM MAIN_ACDRAG
