MODULE UTIL_TADVPRS_MOD

USE YOMPHY0, ONLY : TADVPRS

INTERFACE ACDC_SAVE
MODULE PROCEDURE ACDC_SAVE_TADVPRS
END INTERFACE

INTERFACE ACDC_LOAD
MODULE PROCEDURE ACDC_LOAD_TADVPRS
END INTERFACE

INTERFACE ACDC_COPY
MODULE PROCEDURE ACDC_COPY_TADVPRS
END INTERFACE




INTERFACE ACDC_WIPE
MODULE PROCEDURE ACDC_WIPE_TADVPRS
END INTERFACE


CONTAINS

SUBROUTINE ACDC_SAVE_TADVPRS (SELF, KLUN)

IMPLICIT NONE
TYPE (TADVPRS), INTENT (IN), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN

WRITE (KLUN) SELF%LLMELTS
WRITE (KLUN) SELF%LLFREEZ
WRITE (KLUN) SELF%LLEVAPX
WRITE (KLUN) SELF%ZEPS
WRITE (KLUN) SELF%ZNU1
WRITE (KLUN) SELF%ZNU2
WRITE (KLUN) SELF%ZTAU1
WRITE (KLUN) SELF%ZTAU2
WRITE (KLUN) SELF%ZSIGMA1
WRITE (KLUN) SELF%ZSIGMA2
WRITE (KLUN) SELF%ZFVENTR1
WRITE (KLUN) SELF%ZFVENTR2
WRITE (KLUN) SELF%ZFVENTS1
WRITE (KLUN) SELF%ZFVENTS2
WRITE (KLUN) SELF%ZFVELR
WRITE (KLUN) SELF%ZFVELS
WRITE (KLUN) SELF%ZTMELT
WRITE (KLUN) SELF%ZRHOW
WRITE (KLUN) SELF%ZNRHOW
WRITE (KLUN) SELF%ZDVISC
WRITE (KLUN) SELF%ZSQTVIS
WRITE (KLUN) SELF%ZCDARV
WRITE (KLUN) SELF%ZRHOREF
WRITE (KLUN) SELF%ZEXP1
WRITE (KLUN) SELF%ZEXP4
WRITE (KLUN) SELF%ZEXP6
WRITE (KLUN) SELF%ZPREF
WRITE (KLUN) SELF%ZCOEFF1
WRITE (KLUN) SELF%ZCOEFF2
WRITE (KLUN) SELF%ZCOEFF2B
WRITE (KLUN) SELF%ZCOEFF3
WRITE (KLUN) SELF%ZCOEFF4
WRITE (KLUN) SELF%ZCOEFF5
WRITE (KLUN) SELF%ZCOEFF6
END SUBROUTINE

SUBROUTINE ACDC_LOAD_TADVPRS (SELF, KLUN)
USE PARKIND1, ONLY : JPRD
IMPLICIT NONE
TYPE (TADVPRS), INTENT (OUT), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
REAL(KIND=JPRD) :: ZTMP0
READ (KLUN) SELF%LLMELTS
READ (KLUN) SELF%LLFREEZ
READ (KLUN) SELF%LLEVAPX
READ (KLUN) ZTMP0
SELF%ZEPS = ZTMP0
READ (KLUN) ZTMP0
SELF%ZNU1 = ZTMP0
READ (KLUN) ZTMP0
SELF%ZNU2 = ZTMP0
READ (KLUN) ZTMP0
SELF%ZTAU1 = ZTMP0
READ (KLUN) ZTMP0
SELF%ZTAU2 = ZTMP0
READ (KLUN) ZTMP0
SELF%ZSIGMA1 = ZTMP0
READ (KLUN) ZTMP0
SELF%ZSIGMA2 = ZTMP0
READ (KLUN) ZTMP0
SELF%ZFVENTR1 = ZTMP0
READ (KLUN) ZTMP0
SELF%ZFVENTR2 = ZTMP0
READ (KLUN) ZTMP0
SELF%ZFVENTS1 = ZTMP0
READ (KLUN) ZTMP0
SELF%ZFVENTS2 = ZTMP0
READ (KLUN) ZTMP0
SELF%ZFVELR = ZTMP0
READ (KLUN) ZTMP0
SELF%ZFVELS = ZTMP0
READ (KLUN) ZTMP0
SELF%ZTMELT = ZTMP0
READ (KLUN) ZTMP0
SELF%ZRHOW = ZTMP0
READ (KLUN) ZTMP0
SELF%ZNRHOW = ZTMP0
READ (KLUN) ZTMP0
SELF%ZDVISC = ZTMP0
READ (KLUN) ZTMP0
SELF%ZSQTVIS = ZTMP0
READ (KLUN) ZTMP0
SELF%ZCDARV = ZTMP0
READ (KLUN) ZTMP0
SELF%ZRHOREF = ZTMP0
READ (KLUN) ZTMP0
SELF%ZEXP1 = ZTMP0
READ (KLUN) ZTMP0
SELF%ZEXP4 = ZTMP0
READ (KLUN) ZTMP0
SELF%ZEXP6 = ZTMP0
READ (KLUN) ZTMP0
SELF%ZPREF = ZTMP0
READ (KLUN) ZTMP0
SELF%ZCOEFF1 = ZTMP0
READ (KLUN) ZTMP0
SELF%ZCOEFF2 = ZTMP0
READ (KLUN) ZTMP0
SELF%ZCOEFF2B = ZTMP0
READ (KLUN) ZTMP0
SELF%ZCOEFF3 = ZTMP0
READ (KLUN) ZTMP0
SELF%ZCOEFF4 = ZTMP0
READ (KLUN) ZTMP0
SELF%ZCOEFF5 = ZTMP0
READ (KLUN) ZTMP0
SELF%ZCOEFF6 = ZTMP0
END SUBROUTINE

SUBROUTINE ACDC_COPY_TADVPRS (SELF, LDCREATED, LDFIELDAPI)

IMPLICIT NONE
TYPE (TADVPRS), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
LOGICAL :: LLCREATED
LOGICAL :: LLFIELDAPI
LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$ACC ENTER DATA CREATE (SELF)
  !$ACC UPDATE DEVICE (SELF)
ENDIF

END SUBROUTINE







SUBROUTINE ACDC_WIPE_TADVPRS (SELF, LDDELETED, LDFIELDAPI)

IMPLICIT NONE
TYPE (TADVPRS), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
LOGICAL :: LLDELETED
LOGICAL :: LLFIELDAPI
LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$ACC EXIT DATA DELETE (SELF)
ENDIF
END SUBROUTINE



END MODULE
