MODULE MODEL_PHYSICS_MF_MOD
  USE YOMPHY   , ONLY : TPHY
  USE YOMPHY0  , ONLY : TPHY0
  USE YOMPHY2  , ONLY : TPHY2
  IMPLICIT NONE

  TYPE MODEL_PHYSICS_MF_TYPE

  TYPE(TPHY)    :: YRPHY !! (french) physics
  TYPE(TPHY0)   :: YRPHY0 !! atmospheric parameters
  TYPE(TPHY2)   :: YRPHY2 !! expt parameters

    CONTAINS

    PROCEDURE, PASS :: PRINT => PRINT_CONFIGURATION

  END TYPE MODEL_PHYSICS_MF_TYPE

  !---------------------------------------------------------------------

  CONTAINS

  SUBROUTINE PRINT_CONFIGURATION(SELF, KDEPTH, KOUTNO)
  USE PARKIND1  ,ONLY : JPIM
  IMPLICIT NONE
  CLASS(MODEL_PHYSICS_MF_TYPE), INTENT(IN) :: SELF
  INTEGER(KIND=JPIM)          , INTENT(IN) :: KDEPTH
  INTEGER(KIND=JPIM)          , INTENT(IN) :: KOUTNO

  WRITE(KOUTNO,*) REPEAT(' ',KDEPTH) // 'model%yrml_phy_mf : not yet printa    ble'

  END SUBROUTINE PRINT_CONFIGURATION

END MODULE MODEL_PHYSICS_MF_MOD
