MODULE UTIL_TPHY2_MOD

USE YOMPHY2, ONLY : TPHY2

INTERFACE ACDC_SAVE
MODULE PROCEDURE ACDC_SAVE_TPHY2
END INTERFACE

INTERFACE ACDC_LOAD
MODULE PROCEDURE ACDC_LOAD_TPHY2
END INTERFACE

INTERFACE ACDC_COPY
MODULE PROCEDURE ACDC_COPY_TPHY2
END INTERFACE




INTERFACE ACDC_WIPE
MODULE PROCEDURE ACDC_WIPE_TPHY2
END INTERFACE


CONTAINS

SUBROUTINE ACDC_SAVE_TPHY2 (SELF, KLUN)

IMPLICIT NONE
TYPE (TPHY2), INTENT (IN), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN

WRITE (KLUN) SELF%NTSHM
WRITE (KLUN) SELF%NTSML
WRITE (KLUN) SELF%TSPHY
WRITE (KLUN) SELF%XMUCVPP
WRITE (KLUN) SELF%XMULAF
WRITE (KLUN) SELF%XDAMP
WRITE (KLUN) SELF%HCLP
WRITE (KLUN) SELF%HTCLS
WRITE (KLUN) SELF%HVCLS
WRITE (KLUN) SELF%HTSHM
WRITE (KLUN) SELF%HTSML
WRITE (KLUN) SELF%HWMOHIGH
WRITE (KLUN) SELF%HWMOLOW
WRITE (KLUN) SELF%GZ0RAF
WRITE (KLUN) SELF%FACRAF
WRITE (KLUN) SELF%FACRAFCV
WRITE (KLUN) SELF%FACRAFDCAPE
WRITE (KLUN) SELF%GCAPERAF
WRITE (KLUN) SELF%HTKERAF
WRITE (KLUN) SELF%LRAFTUR
WRITE (KLUN) SELF%LMULAF
WRITE (KLUN) SELF%LWMOCLOUD
WRITE (KLUN) SELF%LRAFTKE
END SUBROUTINE

SUBROUTINE ACDC_LOAD_TPHY2 (SELF, KLUN)
USE PARKIND1, ONLY : JPRD
IMPLICIT NONE
TYPE (TPHY2), INTENT (OUT), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
REAL(KIND=JPRD) :: ZTMP0
READ (KLUN) SELF%NTSHM
READ (KLUN) SELF%NTSML
READ (KLUN) ZTMP0
SELF%TSPHY = ZTMP0
READ (KLUN) ZTMP0
SELF%XMUCVPP = ZTMP0
READ (KLUN) ZTMP0
SELF%XMULAF = ZTMP0
READ (KLUN) ZTMP0
SELF%XDAMP = ZTMP0
READ (KLUN) ZTMP0
SELF%HCLP = ZTMP0
READ (KLUN) ZTMP0
SELF%HTCLS = ZTMP0
READ (KLUN) ZTMP0
SELF%HVCLS = ZTMP0
READ (KLUN) ZTMP0
SELF%HTSHM = ZTMP0
READ (KLUN) ZTMP0
SELF%HTSML = ZTMP0
READ (KLUN) ZTMP0
SELF%HWMOHIGH = ZTMP0
READ (KLUN) ZTMP0
SELF%HWMOLOW = ZTMP0
READ (KLUN) ZTMP0
SELF%GZ0RAF = ZTMP0
READ (KLUN) ZTMP0
SELF%FACRAF = ZTMP0
READ (KLUN) ZTMP0
SELF%FACRAFCV = ZTMP0
READ (KLUN) ZTMP0
SELF%FACRAFDCAPE = ZTMP0
READ (KLUN) ZTMP0
SELF%GCAPERAF = ZTMP0
READ (KLUN) ZTMP0
SELF%HTKERAF = ZTMP0
READ (KLUN) SELF%LRAFTUR
READ (KLUN) SELF%LMULAF
READ (KLUN) SELF%LWMOCLOUD
READ (KLUN) SELF%LRAFTKE
END SUBROUTINE

SUBROUTINE ACDC_COPY_TPHY2 (SELF, LDCREATED, LDFIELDAPI)

IMPLICIT NONE
TYPE (TPHY2), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
LOGICAL :: LLCREATED
LOGICAL :: LLFIELDAPI
LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$ACC ENTER DATA CREATE (SELF)
  !$ACC UPDATE DEVICE (SELF)
ENDIF

END SUBROUTINE







SUBROUTINE ACDC_WIPE_TPHY2 (SELF, LDDELETED, LDFIELDAPI)

IMPLICIT NONE
TYPE (TPHY2), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
LOGICAL :: LLDELETED
LOGICAL :: LLFIELDAPI
LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$ACC EXIT DATA DELETE (SELF)
ENDIF
END SUBROUTINE



END MODULE
