MODULE UTIL_MODEL_PHYSICS_MF_TYPE_MOD

USE MODEL_PHYSICS_MF_MOD, ONLY : MODEL_PHYSICS_MF_TYPE

INTERFACE ACDC_SAVE
MODULE PROCEDURE ACDC_SAVE_MODEL_PHYSICS_MF_TYPE
END INTERFACE

INTERFACE ACDC_LOAD
MODULE PROCEDURE ACDC_LOAD_MODEL_PHYSICS_MF_TYPE
END INTERFACE

INTERFACE ACDC_COPY
MODULE PROCEDURE ACDC_COPY_MODEL_PHYSICS_MF_TYPE
END INTERFACE




INTERFACE ACDC_WIPE
MODULE PROCEDURE ACDC_WIPE_MODEL_PHYSICS_MF_TYPE
END INTERFACE


CONTAINS

SUBROUTINE ACDC_SAVE_MODEL_PHYSICS_MF_TYPE (SELF, KLUN)
USE UTIL_TPHY0_MOD
USE UTIL_TPHY2_MOD
USE UTIL_TPHY_MOD
IMPLICIT NONE
TYPE (MODEL_PHYSICS_MF_TYPE), INTENT (IN), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN

CALL ACDC_SAVE_TPHY (SELF%YRPHY, KLUN)
CALL ACDC_SAVE_TPHY0 (SELF%YRPHY0, KLUN)
CALL ACDC_SAVE_TPHY2 (SELF%YRPHY2, KLUN)
END SUBROUTINE

SUBROUTINE ACDC_LOAD_MODEL_PHYSICS_MF_TYPE (SELF, KLUN)
USE UTIL_TPHY0_MOD
USE UTIL_TPHY2_MOD
USE UTIL_TPHY_MOD
IMPLICIT NONE
TYPE (MODEL_PHYSICS_MF_TYPE), INTENT (OUT), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN

CALL ACDC_LOAD_TPHY (SELF%YRPHY, KLUN)
CALL ACDC_LOAD_TPHY0 (SELF%YRPHY0, KLUN)
CALL ACDC_LOAD_TPHY2 (SELF%YRPHY2, KLUN)
END SUBROUTINE

SUBROUTINE ACDC_COPY_MODEL_PHYSICS_MF_TYPE (SELF, LDCREATED, LDFIELDAPI)
USE UTIL_TPHY0_MOD
USE UTIL_TPHY2_MOD
USE UTIL_TPHY_MOD
IMPLICIT NONE
TYPE (MODEL_PHYSICS_MF_TYPE), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
LOGICAL :: LLCREATED
LOGICAL :: LLFIELDAPI
LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$ACC ENTER DATA CREATE (SELF)
  !$ACC UPDATE DEVICE (SELF)
ENDIF
CALL ACDC_COPY_TPHY (SELF%YRPHY, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL ACDC_COPY_TPHY0 (SELF%YRPHY0, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL ACDC_COPY_TPHY2 (SELF%YRPHY2, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

END SUBROUTINE







SUBROUTINE ACDC_WIPE_MODEL_PHYSICS_MF_TYPE (SELF, LDDELETED, LDFIELDAPI)
USE UTIL_TPHY0_MOD
USE UTIL_TPHY2_MOD
USE UTIL_TPHY_MOD
IMPLICIT NONE
TYPE (MODEL_PHYSICS_MF_TYPE), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
LOGICAL :: LLDELETED
LOGICAL :: LLFIELDAPI
LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
CALL ACDC_WIPE_TPHY (SELF%YRPHY, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL ACDC_WIPE_TPHY0 (SELF%YRPHY0, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL ACDC_WIPE_TPHY2 (SELF%YRPHY2, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$ACC EXIT DATA DELETE (SELF)
ENDIF
END SUBROUTINE



END MODULE
