
SUBROUTINE ACDRAG_BITREPRO (YDCST, YDML_PHY_MF, KIDIA, KFDIA, KLON, KTDIA, KLEV, PAPRS, PAPRSF, PDELP&
&, PNBVNO, PRDELP, PU, PV, PRCORI, PGETRL, PGWDCS, PVRLAN, PVRLDI, PSTRDU, PSTRDV, PRAPTRAJ)
USE MODEL_PHYSICS_MF_MOD,ONLY:MODEL_PHYSICS_MF_TYPE
USE PARKIND1,ONLY:JPIM, JPRB, JPRD
USE YOMHOOK,ONLY:LHOOK, DR_HOOK, JPHOOK
USE YOMCST,ONLY:TCST
USE FXTRAN_ACDC_BR_INTRINSICS, ONLY : FXTRAN_ACDC_BR_COS, FXTRAN_ACDC_BR_LOG&
&, FXTRAN_ACDC_BR_POW, FXTRAN_ACDC_BR_SIN

IMPLICIT NONE

TYPE (TCST), INTENT (IN)::YDCST
TYPE (MODEL_PHYSICS_MF_TYPE), INTENT (IN)::YDML_PHY_MF
INTEGER (KIND=JPIM), INTENT (IN)::KLON
INTEGER (KIND=JPIM), INTENT (IN)::KLEV
INTEGER (KIND=JPIM), INTENT (IN)::KIDIA
INTEGER (KIND=JPIM), INTENT (IN)::KFDIA
INTEGER (KIND=JPIM), INTENT (IN)::KTDIA
REAL (KIND=JPRB), INTENT (IN)::PAPRS (KLON, 0:KLEV)
REAL (KIND=JPRB), INTENT (IN)::PAPRSF (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PDELP (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PNBVNO (KLON, 0:KLEV)
REAL (KIND=JPRB), INTENT (IN)::PRDELP (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PU (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PV (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PRCORI (KLON)
REAL (KIND=JPRB), INTENT (IN)::PGETRL (KLON)
REAL (KIND=JPRB), INTENT (IN)::PGWDCS (KLON)
REAL (KIND=JPRB), INTENT (IN)::PVRLAN (KLON)
REAL (KIND=JPRB), INTENT (IN)::PVRLDI (KLON)
REAL (KIND=JPRB), INTENT (OUT)::PSTRDU (KLON, 0:KLEV)
REAL (KIND=JPRB), INTENT (OUT)::PSTRDV (KLON, 0:KLEV)
REAL (KIND=JPRB), INTENT (OUT)::PRAPTRAJ (KLON, 0:KLEV)
REAL (KIND=JPRB)::ZZCV (KLON)
REAL (KIND=JPRB)::ZZCU (KLON)
REAL (KIND=JPRB)::ZZCR (KLON)
REAL (KIND=JPRB)::ZZBB (KLON)
REAL (KIND=JPRB)::ZZAA (KLON)
REAL (KIND=JPRB)::ZWGHTK (KLON)
REAL (KIND=JPRB)::ZVSUR (KLON)
REAL (KIND=JPRB)::ZUSUR (KLON)
REAL (KIND=JPRB)::ZUSR (KLON)
REAL (KIND=JPRB)::ZTST2 (KLON)
REAL (KIND=JPRB)::ZTST1 (KLON)
REAL (KIND=JPRB)::ZSUSR (KLON)
REAL (KIND=JPRB)::ZSUMV (KLON)
REAL (KIND=JPRB)::ZSUMU (KLON)
REAL (KIND=JPRB)::ZSUMF (KLON)
REAL (KIND=JPRB)::ZSUMD (KLON)
REAL (KIND=JPRB)::ZSUM (KLON)
REAL (KIND=JPRB)::ZSTVS (KLON)
REAL (KIND=JPRB)::ZSTUS (KLON)
REAL (KIND=JPRB)::ZSTS (KLON)
REAL (KIND=JPRB)::ZSTM (KLON)
REAL (KIND=JPRB)::ZREF (KLON)
REAL (KIND=JPRB)::ZPR2 (KLON)
REAL (KIND=JPRB)::ZPR1 (KLON)
REAL (KIND=JPRB)::ZOBST (KLON)
REAL (KIND=JPRB)::ZFACS (KLON)
REAL (KIND=JPRB)::ZDS2 (KLON)
REAL (KIND=JPRB)::ZDS1 (KLON)
REAL (KIND=JPRB)::ZWGHT (KLON, 0:KLEV)
REAL (KIND=JPRB)::ZV (KLON, KLEV)
REAL (KIND=JPRB)::ZU (KLON, KLEV)
REAL (KIND=JPRB)::ZRAPP (KLON, 0:KLEV)
REAL (KIND=JPRB)::ZPOID (KLON, KLEV)
REAL (KIND=JPRB)::ZNFNO (KLON, 0:KLEV)
REAL (KIND=JPRB)::ZIPOI (KLON, KLEV)
INTEGER (KIND=JPIM)::JLON
INTEGER (KIND=JPIM)::JLEV
REAL (KIND=JPRB)::ZRZR
REAL (KIND=JPRB)::ZZPR
REAL (KIND=JPRB)::ZX
REAL (KIND=JPRB)::ZVSTAR
REAL (KIND=JPRB)::ZUSTAR
REAL (KIND=JPRB)::ZTUNE
REAL (KIND=JPRB)::ZTEMPF (KLON)
REAL (KIND=JPRB)::ZRZ
REAL (KIND=JPRB)::ZPRRAP
REAL (KIND=JPRB)::ZPBLF
REAL (KIND=JPRB)::ZPBL
REAL (KIND=JPRB)::ZLIFTG
REAL (KIND=JPRB)::ZLIFT
REAL (KIND=JPRB)::ZGDTI
REAL (KIND=JPRB)::ZGDT
REAL (KIND=JPRB)::ZFORCL
REAL (KIND=JPRB)::ZFORCB
REAL (KIND=JPRB)::ZFORCA
REAL (KIND=JPRB)::ZEPS6
REAL (KIND=JPRB)::ZEPS5
REAL (KIND=JPRB)::ZEPS4
REAL (KIND=JPRB)::ZEPS3
REAL (KIND=JPRB)::ZEPS2
REAL (KIND=JPRB)::ZEPS1
REAL (KIND=JPRB)::ZDX
REAL (KIND=JPRB)::ZDV
REAL (KIND=JPRB)::ZDU
REAL (KIND=JPRB)::ZDIFSV
REAL (KIND=JPRB)::ZDIFSU
REAL (KIND=JPRB)::ZDIFSR
REAL (KIND=JPRB)::ZDEL2
REAL (KIND=JPRB)::ZDEL1
REAL (KIND=JPRB)::ZD
REAL (KIND=JPRB)::ZBETA
REAL (KIND=JPRB)::ZAUSR
REAL (KIND=JPRB)::ZARGLI
REAL (KIND=JPRB)::ZALTI
REAL (KIND=JPRB)::ZALPHA
REAL (KIND=JPRB)::ZALP2
REAL (KIND=JPRB)::ZALP1
REAL (KIND=JPRB)::ZA
REAL (KIND=JPRB)::ZCOS (KLON)
LOGICAL::LLTEST
REAL (KIND=JPHOOK)::ZHOOK_HANDLE
IF (LHOOK) CALL DR_HOOK ('ACDRAG_BITREPRO', 0, ZHOOK_HANDLE)

PRAPTRAJ (:,:)=0.0
ZGDT=YDCST%RG*YDML_PHY_MF%YRPHY2%TSPHY
ZGDTI=1.0_JPRB/ZGDT

IF (YDML_PHY_MF%YRPHY0%GWDPROF==0.0_JPRB) THEN
  ZZPR=0.5_JPRB
ELSE
  ZZPR=((1.0_JPRB+YDML_PHY_MF%YRPHY0%GWDPROF)*FXTRAN_ACDC_BR_LOG (1.0_JPRB+YDML_PHY_MF%YRPHY0&
  &%GWDPROF)-YDML_PHY_MF%YRPHY0%GWDPROF)/FXTRAN_ACDC_BR_POW(YDML_PHY_MF%YRPHY0%GWDPROF, 2)
ENDIF

ZLIFT=YDML_PHY_MF%YRPHY0%GWDLT*YDML_PHY_MF%YRPHY2%TSPHY/(YDML_PHY_MF%YRPHY0%HOBST*ZZPR)
ZLIFTG=YDML_PHY_MF%YRPHY0%GWDLT/(YDML_PHY_MF%YRPHY0%HOBST*ZZPR)

IF (.NOT.YDML_PHY_MF%YRPHY%LGLT) THEN
  ZLIFTG=0.0_JPRB
ENDIF

ZALP1=0.75_JPRB+0.25_JPRB*FXTRAN_ACDC_BR_LOG (16._JPRB)
ZALP2=(3.5_JPRB*YDCST%RPI-FXTRAN_ACDC_BR_LOG (16._JPRB))-8._JPRB
ZDEL1=2.75_JPRB-0.75_JPRB*FXTRAN_ACDC_BR_LOG (16._JPRB)
ZDEL2=(-0.25_JPRB*YDCST%RPI-FXTRAN_ACDC_BR_LOG (16._JPRB))+4._JPRB
ZEPS1=1.E-06_JPRB
ZEPS2=1.E-04_JPRB
ZEPS3=1.E-09_JPRB
ZEPS4=1.E-05_JPRB
ZEPS5=1.E-02_JPRB

IF (JPRB==JPRD) THEN
  ZEPS6=1.E-12_JPRB
ELSE
  ZEPS6=1.E-6_JPRB
ENDIF

ZARGLI=1.E+06_JPRB
ZBETA=MIN (YDML_PHY_MF%YRPHY0%GWDVALI, 1.0_JPRB-ZEPS6)

DO JLEV=KTDIA, KLEV

  DO JLON=KIDIA, KFDIA
    ZPOID (JLON, JLEV)=PDELP (JLON, JLEV)*ZGDTI
    ZIPOI (JLON, JLEV)=PRDELP (JLON, JLEV)*ZGDT
    ZWGHT (JLON, JLEV)=0.0_JPRB
  ENDDO

ENDDO


DO JLON=KIDIA, KFDIA
  ZOBST (JLON)=MIN (PAPRS (JLON, KLEV)-PAPRSF (JLON, KTDIA), MAX (PAPRS (JLON, KLEV&
  &)-PAPRSF (JLON, KLEV), YDML_PHY_MF%YRPHY0%HOBST*PGETRL (JLON)*PGWDCS (JLON)))
  ZWGHT (JLON, KLEV)=(PAPRS (JLON, KLEV)-PAPRSF (JLON, KLEV))/ZOBST (JLON)
  ZWGHT (JLON, KLEV)=ZWGHT (JLON, KLEV)*(1.0_JPRB-ZBETA)
  ZWGHTK (JLON)=ZWGHT (JLON, KLEV)
  ZSUMU (JLON)=ZWGHT (JLON, KLEV)*PU (JLON, KLEV)
  ZSUMV (JLON)=ZWGHT (JLON, KLEV)*PV (JLON, KLEV)
  ZSUMF (JLON)=ZWGHT (JLON, KLEV)*PNBVNO (JLON, KLEV)
ENDDO


DO JLEV=KLEV-1, KTDIA,-1

  IF (JLEV==KLEV-1) THEN
    LLTEST=.TRUE.
  ELSE
    LLTEST=SUM (ZWGHT (KIDIA:KFDIA, JLEV+1))>0.0_JPRB
  ENDIF


  IF (LLTEST) THEN

    DO JLON=KIDIA, KFDIA
      ZWGHT (JLON, JLEV)=MAX (0.0_JPRB,(PAPRSF (JLON, JLEV+1)-MAX (PAPRSF&
      & (JLON, JLEV), PAPRS (JLON, KLEV)-ZOBST (JLON)))/ZOBST (JLON))
      ZALTI=MIN (1.0_JPRB,(PAPRS (JLON, KLEV)-PAPRS (JLON, JLEV))/ZOBST (JLON))
      ZWGHT (JLON, JLEV)=ZWGHT (JLON, JLEV)*(1.0_JPRB-ZBETA*((1.0_JPRB&
      &-ZALTI)/(1.0_JPRB+YDML_PHY_MF%YRPHY0%GWDPROF*ZALTI)))
      ZWGHTK (JLON)=ZWGHTK (JLON)+ZWGHT (JLON, JLEV)
      ZSUMU (JLON)=ZSUMU (JLON)+0.5_JPRB*ZWGHT (JLON, JLEV)*(PU (JLON, JLEV)+PU (JLON, JLEV+1))
      ZSUMV (JLON)=ZSUMV (JLON)+0.5_JPRB*ZWGHT (JLON, JLEV)*(PV (JLON, JLEV)+PV (JLON, JLEV+1))
      ZSUMF (JLON)=ZSUMF (JLON)+ZWGHT (JLON, JLEV)*PNBVNO (JLON, JLEV)
    ENDDO

  ENDIF

ENDDO


DO JLEV=KTDIA, KLEV

  DO JLON=KIDIA, KFDIA
    ZWGHT (JLON, JLEV)=ZWGHT (JLON, JLEV)*(1.0_JPRB/ZWGHTK (JLON))
  ENDDO

ENDDO


DO JLON=KIDIA, KFDIA
  ZSUMU (JLON)=ZSUMU (JLON)*(1.0_JPRB/ZWGHTK (JLON))
  ZSUMV (JLON)=ZSUMV (JLON)*(1.0_JPRB/ZWGHTK (JLON))
  ZSUMF (JLON)=ZSUMF (JLON)*(1.0_JPRB/ZWGHTK (JLON))
ENDDO


DO JLON=KIDIA, KFDIA
  ZNFNO (JLON, KLEV)=SQRT (MAX (0.0_JPRB, ZSUMF (JLON)))
  ZPBLF=1.0_JPRB-MIN (1.0_JPRB,(PAPRS (JLON, KLEV)-PAPRSF (JLON, KLEV))/ZOBST (JLON))
  ZU (JLON, KLEV)=PU (JLON, KLEV)+ZPBLF*(ZSUMU (JLON)-PU (JLON, KLEV))
  ZV (JLON, KLEV)=PV (JLON, KLEV)+ZPBLF*(ZSUMV (JLON)-PV (JLON, KLEV))
ENDDO


DO JLEV=KLEV-1, KTDIA,-1

  DO JLON=KIDIA, KFDIA
    ZPBL=1.0_JPRB-MIN (1.0_JPRB,(PAPRS (JLON, KLEV)-PAPRS (JLON, JLEV))/ZOBST (JLON))
    ZNFNO (JLON, JLEV)=SQRT (MAX (0.0_JPRB, PNBVNO (JLON&
    &, JLEV)+ZPBL*(ZSUMF (JLON)-PNBVNO (JLON, JLEV))))
    ZPBLF=1.0_JPRB-MIN (1.0_JPRB,(PAPRS (JLON, KLEV)-PAPRSF (JLON, JLEV))/ZOBST (JLON))
    ZU (JLON, JLEV)=PU (JLON, JLEV)+ZPBLF*(ZSUMU (JLON)-PU (JLON, JLEV))
    ZV (JLON, JLEV)=PV (JLON, JLEV)+ZPBLF*(ZSUMV (JLON)-PV (JLON, JLEV))
  ENDDO

ENDDO


DO JLON=KIDIA, KFDIA
  ZUSTAR=ZSUMU (JLON)*FXTRAN_ACDC_BR_COS (2.0_JPRB*PVRLDI (JLON)&
  &)+ZSUMV (JLON)*FXTRAN_ACDC_BR_SIN (2.0_JPRB*PVRLDI (JLON))
  ZVSTAR=ZSUMU (JLON)*FXTRAN_ACDC_BR_SIN (2.0_JPRB*PVRLDI (JLON)&
  &)-ZSUMV (JLON)*FXTRAN_ACDC_BR_COS (2.0_JPRB*PVRLDI (JLON))
  ZA=FXTRAN_ACDC_BR_POW(PVRLAN (JLON), 2)+0.5_JPRB*(4._JPRB*(1.0_JPRB-PVRLAN (JLON&
  &))*(1.0_JPRB+ZALP1*PVRLAN (JLON))+PVRLAN (JLON)*FXTRAN_ACDC_BR_LOG (1.0_JPRB&
  &/MAX (ZEPS1, PVRLAN (JLON)))*(1.0_JPRB+ZALP2*PVRLAN (JLON)))/YDCST%RPI
  ZD=0.5_JPRB*(4._JPRB*(1.0_JPRB-PVRLAN (JLON))*(1.0_JPRB+ZDEL1*PVRLAN (JLON))-3._JPRB*PVRLAN (JLON)*FXTRAN_ACDC_BR_LOG&
  & (1.0_JPRB/MAX (ZEPS1, PVRLAN (JLON)))*(1.0_JPRB+ZDEL2*PVRLAN (JLON)))/YDCST%RPI
  ZUSUR (JLON)=ZA*ZSUMU (JLON)+ZD*ZUSTAR
  ZVSUR (JLON)=ZA*ZSUMV (JLON)+ZD*ZVSTAR
  ZSUSR (JLON)=MAX (ZEPS2, ZSUMU (JLON)*ZUSUR (JLON)+ZSUMV (JLON)*ZVSUR (JLON))
  ZUSR (JLON)=SQRT (FXTRAN_ACDC_BR_POW(ZUSUR (JLON), 2)+FXTRAN_ACDC_BR_POW(ZVSUR (JLON), 2))
  ZFACS (JLON)=ZNFNO (JLON, KLEV)/FXTRAN_ACDC_BR_POW(ZSUSR (JLON), 3)
  ZRAPP (JLON, KLEV)=1.0_JPRB
  ZSTUS (JLON)=YDML_PHY_MF%YRPHY0%GWDSE*FXTRAN_ACDC_BR_POW(PGWDCS&
  & (JLON), 2)*ZNFNO (JLON, KLEV)*PGETRL (JLON)*ZUSUR (JLON)
  ZSTVS (JLON)=YDML_PHY_MF%YRPHY0%GWDSE*FXTRAN_ACDC_BR_POW(PGWDCS&
  & (JLON), 2)*ZNFNO (JLON, KLEV)*PGETRL (JLON)*ZVSUR (JLON)
  ZTST1 (JLON)=1.0_JPRB
  ZPR1 (JLON)=PAPRSF (JLON, KLEV)
  ZSUM (JLON)=(PAPRS (JLON, KLEV)-PAPRSF (JLON, KLEV))*ZNFNO (JLON, KLEV)*ZUSR (JLON)/ZSUSR (JLON)
  ZTST2 (JLON)=1.0_JPRB
  ZPR2 (JLON)=PAPRSF (JLON, KLEV)
  ZREF (JLON)=1.0_JPRB
  ZTUNE=YDML_PHY_MF%YRPHY0%GWDBC*FXTRAN_ACDC_BR_POW((ZUSR (JLON)**2/ZSUSR (JLON)), 2)
  ZTEMPF (JLON)=ZUSR (JLON)/MAX (ZEPS5, ZTUNE*YDML_PHY_MF%YRPHY0&
  &%HOBST*PGETRL (JLON)*PGWDCS (JLON)*ZNFNO (JLON, KLEV))
  ZZBB (JLON)=MAX (0.0_JPRB, 1.0_JPRB-MAX (ZTEMPF (JLON), ZEPS6))
  ZZAA (JLON)=YDML_PHY_MF%YRPHY0%GWDCD*ZZBB (JLON)*ZTUNE*(1.0_JPRB-ZZBB (JLON))

  IF (YDML_PHY_MF%YRPHY%LNEWD) THEN
    ZSTUS (JLON)=ZSTUS (JLON)*(1.0_JPRB-ZZBB (JLON))/MAX (1.0_JPRB, ZTEMPF (JLON))
    ZSTVS (JLON)=ZSTVS (JLON)*(1.0_JPRB-ZZBB (JLON))/MAX (1.0_JPRB, ZTEMPF (JLON))
    ZZAA (JLON)=YDML_PHY_MF%YRPHY0%GWDCD*ZZBB (JLON)
  ENDIF

ENDDO


DO JLEV=0, KLEV

  DO JLON=KIDIA, KFDIA
    PRAPTRAJ (JLON, JLEV)=YDML_PHY_MF%YRPHY0%GWDSE*FXTRAN_ACDC_BR_POW&
    &(PGWDCS (JLON), 2)*ZNFNO (JLON, KLEV)*PGETRL (JLON)
  ENDDO


  IF (YDML_PHY_MF%YRPHY%LNEWD) THEN

    DO JLON=KIDIA, KFDIA
      PRAPTRAJ (JLON, JLEV)=PRAPTRAJ (JLON, JLEV)*(1.0_JPRB-ZZBB (JLON))/MAX (1.0_JPRB, ZTEMPF (JLON))
    ENDDO

  ENDIF

ENDDO


DO JLEV=KLEV-1, KTDIA,-1

  DO JLON=KIDIA, KFDIA
    ZAUSR=0.5_JPRB*((ZU (JLON, JLEV)+ZU (JLON, JLEV+1))*ZUSUR (JLON&
    &)+(ZV (JLON, JLEV)+ZV (JLON, JLEV+1))*ZVSUR (JLON))
    ZPRRAP=ZFACS (JLON)*FXTRAN_ACDC_BR_POW(ZAUSR, 3)/MAX (ZEPS3, ZNFNO (JLON, JLEV))
    ZRAPP (JLON, JLEV)=MAX (0.0_JPRB, MIN (ZRAPP (JLON, JLEV+1), ZPRRAP))
    ZTST1 (JLON)=ZTST1 (JLON)*MAX (0.0_JPRB, SIGN (1.0_JPRB, ZPRRAP-1.0_JPRB))
    ZPR1 (JLON)=ZPR1 (JLON)+ZTST1 (JLON)*(PAPRSF (JLON, JLEV)-ZPR1 (JLON))
    ZSUM (JLON)=ZSUM (JLON)+ZTST1 (JLON)*(PAPRSF (JLON, JLEV+1)-PAPRSF &
    &(JLON, JLEV))*ZNFNO (JLON, JLEV)*ZUSR (JLON)/MAX (ZEPS2, ZAUSR)
    ZTST2 (JLON)=ZTST2 (JLON)*(1.0_JPRB-MAX (0.0_JPRB, SIGN (1.0_JPRB, 0.0_JPRB-ZNFNO (JLON, JLEV))))
    ZPR2 (JLON)=ZPR2 (JLON)+ZTST2 (JLON)*(PAPRSF (JLON, JLEV)-ZPR2 (JLON))
    ZREF (JLON)=ZREF (JLON)+ZTST2 (JLON)*(ZRAPP (JLON, JLEV)-ZREF (JLON))
  ENDDO

ENDDO


DO JLON=KIDIA, KFDIA
  PSTRDU (JLON, KTDIA-1)=0.0_JPRB
  PSTRDV (JLON, KTDIA-1)=0.0_JPRB
  ZRAPP (JLON, KTDIA-1)=0.0_JPRB
  PRAPTRAJ (JLON, KTDIA-1)=0.0_JPRB
  ZSTM (JLON)=1.0_JPRB/SQRT (1.0_JPRB+MAX (0.0_JPRB, SIGN (1.0_JPRB, (ZPR1&
  & (JLON)-ZPR2 (JLON))-ZEPS4))*YDML_PHY_MF%YRPHY0%GWDAMP*(2.0_JPRB*FXTRAN_ACDC_BR_SIN&
  & (MIN (ZARGLI, ZSUM (JLON)))+YDML_PHY_MF%YRPHY0%GWDAMP))

  IF (YDML_PHY_MF%YRPHY%LNEWD) THEN
    ZSTM (JLON)=ZSTM (JLON)/(1.0_JPRB-ZZBB (JLON))
    ZREF (JLON)=ZREF (JLON)/(1.0_JPRB-ZZBB (JLON))
  ENDIF

  ZDS1 (JLON)=MAX (0.0_JPRB, ZSTM (JLON)-1.0_JPRB)/(PAPRS (JLON, KLEV)-ZPR1 (JLON))
  ZSTS (JLON)=MIN (ZREF (JLON)*(1.0_JPRB-ZTST2 (JLON)), ZSTM (JLON))
  ZDS2 (JLON)=ZSTS (JLON)/(PAPRS (JLON, KLEV)-ZPR2 (JLON))
ENDDO


DO JLON=KIDIA, KFDIA
  ZZCR (JLON)=ZRAPP (JLON, KLEV)*ZSTM (JLON)
ENDDO


DO JLEV=KTDIA, KLEV

  DO JLON=KIDIA, KFDIA
    ZRAPP (JLON, JLEV)=ZDS2 (JLON)*MAX (0.0_JPRB, PAPRS (JLON, JLEV)-ZPR2&
    & (JLON))+MAX (0.0_JPRB, MIN (ZSTM (JLON), ZRAPP (JLON, JLEV)+ZDS1 (JLON&
    &)*MAX (0.0_JPRB, PAPRS (JLON, JLEV)-ZPR1 (JLON)))-ZSTS (JLON))
    ZRZ=(PAPRS (JLON, KLEV)-PAPRS (JLON, JLEV))/MAX (ZEPS4, ZZBB (JLON&
    &)*YDML_PHY_MF%YRPHY0%HOBST*PGETRL (JLON)*PGWDCS (JLON))

    IF (.NOT.YDML_PHY_MF%YRPHY%LNEWD) THEN
      ZZCR (JLON)=ZRAPP (JLON, JLEV)
      ZRZR=1.0_JPRB
      ZRZ=MIN (1.0_JPRB, ZRZ)
    ELSE
      ZRZR=SQRT (ZZBB (JLON)/(1.0_JPRB+FXTRAN_ACDC_BR_POW(ZRZ, 2)*ZZBB (JLON)*(1.0_JPRB-ZZBB (JLON))))
    ENDIF

    ZRAPP (JLON, JLEV)=ZRAPP (JLON, JLEV)+ZZCR (JLON)*(ZZAA (JLON)*SQRT (MAX (0.0_JPRB,FXTRAN_ACDC_BR_POW&
    &((1.0_JPRB-ZRZ*ZRZR), 3)/(1.0_JPRB+ZRZ*YDML_PHY_MF%YRPHY0%GWDPROF*ZZBB (JLON)))))
  ENDDO

ENDDO


DO JLON=KIDIA, KFDIA
  ZZCR (JLON)=ZRAPP (JLON, KTDIA-1)
ENDDO


DO JLEV=KTDIA, KLEV

  DO JLON=KIDIA, KFDIA
    ZDIFSR=ZRAPP (JLON, JLEV)-ZZCR (JLON)
    ZZCR (JLON)=ZRAPP (JLON, JLEV)
    ZALTI=MIN (1.0_JPRB,(PAPRS (JLON, KLEV)-PAPRSF (JLON, JLEV))/ZOBST (JLON))
    ZRAPP (JLON, JLEV)=ZRAPP (JLON, JLEV-1)+ZDIFSR*(1.0_JPRB+ZLIFTG*(1.0_JPRB&
    &-ZALTI)/(1.0_JPRB+ZALTI*YDML_PHY_MF%YRPHY0%GWDPROF))*(1.0_JPRB-ZBETA*&
    &((1.0_JPRB-ZALTI)/(1.0_JPRB+YDML_PHY_MF%YRPHY0%GWDPROF*ZALTI)))
    PSTRDU (JLON, JLEV)=ZRAPP (JLON, JLEV)*ZSTUS (JLON)
    PSTRDV (JLON, JLEV)=ZRAPP (JLON, JLEV)*ZSTVS (JLON)
    PRAPTRAJ (JLON, JLEV)=PRAPTRAJ (JLON, JLEV)*ZRAPP (JLON, JLEV)
  ENDDO

ENDDO


DO JLON=KIDIA, KFDIA
  ZSUMD (JLON)=0.5_JPRB*ZWGHT (JLON, KTDIA)*ZIPOI (JLON,&
  & KTDIA)*(ZRAPP (JLON, KTDIA)-ZRAPP (JLON, KTDIA-1))
ENDDO


DO JLEV=KTDIA+1, KLEV

  DO JLON=KIDIA, KFDIA
    ZSUMD (JLON)=ZSUMD (JLON)+0.5_JPRB*(ZWGHT (JLON, JLEV)+ZWGHT (JLON, JLEV&
    &-1))*ZIPOI (JLON, JLEV)*(ZRAPP (JLON, JLEV)-ZRAPP (JLON, JLEV-1))
  ENDDO

ENDDO


DO JLON=KIDIA, KFDIA
  ZSUMD (JLON)=ZSUMD (JLON)+0.5_JPRB*ZWGHT (JLON, KLEV)*ZIPOI&
  & (JLON, KLEV)*(ZRAPP (JLON, KLEV)-ZRAPP (JLON, KLEV-1))
ENDDO


DO JLON=KIDIA, KFDIA
  ZSUMD (JLON)=ZSUMD (JLON)*SQRT (FXTRAN_ACDC_BR_POW(ZSTUS&
  & (JLON), 2)+FXTRAN_ACDC_BR_POW(ZSTVS (JLON), 2))
  ZRAPP (JLON, KLEV)=1.0_JPRB/(1.0_JPRB+ZSUMD (JLON)*ZUSR (JLON)/ZSUSR (JLON))
ENDDO


DO JLEV=KTDIA, KLEV

  DO JLON=KIDIA, KFDIA
    PSTRDU (JLON, JLEV)=PSTRDU (JLON, JLEV)*ZRAPP (JLON, KLEV)
    PSTRDV (JLON, JLEV)=PSTRDV (JLON, JLEV)*ZRAPP (JLON, KLEV)
    PRAPTRAJ (JLON, JLEV)=PRAPTRAJ (JLON, JLEV)*ZRAPP (JLON, KLEV)
  ENDDO

ENDDO


DO JLEV=KTDIA, KLEV

  DO JLON=KIDIA, KFDIA
    ZDU=ZIPOI (JLON, JLEV)*(PSTRDU (JLON, JLEV-1)-PSTRDU (JLON, JLEV))
    ZDV=ZIPOI (JLON, JLEV)*(PSTRDV (JLON, JLEV-1)-PSTRDV (JLON, JLEV))
    ZDX=ZIPOI (JLON, JLEV)*(ZUSUR (JLON)*PSTRDU (JLON, JLEV)+ZVSUR (JLON)*PSTRDV (JLON, JLEV))
    ZX=ZUSUR (JLON)*PU (JLON, JLEV)+ZVSUR (JLON)*PV (JLON, JLEV)
    ZALPHA=1.0_JPRB/(1.0_JPRB+ZDX/MAX (ZEPS2, ZX))
    PSTRDU (JLON, JLEV)=PSTRDU (JLON, JLEV-1)-ZPOID (JLON, JLEV)*ZALPHA*ZDU
    PSTRDV (JLON, JLEV)=PSTRDV (JLON, JLEV-1)-ZPOID (JLON, JLEV)*ZALPHA*ZDV
  ENDDO

ENDDO


DO JLON=KIDIA, KFDIA
  ZZCU (JLON)=PSTRDU (JLON, KTDIA-1)
  ZZCV (JLON)=PSTRDV (JLON, KTDIA-1)
ENDDO


DO JLEV=KTDIA, KLEV

  DO JLON=KIDIA, KFDIA
    ZDIFSU=PSTRDU (JLON, JLEV)-ZZCU (JLON)
    ZDIFSV=PSTRDV (JLON, JLEV)-ZZCV (JLON)
    ZZCU (JLON)=PSTRDU (JLON, JLEV)
    ZZCV (JLON)=PSTRDV (JLON, JLEV)
    ZALTI=MIN (1.0_JPRB,(PAPRS (JLON, KLEV)-PAPRSF (JLON, JLEV))/ZOBST (JLON))
    ZFORCL=ZLIFT*PRCORI (JLON)*(1.0_JPRB-ZALTI)/(1.0_JPRB+ZALTI*YDML_PHY_MF%YRPHY0%GWDPROF)
    ZFORCA=ZFORCL/(1.0_JPRB+0.25_JPRB*FXTRAN_ACDC_BR_POW(ZFORCL, 2))
    ZFORCB=0.5_JPRB*ZFORCL*ZFORCA
    PSTRDU (JLON, JLEV)=(PSTRDU (JLON, JLEV-1)+ZDIFSU)+ZPOID (JLON&
    &, JLEV)*(ZFORCB*PU (JLON, JLEV)-ZFORCA*PV (JLON, JLEV))
    PSTRDV (JLON, JLEV)=(PSTRDV (JLON, JLEV-1)+ZDIFSV)+ZPOID (JLON&
    &, JLEV)*(ZFORCB*PV (JLON, JLEV)+ZFORCA*PU (JLON, JLEV))
  ENDDO

ENDDO


IF (LHOOK) CALL DR_HOOK ('ACDRAG_BITREPRO', 1, ZHOOK_HANDLE)
END SUBROUTINE ACDRAG_BITREPRO
