MODULE UTIL_TPHY0_MOD

USE YOMPHY0, ONLY : TPHY0

INTERFACE ACDC_SAVE
MODULE PROCEDURE ACDC_SAVE_TPHY0
END INTERFACE

INTERFACE ACDC_LOAD
MODULE PROCEDURE ACDC_LOAD_TPHY0
END INTERFACE

INTERFACE ACDC_COPY
MODULE PROCEDURE ACDC_COPY_TPHY0
END INTERFACE




INTERFACE ACDC_WIPE
MODULE PROCEDURE ACDC_WIPE_TPHY0
END INTERFACE


CONTAINS

SUBROUTINE ACDC_SAVE_TPHY0 (SELF, KLUN)
USE UTIL_TADVPRS_MOD
IMPLICIT NONE
TYPE (TPHY0), INTENT (IN), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
LOGICAL :: LRHUC, LRN1D, LRQSMOD, LRRC1D, LRSRC1D, LRSURF
WRITE (KLUN) SELF%TYM
WRITE (KLUN) SELF%NPCLO1
WRITE (KLUN) SELF%NPCLO2
WRITE (KLUN) SELF%A0ML_AU
WRITE (KLUN) SELF%A0ML_AT
WRITE (KLUN) SELF%A0ML_BU
WRITE (KLUN) SELF%A0ML_BT
WRITE (KLUN) SELF%AERCS1
WRITE (KLUN) SELF%AERCS3
WRITE (KLUN) SELF%AERCS5
WRITE (KLUN) SELF%ADJTAU
WRITE (KLUN) SELF%ALMAV
WRITE (KLUN) SELF%BEDIFV
WRITE (KLUN) SELF%ECMNP
WRITE (KLUN) SELF%EDB
WRITE (KLUN) SELF%EDC
WRITE (KLUN) SELF%EDD
WRITE (KLUN) SELF%EVAP
WRITE (KLUN) SELF%FONT
WRITE (KLUN) SELF%GALP
WRITE (KLUN) SELF%GCISMIN
WRITE (KLUN) SELF%GEVAVF
WRITE (KLUN) SELF%GCCSV
WRITE (KLUN) SELF%GCVADS
WRITE (KLUN) SELF%GCVBETA
WRITE (KLUN) SELF%GCVIMPT
WRITE (KLUN) SELF%GCVOMGE
WRITE (KLUN) SELF%GCVOMGQ
WRITE (KLUN) SELF%GCVOMGS
WRITE (KLUN) SELF%GCVTURB
WRITE (KLUN) SELF%GCVOMDPS
WRITE (KLUN) SELF%GCVOMGSX
WRITE (KLUN) SELF%GCVRHMIN
WRITE (KLUN) SELF%GCVRHMAX
WRITE (KLUN) SELF%GCVOMCA
WRITE (KLUN) SELF%GCVOMCC
WRITE (KLUN) SELF%GDDEVA
WRITE (KLUN) SELF%GDDSDE
WRITE (KLUN) SELF%GDDFREVS
WRITE (KLUN) SELF%GDDINHOM
WRITE (KLUN) SELF%GRCVPP
WRITE (KLUN) SELF%GWDAMP
WRITE (KLUN) SELF%GWDBC
WRITE (KLUN) SELF%GWDCCO
WRITE (KLUN) SELF%GWDCD
WRITE (KLUN) SELF%GWDLT
WRITE (KLUN) SELF%GWDSE
WRITE (KLUN) SELF%GWDPROF
WRITE (KLUN) SELF%GWDVALI
WRITE (KLUN) SELF%HOBST
WRITE (KLUN) SELF%HUCOE
WRITE (KLUN) SELF%HUTIL
WRITE (KLUN) SELF%HUTIL1
WRITE (KLUN) SELF%HUTIL2
WRITE (KLUN) SELF%QSMIN
WRITE (KLUN) SELF%QSMODC
WRITE (KLUN) SELF%QSNEBC
WRITE (KLUN) SELF%QSNEBS
WRITE (KLUN) SELF%QSSUSC
WRITE (KLUN) SELF%QSSUSS
WRITE (KLUN) SELF%QSSUSV
WRITE (KLUN) SELF%QSUSXC
WRITE (KLUN) SELF%QSUSXS
WRITE (KLUN) SELF%RPHI0
WRITE (KLUN) SELF%RPHIR
WRITE (KLUN) SELF%QXRAL
WRITE (KLUN) SELF%QXRAL_ADJ
WRITE (KLUN) SELF%QXRDEL
WRITE (KLUN) SELF%QXRHX
WRITE (KLUN) SELF%QXRR
WRITE (KLUN) SELF%QXRTGH
WRITE (KLUN) SELF%QXRCDIL
WRITE (KLUN) SELF%RCIN
WRITE (KLUN) SELF%RCVEVAP
WRITE (KLUN) SELF%RDECRD
WRITE (KLUN) SELF%RDECRD1
WRITE (KLUN) SELF%RDECRD2
WRITE (KLUN) SELF%RDECRD3
WRITE (KLUN) SELF%RDECRD4
WRITE (KLUN) SELF%RDECRDRED
WRITE (KLUN) SELF%RDTFAC
WRITE (KLUN) SELF%REVAPN
WRITE (KLUN) SELF%REVGSL
WRITE (KLUN) SELF%RGELSFON
WRITE (KLUN) SELF%RFLCHCE
WRITE (KLUN) SELF%RTCAPE
WRITE (KLUN) SELF%SCO
WRITE (KLUN) SELF%SENSL
WRITE (KLUN) SELF%SNNBCO
WRITE (KLUN) SELF%SPNBCO
WRITE (KLUN) SELF%SXNBCO
WRITE (KLUN) SELF%TCA
WRITE (KLUN) SELF%TCT
WRITE (KLUN) SELF%TCW
WRITE (KLUN) SELF%TENTR
WRITE (KLUN) SELF%TENTRX
WRITE (KLUN) SELF%TUDGP
WRITE (KLUN) SELF%TDDGP
WRITE (KLUN) SELF%TURB
WRITE (KLUN) SELF%TVF
WRITE (KLUN) SELF%UHDIFV
WRITE (KLUN) SELF%USDMLT
WRITE (KLUN) SELF%USUPRC
WRITE (KLUN) SELF%USURIC
WRITE (KLUN) SELF%VCHRNK
WRITE (KLUN) SELF%VKARMN
WRITE (KLUN) SELF%VZ0CM
WRITE (KLUN) SELF%VZIUSTAR0
WRITE (KLUN) SELF%XNBMAX
WRITE (KLUN) SELF%AECLS3
WRITE (KLUN) SELF%AECLS4
WRITE (KLUN) SELF%ALD
WRITE (KLUN) SELF%AKN
WRITE (KLUN) SELF%ALPHAT
WRITE (KLUN) SELF%ALPHAE
WRITE (KLUN) SELF%EPS
WRITE (KLUN) SELF%ETACUT
WRITE (KLUN) SELF%ADISI
WRITE (KLUN) SELF%ADISE
WRITE (KLUN) SELF%ECTMIN
WRITE (KLUN) SELF%ECTMAX
WRITE (KLUN) SELF%AHCLPV
WRITE (KLUN) SELF%RICRLM
WRITE (KLUN) SELF%RMULACVG
WRITE (KLUN) SELF%XBLM
WRITE (KLUN) SELF%XMINLM
WRITE (KLUN) SELF%XMAXLM
WRITE (KLUN) SELF%XWSALM
WRITE (KLUN) SELF%XWSBLM
WRITE (KLUN) SELF%GCVALFA
WRITE (KLUN) SELF%GCVPSI
WRITE (KLUN) SELF%GCVPSIE
WRITE (KLUN) SELF%USURICE
WRITE (KLUN) SELF%USURICL
WRITE (KLUN) SELF%QSSC
WRITE (KLUN) SELF%USURID
WRITE (KLUN) SELF%GCVNU
WRITE (KLUN) SELF%USURIDE
WRITE (KLUN) SELF%GCVMLT
WRITE (KLUN) SELF%UTILGUST
WRITE (KLUN) SELF%RRGAMMA
WRITE (KLUN) SELF%RRSCALE
WRITE (KLUN) SELF%GPBLHK0
WRITE (KLUN) SELF%GPBLHRA
WRITE (KLUN) SELF%WMXOV
WRITE (KLUN) SELF%ACBRPHIM
WRITE (KLUN) SELF%ALMAVE
WRITE (KLUN) SELF%ALMAVX
WRITE (KLUN) SELF%ARSCH
WRITE (KLUN) SELF%ARSCQ
WRITE (KLUN) SELF%ARSC1
WRITE (KLUN) SELF%ARSB2
WRITE (KLUN) SELF%RICRET
WRITE (KLUN) SELF%STTBMIN
WRITE (KLUN) SELF%UCWSTAR
WRITE (KLUN) SELF%UDECT
WRITE (KLUN) SELF%UPRETMIN
WRITE (KLUN) SELF%UPRETMAX
WRITE (KLUN) SELF%USHEARM
WRITE (KLUN) SELF%RAUTEFR
WRITE (KLUN) SELF%RRAUTCS
WRITE (KLUN) SELF%RAUTEFS
WRITE (KLUN) SELF%RAUTSBET
WRITE (KLUN) SELF%RAUTEFG
WRITE (KLUN) SELF%REVASX
WRITE (KLUN) SELF%REVASXR
WRITE (KLUN) SELF%REVASXS
WRITE (KLUN) SELF%REVASXG
WRITE (KLUN) SELF%RNINTR
WRITE (KLUN) SELF%RNINTS
WRITE (KLUN) SELF%RNINTG
WRITE (KLUN) SELF%RQLCR
WRITE (KLUN) SELF%RSPCRR
WRITE (KLUN) SELF%RQICRMAX
WRITE (KLUN) SELF%RQICRMIN
WRITE (KLUN) SELF%RQLCV
WRITE (KLUN) SELF%RQICVMAX
WRITE (KLUN) SELF%RQICVMIN
WRITE (KLUN) SELF%RQICRT1
WRITE (KLUN) SELF%RQICRT2
WRITE (KLUN) SELF%RQICRSN
WRITE (KLUN) SELF%RQCRNS
WRITE (KLUN) SELF%RACCEF
WRITE (KLUN) SELF%RAGGEF
WRITE (KLUN) SELF%RRIMEF
WRITE (KLUN) SELF%RHCRIT1
WRITE (KLUN) SELF%RHCRIT2
WRITE (KLUN) SELF%RETAMIN
WRITE (KLUN) SELF%RFACNSM
WRITE (KLUN) SELF%TFVL
WRITE (KLUN) SELF%TFVLD
WRITE (KLUN) SELF%TFVI
WRITE (KLUN) SELF%TFVR
WRITE (KLUN) SELF%TFVS
WRITE (KLUN) SELF%GRHCMOD
WRITE (KLUN) SELF%RHCEXPDX
WRITE (KLUN) SELF%NUPTKE
WRITE (KLUN) SELF%TKEMULT
WRITE (KLUN) SELF%C_EPSILON
WRITE (KLUN) SELF%C3TKEFREE
WRITE (KLUN) SELF%ETKE_CTHETA
WRITE (KLUN) SELF%ETKE_RIFC_MAF
WRITE (KLUN) SELF%ETKE_RIFC
WRITE (KLUN) SELF%ETKE_R
WRITE (KLUN) SELF%ETKE_OLAM
WRITE (KLUN) SELF%ETKE_LAM0
WRITE (KLUN) SELF%ETKE_LAM1
WRITE (KLUN) SELF%ETKE_LAM2
WRITE (KLUN) SELF%ETKE_LAM3
WRITE (KLUN) SELF%ETKE_LAM4
WRITE (KLUN) SELF%ETKE_KA1
WRITE (KLUN) SELF%ETKE_KA2
WRITE (KLUN) SELF%ETKE_KA3
WRITE (KLUN) SELF%ENT_LAMBDA
WRITE (KLUN) SELF%ETKE_CG01
WRITE (KLUN) SELF%ETKE_CG02
WRITE (KLUN) SELF%ETKE_CG03
WRITE (KLUN) SELF%ETKE_BETA_EPS
WRITE (KLUN) SELF%ETKE_GAMMA_EPS
WRITE (KLUN) SELF%ETKE_GAMD
WRITE (KLUN) SELF%ETKE_TALPH
WRITE (KLUN) SELF%ETKE_ALPH0
WRITE (KLUN) SELF%ETKE_ENTRX
WRITE (KLUN) SELF%ETKE_ENTRN
WRITE (KLUN) SELF%ETKE_KLM
WRITE (KLUN) SELF%ETKE_TAULM
WRITE (KLUN) SELF%ETKE_C0SHEAR
WRITE (KLUN) SELF%ETKE_DTHETA_S1
WRITE (KLUN) SELF%ETKE_DTHETA_S2
WRITE (KLUN) SELF%ETKE_LBLT1
WRITE (KLUN) SELF%ETKE_LBLT2
WRITE (KLUN) SELF%ETKE_HUTLS
WRITE (KLUN) SELF%ETKE_LUTLS
WRITE (KLUN) SELF%ETKE_R1SIM
WRITE (KLUN) SELF%ETKE_R2SIM
WRITE (KLUN) SELF%ETKE_GB08A
WRITE (KLUN) SELF%ETKE_GB08B
WRITE (KLUN) SELF%ETKE_MIN
WRITE (KLUN) SELF%ETKE_CRIT
WRITE (KLUN) SELF%ETKE_DELTA
WRITE (KLUN) SELF%ETKE_RIFGR
WRITE (KLUN) SELF%EFB_AZ0
WRITE (KLUN) SELF%EFB_UR
WRITE (KLUN) SELF%REFB_1
WRITE (KLUN) SELF%REFB_2
WRITE (KLUN) SELF%REFB_3
WRITE (KLUN) SELF%RPBLH_UP
WRITE (KLUN) SELF%TUDBU
WRITE (KLUN) SELF%TDDBU
WRITE (KLUN) SELF%TUDFR
WRITE (KLUN) SELF%TDDFR
WRITE (KLUN) SELF%GCVALMX
WRITE (KLUN) SELF%GCVTAUDE
WRITE (KLUN) SELF%GCVACHI
WRITE (KLUN) SELF%GCVBEE
WRITE (KLUN) SELF%GCVEEX
WRITE (KLUN) SELF%ECMNPI
WRITE (KLUN) SELF%GRRMINA
WRITE (KLUN) SELF%GDDBETA
WRITE (KLUN) SELF%GDDDP
WRITE (KLUN) SELF%GDDFXM
WRITE (KLUN) SELF%GDDWPF
WRITE (KLUN) SELF%GDDEVF
WRITE (KLUN) SELF%TENTRD
WRITE (KLUN) SELF%GDDALBU
WRITE (KLUN) SELF%GDDFRAC
WRITE (KLUN) SELF%GDDENDYMX
WRITE (KLUN) SELF%GDDFP
WRITE (KLUN) SELF%GDDTAUSIG
WRITE (KLUN) SELF%GPEIPHI
WRITE (KLUN) SELF%GPETAU
WRITE (KLUN) SELF%GPEFDC
WRITE (KLUN) SELF%GENVSRH
WRITE (KLUN) SELF%GCVKSKV
WRITE (KLUN) SELF%GCVALBU
WRITE (KLUN) SELF%GCVENDY1
WRITE (KLUN) SELF%GCVENDY2
WRITE (KLUN) SELF%GCVENDYMX
WRITE (KLUN) SELF%GCVIDPBAS
WRITE (KLUN) SELF%GCVTAUSIG
WRITE (KLUN) SELF%GTRGDPMIX
WRITE (KLUN) SELF%GTRGDPHIMN
WRITE (KLUN) SELF%GTRGPUSLMN
WRITE (KLUN) SELF%GTRGKCK9
WRITE (KLUN) SELF%GTRGAIN
WRITE (KLUN) SELF%GTRTHRS
WRITE (KLUN) SELF%GTRTHCK
WRITE (KLUN) SELF%GTRBRC
WRITE (KLUN) SELF%GTRKGAIN
WRITE (KLUN) SELF%GTRKTHRS
WRITE (KLUN) SELF%GTRKTHCK
WRITE (KLUN) SELF%GCVCATAU
WRITE (KLUN) SELF%GCATHRCAP
WRITE (KLUN) SELF%GCATHRMOC
WRITE (KLUN) SELF%GCATHRCND
WRITE (KLUN) SELF%GCAOMCND
WRITE (KLUN) SELF%NWEIGHT
WRITE (KLUN) SELF%NCATAU
WRITE (KLUN) SELF%NCAPEMAX
WRITE (KLUN) SELF%NCVGMAX
WRITE (KLUN) SELF%RNEGAT
WRITE (KLUN) SELF%RNLCURV
WRITE (KLUN) SELF%EDK
WRITE (KLUN) SELF%XKLM
WRITE (KLUN) SELF%AGRE1
WRITE (KLUN) SELF%AGRERICR
WRITE (KLUN) SELF%AJBUMIN
WRITE (KLUN) SELF%RCOFLM
WRITE (KLUN) SELF%TENTRVL
WRITE (KLUN) SELF%TRENTRV
WRITE (KLUN) SELF%GCVGAMMA
WRITE (KLUN) SELF%LKESC
WRITE (KLUN) SELF%AGRE2
WRITE (KLUN) SELF%AGREF
WRITE (KLUN) SELF%ALFX
WRITE (KLUN) SELF%ALFX_LR
WRITE (KLUN) SELF%ALFX_HR
WRITE (KLUN) SELF%TCTC
WRITE (KLUN) SELF%TVFC
WRITE (KLUN) SELF%GAMAP1
WRITE (KLUN) SELF%RKDN
WRITE (KLUN) SELF%VVN
WRITE (KLUN) SELF%VVX
WRITE (KLUN) SELF%FENTRT
WRITE (KLUN) SELF%FQLIC
WRITE (KLUN) SELF%FNEBC
WRITE (KLUN) SELF%FEVAPC
WRITE (KLUN) SELF%RDPHIC
WRITE (KLUN) SELF%RWBF1
WRITE (KLUN) SELF%RWBF2
WRITE (KLUN) SELF%RCPCOEF1
WRITE (KLUN) SELF%RCPCOEF2
WRITE (KLUN) SELF%RCPCOEF3
WRITE (KLUN) SELF%SCLESPR
WRITE (KLUN) SELF%SCLESPS
WRITE (KLUN) SELF%HUCRED
WRITE (KLUN) SELF%HUCREDRA
WRITE (KLUN) SELF%FSPRAIN
WRITE (KLUN) SELF%EFFCOLL
WRITE (KLUN) SELF%RSMDNEBX
WRITE (KLUN) SELF%RSMDTX
WRITE (KLUN) SELF%NSMTPA
WRITE (KLUN) SELF%NSMTPB
WRITE (KLUN) SELF%RKFBTAU
WRITE (KLUN) SELF%RKFBNBX
WRITE (KLUN) SELF%GCVHMIN
WRITE (KLUN) SELF%GCVRESN
WRITE (KLUN) SELF%GCVRESX
WRITE (KLUN) SELF%GMIRH
WRITE (KLUN) SELF%RLMLH1
WRITE (KLUN) SELF%RPRTH
WRITE (KLUN) SELF%RSMOOTHMELT
WRITE (KLUN) SELF%LADVLIM
WRITE (KLUN) SELF%LGDDD
WRITE (KLUN) SELF%LCVRESDYN
WRITE (KLUN) SELF%LCVMICC
WRITE (KLUN) SELF%GMUKEDD
WRITE (KLUN) SELF%GNHDTAT
WRITE (KLUN) SELF%GNHDSMOS
WRITE (KLUN) SELF%GNHDSMOT
WRITE (KLUN) SELF%GNHDEV
WRITE (KLUN) SELF%LGVVEX
WRITE (KLUN) SELF%LCVUVM
WRITE (KLUN) SELF%NCVENTR
WRITE (KLUN) SELF%NCVSIG
WRITE (KLUN) SELF%NCVCLOS
WRITE (KLUN) SELF%NCVQLI
WRITE (KLUN) SELF%GCVENTRN
WRITE (KLUN) SELF%GCVENTRX
WRITE (KLUN) SELF%ADOE
WRITE (KLUN) SELF%RFRAC_ENTR_N
WRITE (KLUN) SELF%RFRAC_ENTR_X
WRITE (KLUN) SELF%GCVENTR_MIN
WRITE (KLUN) SELF%THPCMT
WRITE (KLUN) SELF%AJ1PEPS
WRITE (KLUN) SELF%AJ1MEPS
WRITE (KLUN) SELF%NAJITER
WRITE (KLUN) SELF%GAEPS
WRITE (KLUN) SELF%GCVEZ
WRITE (KLUN) SELF%GCVTRMIN
WRITE (KLUN) SELF%LCVFEVV
WRITE (KLUN) SELF%GCVFEVV
WRITE (KLUN) SELF%LCVCONTAU
WRITE (KLUN) SELF%GCVTEXC
WRITE (KLUN) SELF%GCVWEXC
WRITE (KLUN) SELF%LCVNAUV
WRITE (KLUN) SELF%GCVFRR
WRITE (KLUN) SELF%GCVPNH
WRITE (KLUN) SELF%GCVORGED
WRITE (KLUN) SELF%LCVIMPT
WRITE (KLUN) SELF%GCVTAUREM
WRITE (KLUN) SELF%GCLOEA
WRITE (KLUN) SELF%GCLOEB
WRITE (KLUN) SELF%GFRAE
WRITE (KLUN) SELF%GCVADET
WRITE (KLUN) SELF%GCVCINC
WRITE (KLUN) SELF%GSDMIN
WRITE (KLUN) SELF%GSDMAX
WRITE (KLUN) SELF%GALMIN
WRITE (KLUN) SELF%GALMAX
WRITE (KLUN) SELF%GSDAMIN
WRITE (KLUN) SELF%GSDAMAX
WRITE (KLUN) SELF%GEXPKD
WRITE (KLUN) SELF%LCVEOD
WRITE (KLUN) SELF%GREMIN
WRITE (KLUN) SELF%GREMAX
WRITE (KLUN) SELF%GCHI0
WRITE (KLUN) SELF%GFSURF
WRITE (KLUN) SELF%GSHELL
WRITE (KLUN) SELF%GFRIC
WRITE (KLUN) SELF%GUDDD
WRITE (KLUN) SELF%GSIGA
WRITE (KLUN) SELF%GNHDSMOW
WRITE (KLUN) SELF%GDEPTH
WRITE (KLUN) SELF%GALTAU
WRITE (KLUN) SELF%GKEDDRE
WRITE (KLUN) SELF%GNHACC
WRITE (KLUN) SELF%GTDCL
WRITE (KLUN) SELF%GSINHD
WRITE (KLUN) SELF%GSINHR
WRITE (KLUN) SELF%GCVFNER
WRITE (KLUN) SELF%GCVFNEO
WRITE (KLUN) SELF%GCVFNEP1
WRITE (KLUN) SELF%GCVFNEP2
WRITE (KLUN) SELF%GRBCC
WRITE (KLUN) SELF%GTOPDEPTH
WRITE (KLUN) SELF%GCVTSMO
WRITE (KLUN) SELF%RKDX
WRITE (KLUN) SELF%LCAPCIN
WRITE (KLUN) SELF%LCORSEDIM
WRITE (KLUN) SELF%GNHDTAU
WRITE (KLUN) SELF%GRSO
WRITE (KLUN) SELF%GRTH
WRITE (KLUN) SELF%GRFCS
WRITE (KLUN) SELF%GCVRE
WRITE (KLUN) SELF%GCVFMAX
WRITE (KLUN) SELF%GLIGHT
WRITE (KLUN) SELF%LSBUO
WRITE (KLUN) SELF%GREDDI
WRITE (KLUN) SELF%GREDDL
WRITE (KLUN) SELF%GREDDR
WRITE (KLUN) SELF%GREDDS
WRITE (KLUN) SELF%LCVTADV
WRITE (KLUN) SELF%LCVDS
WRITE (KLUN) SELF%GCVUV
WRITE (KLUN) SELF%GCVGAW
WRITE (KLUN) SELF%GCVGAX
WRITE (KLUN) SELF%GCHECKMV_TMIN
WRITE (KLUN) SELF%GCHECKMV_TMAX
WRITE (KLUN) SELF%GCHECKMV_QVMIN
WRITE (KLUN) SELF%GCHECKMV_QVMAX
WRITE (KLUN) SELF%LGPRONI1
WRITE (KLUN) SELF%NPRONI
WRITE (KLUN) SELF%GPRONI
WRITE (KLUN) SELF%RNEBCX
WRITE (KLUN) SELF%GLIGHTT1
WRITE (KLUN) SELF%GLIGHTT2
WRITE (KLUN) SELF%GLIGHTT3
WRITE (KLUN) SELF%REFLRHC
WRITE (KLUN) SELF%TEQH
WRITE (KLUN) SELF%REFLKUO
WRITE (KLUN) SELF%REFLCAPE
WRITE (KLUN) SELF%TEQK
WRITE (KLUN) SELF%TEQC
WRITE (KLUN) SELF%REPS
LRHUC = ALLOCATED (SELF%RHUC)
WRITE (KLUN) LRHUC
IF (LRHUC) THEN
  WRITE (KLUN) LBOUND (SELF%RHUC)
  WRITE (KLUN) UBOUND (SELF%RHUC)
  WRITE (KLUN) SELF%RHUC
ENDIF
LRQSMOD = ALLOCATED (SELF%RQSMOD)
WRITE (KLUN) LRQSMOD
IF (LRQSMOD) THEN
  WRITE (KLUN) LBOUND (SELF%RQSMOD)
  WRITE (KLUN) UBOUND (SELF%RQSMOD)
  WRITE (KLUN) SELF%RQSMOD
ENDIF
LRSURF = ALLOCATED (SELF%RSURF)
WRITE (KLUN) LRSURF
IF (LRSURF) THEN
  WRITE (KLUN) LBOUND (SELF%RSURF)
  WRITE (KLUN) UBOUND (SELF%RSURF)
  WRITE (KLUN) SELF%RSURF
ENDIF
LRN1D = ALLOCATED (SELF%RN1D)
WRITE (KLUN) LRN1D
IF (LRN1D) THEN
  WRITE (KLUN) LBOUND (SELF%RN1D)
  WRITE (KLUN) UBOUND (SELF%RN1D)
  WRITE (KLUN) SELF%RN1D
ENDIF
LRRC1D = ALLOCATED (SELF%RRC1D)
WRITE (KLUN) LRRC1D
IF (LRRC1D) THEN
  WRITE (KLUN) LBOUND (SELF%RRC1D)
  WRITE (KLUN) UBOUND (SELF%RRC1D)
  WRITE (KLUN) SELF%RRC1D
ENDIF
LRSRC1D = ALLOCATED (SELF%RSRC1D)
WRITE (KLUN) LRSRC1D
IF (LRSRC1D) THEN
  WRITE (KLUN) LBOUND (SELF%RSRC1D)
  WRITE (KLUN) UBOUND (SELF%RSRC1D)
  WRITE (KLUN) SELF%RSRC1D
ENDIF
WRITE (KLUN) SELF%RCOEFRAIN
WRITE (KLUN) SELF%RCOEFSNOW
CALL ACDC_SAVE_TADVPRS (SELF%YRADVPRCS, KLUN)
END SUBROUTINE

SUBROUTINE ACDC_LOAD_TPHY0 (SELF, KLUN)
USE UTIL_TADVPRS_MOD
USE PARKIND1, ONLY : JPRD
IMPLICIT NONE
TYPE (TPHY0), INTENT (OUT), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN
INTEGER :: IL1(1), IU1(1)
LOGICAL :: LRHUC, LRN1D, LRQSMOD, LRRC1D, LRSRC1D, LRSURF
REAL(KIND=JPRD) :: ZTMP0
REAL(KIND=JPRD), ALLOCATABLE :: ZTMP1 (:)
ALLOCATE (ZTMP1(LBOUND(SELF%TYM,1):UBOUND(SELF%TYM,1)))
READ (KLUN) ZTMP1
SELF%TYM = ZTMP1
DEALLOCATE (ZTMP1)
READ (KLUN) SELF%NPCLO1
READ (KLUN) SELF%NPCLO2
READ (KLUN) ZTMP0
SELF%A0ML_AU = ZTMP0
READ (KLUN) ZTMP0
SELF%A0ML_AT = ZTMP0
READ (KLUN) ZTMP0
SELF%A0ML_BU = ZTMP0
READ (KLUN) ZTMP0
SELF%A0ML_BT = ZTMP0
READ (KLUN) ZTMP0
SELF%AERCS1 = ZTMP0
READ (KLUN) ZTMP0
SELF%AERCS3 = ZTMP0
READ (KLUN) ZTMP0
SELF%AERCS5 = ZTMP0
READ (KLUN) ZTMP0
SELF%ADJTAU = ZTMP0
READ (KLUN) ZTMP0
SELF%ALMAV = ZTMP0
READ (KLUN) ZTMP0
SELF%BEDIFV = ZTMP0
READ (KLUN) ZTMP0
SELF%ECMNP = ZTMP0
READ (KLUN) ZTMP0
SELF%EDB = ZTMP0
READ (KLUN) ZTMP0
SELF%EDC = ZTMP0
READ (KLUN) ZTMP0
SELF%EDD = ZTMP0
READ (KLUN) ZTMP0
SELF%EVAP = ZTMP0
READ (KLUN) ZTMP0
SELF%FONT = ZTMP0
READ (KLUN) ZTMP0
SELF%GALP = ZTMP0
READ (KLUN) ZTMP0
SELF%GCISMIN = ZTMP0
READ (KLUN) ZTMP0
SELF%GEVAVF = ZTMP0
READ (KLUN) ZTMP0
SELF%GCCSV = ZTMP0
READ (KLUN) ZTMP0
SELF%GCVADS = ZTMP0
READ (KLUN) ZTMP0
SELF%GCVBETA = ZTMP0
READ (KLUN) ZTMP0
SELF%GCVIMPT = ZTMP0
READ (KLUN) ZTMP0
SELF%GCVOMGE = ZTMP0
READ (KLUN) ZTMP0
SELF%GCVOMGQ = ZTMP0
READ (KLUN) ZTMP0
SELF%GCVOMGS = ZTMP0
READ (KLUN) ZTMP0
SELF%GCVTURB = ZTMP0
READ (KLUN) ZTMP0
SELF%GCVOMDPS = ZTMP0
READ (KLUN) ZTMP0
SELF%GCVOMGSX = ZTMP0
READ (KLUN) ZTMP0
SELF%GCVRHMIN = ZTMP0
READ (KLUN) ZTMP0
SELF%GCVRHMAX = ZTMP0
READ (KLUN) ZTMP0
SELF%GCVOMCA = ZTMP0
READ (KLUN) ZTMP0
SELF%GCVOMCC = ZTMP0
READ (KLUN) ZTMP0
SELF%GDDEVA = ZTMP0
READ (KLUN) ZTMP0
SELF%GDDSDE = ZTMP0
READ (KLUN) ZTMP0
SELF%GDDFREVS = ZTMP0
READ (KLUN) ZTMP0
SELF%GDDINHOM = ZTMP0
READ (KLUN) ZTMP0
SELF%GRCVPP = ZTMP0
READ (KLUN) ZTMP0
SELF%GWDAMP = ZTMP0
READ (KLUN) ZTMP0
SELF%GWDBC = ZTMP0
READ (KLUN) ZTMP0
SELF%GWDCCO = ZTMP0
READ (KLUN) ZTMP0
SELF%GWDCD = ZTMP0
READ (KLUN) ZTMP0
SELF%GWDLT = ZTMP0
READ (KLUN) ZTMP0
SELF%GWDSE = ZTMP0
READ (KLUN) ZTMP0
SELF%GWDPROF = ZTMP0
READ (KLUN) ZTMP0
SELF%GWDVALI = ZTMP0
READ (KLUN) ZTMP0
SELF%HOBST = ZTMP0
READ (KLUN) ZTMP0
SELF%HUCOE = ZTMP0
READ (KLUN) ZTMP0
SELF%HUTIL = ZTMP0
READ (KLUN) ZTMP0
SELF%HUTIL1 = ZTMP0
READ (KLUN) ZTMP0
SELF%HUTIL2 = ZTMP0
READ (KLUN) ZTMP0
SELF%QSMIN = ZTMP0
READ (KLUN) ZTMP0
SELF%QSMODC = ZTMP0
READ (KLUN) ZTMP0
SELF%QSNEBC = ZTMP0
READ (KLUN) ZTMP0
SELF%QSNEBS = ZTMP0
READ (KLUN) ZTMP0
SELF%QSSUSC = ZTMP0
READ (KLUN) ZTMP0
SELF%QSSUSS = ZTMP0
READ (KLUN) ZTMP0
SELF%QSSUSV = ZTMP0
READ (KLUN) ZTMP0
SELF%QSUSXC = ZTMP0
READ (KLUN) ZTMP0
SELF%QSUSXS = ZTMP0
READ (KLUN) ZTMP0
SELF%RPHI0 = ZTMP0
READ (KLUN) ZTMP0
SELF%RPHIR = ZTMP0
READ (KLUN) ZTMP0
SELF%QXRAL = ZTMP0
READ (KLUN) ZTMP0
SELF%QXRAL_ADJ = ZTMP0
READ (KLUN) ZTMP0
SELF%QXRDEL = ZTMP0
READ (KLUN) ZTMP0
SELF%QXRHX = ZTMP0
READ (KLUN) ZTMP0
SELF%QXRR = ZTMP0
READ (KLUN) ZTMP0
SELF%QXRTGH = ZTMP0
READ (KLUN) ZTMP0
SELF%QXRCDIL = ZTMP0
READ (KLUN) ZTMP0
SELF%RCIN = ZTMP0
READ (KLUN) ZTMP0
SELF%RCVEVAP = ZTMP0
READ (KLUN) ZTMP0
SELF%RDECRD = ZTMP0
READ (KLUN) ZTMP0
SELF%RDECRD1 = ZTMP0
READ (KLUN) ZTMP0
SELF%RDECRD2 = ZTMP0
READ (KLUN) ZTMP0
SELF%RDECRD3 = ZTMP0
READ (KLUN) ZTMP0
SELF%RDECRD4 = ZTMP0
READ (KLUN) ZTMP0
SELF%RDECRDRED = ZTMP0
READ (KLUN) ZTMP0
SELF%RDTFAC = ZTMP0
READ (KLUN) ZTMP0
SELF%REVAPN = ZTMP0
READ (KLUN) ZTMP0
SELF%REVGSL = ZTMP0
READ (KLUN) ZTMP0
SELF%RGELSFON = ZTMP0
READ (KLUN) ZTMP0
SELF%RFLCHCE = ZTMP0
READ (KLUN) ZTMP0
SELF%RTCAPE = ZTMP0
READ (KLUN) ZTMP0
SELF%SCO = ZTMP0
READ (KLUN) ZTMP0
SELF%SENSL = ZTMP0
READ (KLUN) ZTMP0
SELF%SNNBCO = ZTMP0
READ (KLUN) ZTMP0
SELF%SPNBCO = ZTMP0
READ (KLUN) ZTMP0
SELF%SXNBCO = ZTMP0
READ (KLUN) ZTMP0
SELF%TCA = ZTMP0
READ (KLUN) ZTMP0
SELF%TCT = ZTMP0
READ (KLUN) ZTMP0
SELF%TCW = ZTMP0
READ (KLUN) ZTMP0
SELF%TENTR = ZTMP0
READ (KLUN) ZTMP0
SELF%TENTRX = ZTMP0
READ (KLUN) ZTMP0
SELF%TUDGP = ZTMP0
READ (KLUN) ZTMP0
SELF%TDDGP = ZTMP0
READ (KLUN) ZTMP0
SELF%TURB = ZTMP0
READ (KLUN) ZTMP0
SELF%TVF = ZTMP0
READ (KLUN) ZTMP0
SELF%UHDIFV = ZTMP0
READ (KLUN) ZTMP0
SELF%USDMLT = ZTMP0
READ (KLUN) ZTMP0
SELF%USUPRC = ZTMP0
READ (KLUN) ZTMP0
SELF%USURIC = ZTMP0
READ (KLUN) ZTMP0
SELF%VCHRNK = ZTMP0
READ (KLUN) ZTMP0
SELF%VKARMN = ZTMP0
READ (KLUN) ZTMP0
SELF%VZ0CM = ZTMP0
READ (KLUN) ZTMP0
SELF%VZIUSTAR0 = ZTMP0
READ (KLUN) ZTMP0
SELF%XNBMAX = ZTMP0
READ (KLUN) ZTMP0
SELF%AECLS3 = ZTMP0
READ (KLUN) ZTMP0
SELF%AECLS4 = ZTMP0
READ (KLUN) ZTMP0
SELF%ALD = ZTMP0
READ (KLUN) ZTMP0
SELF%AKN = ZTMP0
READ (KLUN) ZTMP0
SELF%ALPHAT = ZTMP0
READ (KLUN) ZTMP0
SELF%ALPHAE = ZTMP0
READ (KLUN) ZTMP0
SELF%EPS = ZTMP0
READ (KLUN) ZTMP0
SELF%ETACUT = ZTMP0
READ (KLUN) ZTMP0
SELF%ADISI = ZTMP0
READ (KLUN) ZTMP0
SELF%ADISE = ZTMP0
READ (KLUN) ZTMP0
SELF%ECTMIN = ZTMP0
READ (KLUN) ZTMP0
SELF%ECTMAX = ZTMP0
READ (KLUN) ZTMP0
SELF%AHCLPV = ZTMP0
READ (KLUN) ZTMP0
SELF%RICRLM = ZTMP0
READ (KLUN) ZTMP0
SELF%RMULACVG = ZTMP0
READ (KLUN) ZTMP0
SELF%XBLM = ZTMP0
READ (KLUN) ZTMP0
SELF%XMINLM = ZTMP0
READ (KLUN) ZTMP0
SELF%XMAXLM = ZTMP0
READ (KLUN) ZTMP0
SELF%XWSALM = ZTMP0
READ (KLUN) ZTMP0
SELF%XWSBLM = ZTMP0
READ (KLUN) ZTMP0
SELF%GCVALFA = ZTMP0
READ (KLUN) ZTMP0
SELF%GCVPSI = ZTMP0
READ (KLUN) ZTMP0
SELF%GCVPSIE = ZTMP0
READ (KLUN) ZTMP0
SELF%USURICE = ZTMP0
READ (KLUN) ZTMP0
SELF%USURICL = ZTMP0
READ (KLUN) ZTMP0
SELF%QSSC = ZTMP0
READ (KLUN) ZTMP0
SELF%USURID = ZTMP0
READ (KLUN) ZTMP0
SELF%GCVNU = ZTMP0
READ (KLUN) ZTMP0
SELF%USURIDE = ZTMP0
READ (KLUN) ZTMP0
SELF%GCVMLT = ZTMP0
READ (KLUN) ZTMP0
SELF%UTILGUST = ZTMP0
READ (KLUN) ZTMP0
SELF%RRGAMMA = ZTMP0
READ (KLUN) ZTMP0
SELF%RRSCALE = ZTMP0
READ (KLUN) ZTMP0
SELF%GPBLHK0 = ZTMP0
READ (KLUN) ZTMP0
SELF%GPBLHRA = ZTMP0
READ (KLUN) ZTMP0
SELF%WMXOV = ZTMP0
READ (KLUN) ZTMP0
SELF%ACBRPHIM = ZTMP0
READ (KLUN) ZTMP0
SELF%ALMAVE = ZTMP0
READ (KLUN) ZTMP0
SELF%ALMAVX = ZTMP0
READ (KLUN) ZTMP0
SELF%ARSCH = ZTMP0
READ (KLUN) ZTMP0
SELF%ARSCQ = ZTMP0
READ (KLUN) ZTMP0
SELF%ARSC1 = ZTMP0
READ (KLUN) ZTMP0
SELF%ARSB2 = ZTMP0
READ (KLUN) ZTMP0
SELF%RICRET = ZTMP0
READ (KLUN) ZTMP0
SELF%STTBMIN = ZTMP0
READ (KLUN) ZTMP0
SELF%UCWSTAR = ZTMP0
READ (KLUN) ZTMP0
SELF%UDECT = ZTMP0
READ (KLUN) ZTMP0
SELF%UPRETMIN = ZTMP0
READ (KLUN) ZTMP0
SELF%UPRETMAX = ZTMP0
READ (KLUN) ZTMP0
SELF%USHEARM = ZTMP0
READ (KLUN) ZTMP0
SELF%RAUTEFR = ZTMP0
READ (KLUN) ZTMP0
SELF%RRAUTCS = ZTMP0
READ (KLUN) ZTMP0
SELF%RAUTEFS = ZTMP0
READ (KLUN) ZTMP0
SELF%RAUTSBET = ZTMP0
READ (KLUN) ZTMP0
SELF%RAUTEFG = ZTMP0
READ (KLUN) ZTMP0
SELF%REVASX = ZTMP0
READ (KLUN) ZTMP0
SELF%REVASXR = ZTMP0
READ (KLUN) ZTMP0
SELF%REVASXS = ZTMP0
READ (KLUN) ZTMP0
SELF%REVASXG = ZTMP0
READ (KLUN) ZTMP0
SELF%RNINTR = ZTMP0
READ (KLUN) ZTMP0
SELF%RNINTS = ZTMP0
READ (KLUN) ZTMP0
SELF%RNINTG = ZTMP0
READ (KLUN) ZTMP0
SELF%RQLCR = ZTMP0
READ (KLUN) ZTMP0
SELF%RSPCRR = ZTMP0
READ (KLUN) ZTMP0
SELF%RQICRMAX = ZTMP0
READ (KLUN) ZTMP0
SELF%RQICRMIN = ZTMP0
READ (KLUN) ZTMP0
SELF%RQLCV = ZTMP0
READ (KLUN) ZTMP0
SELF%RQICVMAX = ZTMP0
READ (KLUN) ZTMP0
SELF%RQICVMIN = ZTMP0
READ (KLUN) ZTMP0
SELF%RQICRT1 = ZTMP0
READ (KLUN) ZTMP0
SELF%RQICRT2 = ZTMP0
READ (KLUN) ZTMP0
SELF%RQICRSN = ZTMP0
READ (KLUN) ZTMP0
SELF%RQCRNS = ZTMP0
READ (KLUN) ZTMP0
SELF%RACCEF = ZTMP0
READ (KLUN) ZTMP0
SELF%RAGGEF = ZTMP0
READ (KLUN) ZTMP0
SELF%RRIMEF = ZTMP0
READ (KLUN) ZTMP0
SELF%RHCRIT1 = ZTMP0
READ (KLUN) ZTMP0
SELF%RHCRIT2 = ZTMP0
READ (KLUN) ZTMP0
SELF%RETAMIN = ZTMP0
READ (KLUN) ZTMP0
SELF%RFACNSM = ZTMP0
READ (KLUN) ZTMP0
SELF%TFVL = ZTMP0
READ (KLUN) ZTMP0
SELF%TFVLD = ZTMP0
READ (KLUN) ZTMP0
SELF%TFVI = ZTMP0
READ (KLUN) ZTMP0
SELF%TFVR = ZTMP0
READ (KLUN) ZTMP0
SELF%TFVS = ZTMP0
READ (KLUN) ZTMP0
SELF%GRHCMOD = ZTMP0
READ (KLUN) ZTMP0
SELF%RHCEXPDX = ZTMP0
READ (KLUN) ZTMP0
SELF%NUPTKE = ZTMP0
READ (KLUN) ZTMP0
SELF%TKEMULT = ZTMP0
READ (KLUN) ZTMP0
SELF%C_EPSILON = ZTMP0
READ (KLUN) ZTMP0
SELF%C3TKEFREE = ZTMP0
READ (KLUN) ZTMP0
SELF%ETKE_CTHETA = ZTMP0
READ (KLUN) ZTMP0
SELF%ETKE_RIFC_MAF = ZTMP0
READ (KLUN) ZTMP0
SELF%ETKE_RIFC = ZTMP0
READ (KLUN) ZTMP0
SELF%ETKE_R = ZTMP0
READ (KLUN) ZTMP0
SELF%ETKE_OLAM = ZTMP0
READ (KLUN) ZTMP0
SELF%ETKE_LAM0 = ZTMP0
READ (KLUN) ZTMP0
SELF%ETKE_LAM1 = ZTMP0
READ (KLUN) ZTMP0
SELF%ETKE_LAM2 = ZTMP0
READ (KLUN) ZTMP0
SELF%ETKE_LAM3 = ZTMP0
READ (KLUN) ZTMP0
SELF%ETKE_LAM4 = ZTMP0
READ (KLUN) ZTMP0
SELF%ETKE_KA1 = ZTMP0
READ (KLUN) ZTMP0
SELF%ETKE_KA2 = ZTMP0
READ (KLUN) ZTMP0
SELF%ETKE_KA3 = ZTMP0
READ (KLUN) ZTMP0
SELF%ENT_LAMBDA = ZTMP0
READ (KLUN) ZTMP0
SELF%ETKE_CG01 = ZTMP0
READ (KLUN) ZTMP0
SELF%ETKE_CG02 = ZTMP0
READ (KLUN) ZTMP0
SELF%ETKE_CG03 = ZTMP0
READ (KLUN) ZTMP0
SELF%ETKE_BETA_EPS = ZTMP0
READ (KLUN) ZTMP0
SELF%ETKE_GAMMA_EPS = ZTMP0
READ (KLUN) ZTMP0
SELF%ETKE_GAMD = ZTMP0
READ (KLUN) ZTMP0
SELF%ETKE_TALPH = ZTMP0
READ (KLUN) ZTMP0
SELF%ETKE_ALPH0 = ZTMP0
READ (KLUN) ZTMP0
SELF%ETKE_ENTRX = ZTMP0
READ (KLUN) ZTMP0
SELF%ETKE_ENTRN = ZTMP0
READ (KLUN) ZTMP0
SELF%ETKE_KLM = ZTMP0
READ (KLUN) ZTMP0
SELF%ETKE_TAULM = ZTMP0
READ (KLUN) ZTMP0
SELF%ETKE_C0SHEAR = ZTMP0
READ (KLUN) ZTMP0
SELF%ETKE_DTHETA_S1 = ZTMP0
READ (KLUN) ZTMP0
SELF%ETKE_DTHETA_S2 = ZTMP0
READ (KLUN) ZTMP0
SELF%ETKE_LBLT1 = ZTMP0
READ (KLUN) ZTMP0
SELF%ETKE_LBLT2 = ZTMP0
READ (KLUN) ZTMP0
SELF%ETKE_HUTLS = ZTMP0
READ (KLUN) ZTMP0
SELF%ETKE_LUTLS = ZTMP0
READ (KLUN) ZTMP0
SELF%ETKE_R1SIM = ZTMP0
READ (KLUN) ZTMP0
SELF%ETKE_R2SIM = ZTMP0
READ (KLUN) ZTMP0
SELF%ETKE_GB08A = ZTMP0
READ (KLUN) ZTMP0
SELF%ETKE_GB08B = ZTMP0
READ (KLUN) ZTMP0
SELF%ETKE_MIN = ZTMP0
READ (KLUN) ZTMP0
SELF%ETKE_CRIT = ZTMP0
READ (KLUN) ZTMP0
SELF%ETKE_DELTA = ZTMP0
READ (KLUN) ZTMP0
SELF%ETKE_RIFGR = ZTMP0
READ (KLUN) ZTMP0
SELF%EFB_AZ0 = ZTMP0
READ (KLUN) ZTMP0
SELF%EFB_UR = ZTMP0
READ (KLUN) ZTMP0
SELF%REFB_1 = ZTMP0
READ (KLUN) ZTMP0
SELF%REFB_2 = ZTMP0
READ (KLUN) ZTMP0
SELF%REFB_3 = ZTMP0
READ (KLUN) ZTMP0
SELF%RPBLH_UP = ZTMP0
READ (KLUN) ZTMP0
SELF%TUDBU = ZTMP0
READ (KLUN) ZTMP0
SELF%TDDBU = ZTMP0
READ (KLUN) ZTMP0
SELF%TUDFR = ZTMP0
READ (KLUN) ZTMP0
SELF%TDDFR = ZTMP0
READ (KLUN) ZTMP0
SELF%GCVALMX = ZTMP0
READ (KLUN) ZTMP0
SELF%GCVTAUDE = ZTMP0
READ (KLUN) ZTMP0
SELF%GCVACHI = ZTMP0
READ (KLUN) ZTMP0
SELF%GCVBEE = ZTMP0
READ (KLUN) ZTMP0
SELF%GCVEEX = ZTMP0
READ (KLUN) ZTMP0
SELF%ECMNPI = ZTMP0
READ (KLUN) ZTMP0
SELF%GRRMINA = ZTMP0
READ (KLUN) ZTMP0
SELF%GDDBETA = ZTMP0
READ (KLUN) ZTMP0
SELF%GDDDP = ZTMP0
READ (KLUN) ZTMP0
SELF%GDDFXM = ZTMP0
READ (KLUN) ZTMP0
SELF%GDDWPF = ZTMP0
READ (KLUN) ZTMP0
SELF%GDDEVF = ZTMP0
READ (KLUN) ZTMP0
SELF%TENTRD = ZTMP0
READ (KLUN) ZTMP0
SELF%GDDALBU = ZTMP0
READ (KLUN) ZTMP0
SELF%GDDFRAC = ZTMP0
READ (KLUN) ZTMP0
SELF%GDDENDYMX = ZTMP0
ALLOCATE (ZTMP1(LBOUND(SELF%GDDFP,1):UBOUND(SELF%GDDFP,1)))
READ (KLUN) ZTMP1
SELF%GDDFP = ZTMP1
DEALLOCATE (ZTMP1)
READ (KLUN) ZTMP0
SELF%GDDTAUSIG = ZTMP0
READ (KLUN) ZTMP0
SELF%GPEIPHI = ZTMP0
READ (KLUN) ZTMP0
SELF%GPETAU = ZTMP0
READ (KLUN) ZTMP0
SELF%GPEFDC = ZTMP0
READ (KLUN) ZTMP0
SELF%GENVSRH = ZTMP0
READ (KLUN) ZTMP0
SELF%GCVKSKV = ZTMP0
READ (KLUN) ZTMP0
SELF%GCVALBU = ZTMP0
READ (KLUN) ZTMP0
SELF%GCVENDY1 = ZTMP0
READ (KLUN) ZTMP0
SELF%GCVENDY2 = ZTMP0
READ (KLUN) ZTMP0
SELF%GCVENDYMX = ZTMP0
READ (KLUN) ZTMP0
SELF%GCVIDPBAS = ZTMP0
READ (KLUN) ZTMP0
SELF%GCVTAUSIG = ZTMP0
READ (KLUN) ZTMP0
SELF%GTRGDPMIX = ZTMP0
READ (KLUN) ZTMP0
SELF%GTRGDPHIMN = ZTMP0
READ (KLUN) ZTMP0
SELF%GTRGPUSLMN = ZTMP0
READ (KLUN) ZTMP0
SELF%GTRGKCK9 = ZTMP0
READ (KLUN) ZTMP0
SELF%GTRGAIN = ZTMP0
READ (KLUN) ZTMP0
SELF%GTRTHRS = ZTMP0
READ (KLUN) ZTMP0
SELF%GTRTHCK = ZTMP0
READ (KLUN) ZTMP0
SELF%GTRBRC = ZTMP0
READ (KLUN) ZTMP0
SELF%GTRKGAIN = ZTMP0
READ (KLUN) ZTMP0
SELF%GTRKTHRS = ZTMP0
READ (KLUN) ZTMP0
SELF%GTRKTHCK = ZTMP0
READ (KLUN) ZTMP0
SELF%GCVCATAU = ZTMP0
READ (KLUN) ZTMP0
SELF%GCATHRCAP = ZTMP0
READ (KLUN) ZTMP0
SELF%GCATHRMOC = ZTMP0
READ (KLUN) ZTMP0
SELF%GCATHRCND = ZTMP0
READ (KLUN) ZTMP0
SELF%GCAOMCND = ZTMP0
READ (KLUN) ZTMP0
SELF%NWEIGHT = ZTMP0
READ (KLUN) ZTMP0
SELF%NCATAU = ZTMP0
READ (KLUN) ZTMP0
SELF%NCAPEMAX = ZTMP0
READ (KLUN) ZTMP0
SELF%NCVGMAX = ZTMP0
READ (KLUN) ZTMP0
SELF%RNEGAT = ZTMP0
READ (KLUN) ZTMP0
SELF%RNLCURV = ZTMP0
READ (KLUN) ZTMP0
SELF%EDK = ZTMP0
READ (KLUN) ZTMP0
SELF%XKLM = ZTMP0
READ (KLUN) ZTMP0
SELF%AGRE1 = ZTMP0
READ (KLUN) ZTMP0
SELF%AGRERICR = ZTMP0
READ (KLUN) ZTMP0
SELF%AJBUMIN = ZTMP0
READ (KLUN) ZTMP0
SELF%RCOFLM = ZTMP0
READ (KLUN) ZTMP0
SELF%TENTRVL = ZTMP0
READ (KLUN) ZTMP0
SELF%TRENTRV = ZTMP0
READ (KLUN) ZTMP0
SELF%GCVGAMMA = ZTMP0
READ (KLUN) SELF%LKESC
READ (KLUN) ZTMP0
SELF%AGRE2 = ZTMP0
READ (KLUN) ZTMP0
SELF%AGREF = ZTMP0
READ (KLUN) ZTMP0
SELF%ALFX = ZTMP0
READ (KLUN) ZTMP0
SELF%ALFX_LR = ZTMP0
READ (KLUN) ZTMP0
SELF%ALFX_HR = ZTMP0
READ (KLUN) ZTMP0
SELF%TCTC = ZTMP0
READ (KLUN) ZTMP0
SELF%TVFC = ZTMP0
READ (KLUN) ZTMP0
SELF%GAMAP1 = ZTMP0
READ (KLUN) ZTMP0
SELF%RKDN = ZTMP0
READ (KLUN) ZTMP0
SELF%VVN = ZTMP0
READ (KLUN) ZTMP0
SELF%VVX = ZTMP0
READ (KLUN) ZTMP0
SELF%FENTRT = ZTMP0
READ (KLUN) ZTMP0
SELF%FQLIC = ZTMP0
READ (KLUN) ZTMP0
SELF%FNEBC = ZTMP0
READ (KLUN) ZTMP0
SELF%FEVAPC = ZTMP0
READ (KLUN) ZTMP0
SELF%RDPHIC = ZTMP0
READ (KLUN) ZTMP0
SELF%RWBF1 = ZTMP0
READ (KLUN) ZTMP0
SELF%RWBF2 = ZTMP0
READ (KLUN) ZTMP0
SELF%RCPCOEF1 = ZTMP0
READ (KLUN) ZTMP0
SELF%RCPCOEF2 = ZTMP0
READ (KLUN) ZTMP0
SELF%RCPCOEF3 = ZTMP0
READ (KLUN) ZTMP0
SELF%SCLESPR = ZTMP0
READ (KLUN) ZTMP0
SELF%SCLESPS = ZTMP0
READ (KLUN) ZTMP0
SELF%HUCRED = ZTMP0
READ (KLUN) ZTMP0
SELF%HUCREDRA = ZTMP0
READ (KLUN) ZTMP0
SELF%FSPRAIN = ZTMP0
READ (KLUN) ZTMP0
SELF%EFFCOLL = ZTMP0
READ (KLUN) ZTMP0
SELF%RSMDNEBX = ZTMP0
READ (KLUN) ZTMP0
SELF%RSMDTX = ZTMP0
READ (KLUN) SELF%NSMTPA
READ (KLUN) SELF%NSMTPB
READ (KLUN) ZTMP0
SELF%RKFBTAU = ZTMP0
READ (KLUN) ZTMP0
SELF%RKFBNBX = ZTMP0
READ (KLUN) ZTMP0
SELF%GCVHMIN = ZTMP0
READ (KLUN) ZTMP0
SELF%GCVRESN = ZTMP0
READ (KLUN) ZTMP0
SELF%GCVRESX = ZTMP0
READ (KLUN) ZTMP0
SELF%GMIRH = ZTMP0
READ (KLUN) ZTMP0
SELF%RLMLH1 = ZTMP0
READ (KLUN) ZTMP0
SELF%RPRTH = ZTMP0
READ (KLUN) ZTMP0
SELF%RSMOOTHMELT = ZTMP0
READ (KLUN) SELF%LADVLIM
READ (KLUN) SELF%LGDDD
READ (KLUN) SELF%LCVRESDYN
READ (KLUN) SELF%LCVMICC
READ (KLUN) ZTMP0
SELF%GMUKEDD = ZTMP0
READ (KLUN) ZTMP0
SELF%GNHDTAT = ZTMP0
READ (KLUN) ZTMP0
SELF%GNHDSMOS = ZTMP0
READ (KLUN) ZTMP0
SELF%GNHDSMOT = ZTMP0
READ (KLUN) ZTMP0
SELF%GNHDEV = ZTMP0
READ (KLUN) SELF%LGVVEX
READ (KLUN) SELF%LCVUVM
READ (KLUN) SELF%NCVENTR
READ (KLUN) SELF%NCVSIG
READ (KLUN) SELF%NCVCLOS
READ (KLUN) SELF%NCVQLI
READ (KLUN) ZTMP0
SELF%GCVENTRN = ZTMP0
READ (KLUN) ZTMP0
SELF%GCVENTRX = ZTMP0
READ (KLUN) ZTMP0
SELF%ADOE = ZTMP0
READ (KLUN) ZTMP0
SELF%RFRAC_ENTR_N = ZTMP0
READ (KLUN) ZTMP0
SELF%RFRAC_ENTR_X = ZTMP0
READ (KLUN) ZTMP0
SELF%GCVENTR_MIN = ZTMP0
READ (KLUN) ZTMP0
SELF%THPCMT = ZTMP0
READ (KLUN) ZTMP0
SELF%AJ1PEPS = ZTMP0
READ (KLUN) ZTMP0
SELF%AJ1MEPS = ZTMP0
READ (KLUN) SELF%NAJITER
READ (KLUN) ZTMP0
SELF%GAEPS = ZTMP0
READ (KLUN) ZTMP0
SELF%GCVEZ = ZTMP0
READ (KLUN) ZTMP0
SELF%GCVTRMIN = ZTMP0
READ (KLUN) SELF%LCVFEVV
READ (KLUN) ZTMP0
SELF%GCVFEVV = ZTMP0
READ (KLUN) SELF%LCVCONTAU
READ (KLUN) ZTMP0
SELF%GCVTEXC = ZTMP0
READ (KLUN) ZTMP0
SELF%GCVWEXC = ZTMP0
READ (KLUN) SELF%LCVNAUV
READ (KLUN) ZTMP0
SELF%GCVFRR = ZTMP0
READ (KLUN) ZTMP0
SELF%GCVPNH = ZTMP0
READ (KLUN) ZTMP0
SELF%GCVORGED = ZTMP0
READ (KLUN) SELF%LCVIMPT
READ (KLUN) ZTMP0
SELF%GCVTAUREM = ZTMP0
READ (KLUN) ZTMP0
SELF%GCLOEA = ZTMP0
READ (KLUN) ZTMP0
SELF%GCLOEB = ZTMP0
READ (KLUN) ZTMP0
SELF%GFRAE = ZTMP0
READ (KLUN) ZTMP0
SELF%GCVADET = ZTMP0
READ (KLUN) ZTMP0
SELF%GCVCINC = ZTMP0
READ (KLUN) ZTMP0
SELF%GSDMIN = ZTMP0
READ (KLUN) ZTMP0
SELF%GSDMAX = ZTMP0
READ (KLUN) ZTMP0
SELF%GALMIN = ZTMP0
READ (KLUN) ZTMP0
SELF%GALMAX = ZTMP0
READ (KLUN) ZTMP0
SELF%GSDAMIN = ZTMP0
READ (KLUN) ZTMP0
SELF%GSDAMAX = ZTMP0
READ (KLUN) ZTMP0
SELF%GEXPKD = ZTMP0
READ (KLUN) SELF%LCVEOD
READ (KLUN) ZTMP0
SELF%GREMIN = ZTMP0
READ (KLUN) ZTMP0
SELF%GREMAX = ZTMP0
READ (KLUN) ZTMP0
SELF%GCHI0 = ZTMP0
READ (KLUN) ZTMP0
SELF%GFSURF = ZTMP0
READ (KLUN) ZTMP0
SELF%GSHELL = ZTMP0
READ (KLUN) ZTMP0
SELF%GFRIC = ZTMP0
READ (KLUN) ZTMP0
SELF%GUDDD = ZTMP0
READ (KLUN) ZTMP0
SELF%GSIGA = ZTMP0
READ (KLUN) ZTMP0
SELF%GNHDSMOW = ZTMP0
READ (KLUN) ZTMP0
SELF%GDEPTH = ZTMP0
READ (KLUN) ZTMP0
SELF%GALTAU = ZTMP0
READ (KLUN) ZTMP0
SELF%GKEDDRE = ZTMP0
READ (KLUN) ZTMP0
SELF%GNHACC = ZTMP0
READ (KLUN) ZTMP0
SELF%GTDCL = ZTMP0
READ (KLUN) ZTMP0
SELF%GSINHD = ZTMP0
READ (KLUN) ZTMP0
SELF%GSINHR = ZTMP0
READ (KLUN) ZTMP0
SELF%GCVFNER = ZTMP0
READ (KLUN) ZTMP0
SELF%GCVFNEO = ZTMP0
READ (KLUN) ZTMP0
SELF%GCVFNEP1 = ZTMP0
READ (KLUN) ZTMP0
SELF%GCVFNEP2 = ZTMP0
READ (KLUN) ZTMP0
SELF%GRBCC = ZTMP0
READ (KLUN) ZTMP0
SELF%GTOPDEPTH = ZTMP0
READ (KLUN) ZTMP0
SELF%GCVTSMO = ZTMP0
READ (KLUN) ZTMP0
SELF%RKDX = ZTMP0
READ (KLUN) SELF%LCAPCIN
READ (KLUN) SELF%LCORSEDIM
READ (KLUN) ZTMP0
SELF%GNHDTAU = ZTMP0
READ (KLUN) ZTMP0
SELF%GRSO = ZTMP0
READ (KLUN) ZTMP0
SELF%GRTH = ZTMP0
READ (KLUN) ZTMP0
SELF%GRFCS = ZTMP0
READ (KLUN) ZTMP0
SELF%GCVRE = ZTMP0
READ (KLUN) ZTMP0
SELF%GCVFMAX = ZTMP0
READ (KLUN) ZTMP0
SELF%GLIGHT = ZTMP0
READ (KLUN) SELF%LSBUO
READ (KLUN) ZTMP0
SELF%GREDDI = ZTMP0
READ (KLUN) ZTMP0
SELF%GREDDL = ZTMP0
READ (KLUN) ZTMP0
SELF%GREDDR = ZTMP0
READ (KLUN) ZTMP0
SELF%GREDDS = ZTMP0
READ (KLUN) SELF%LCVTADV
READ (KLUN) SELF%LCVDS
READ (KLUN) ZTMP0
SELF%GCVUV = ZTMP0
READ (KLUN) ZTMP0
SELF%GCVGAW = ZTMP0
READ (KLUN) ZTMP0
SELF%GCVGAX = ZTMP0
READ (KLUN) ZTMP0
SELF%GCHECKMV_TMIN = ZTMP0
READ (KLUN) ZTMP0
SELF%GCHECKMV_TMAX = ZTMP0
READ (KLUN) ZTMP0
SELF%GCHECKMV_QVMIN = ZTMP0
READ (KLUN) ZTMP0
SELF%GCHECKMV_QVMAX = ZTMP0
READ (KLUN) SELF%LGPRONI1
READ (KLUN) SELF%NPRONI
READ (KLUN) ZTMP0
SELF%GPRONI = ZTMP0
READ (KLUN) ZTMP0
SELF%RNEBCX = ZTMP0
READ (KLUN) ZTMP0
SELF%GLIGHTT1 = ZTMP0
READ (KLUN) ZTMP0
SELF%GLIGHTT2 = ZTMP0
READ (KLUN) ZTMP0
SELF%GLIGHTT3 = ZTMP0
READ (KLUN) ZTMP0
SELF%REFLRHC = ZTMP0
READ (KLUN) ZTMP0
SELF%TEQH = ZTMP0
READ (KLUN) ZTMP0
SELF%REFLKUO = ZTMP0
READ (KLUN) ZTMP0
SELF%REFLCAPE = ZTMP0
READ (KLUN) ZTMP0
SELF%TEQK = ZTMP0
READ (KLUN) ZTMP0
SELF%TEQC = ZTMP0
READ (KLUN) ZTMP0
SELF%REPS = ZTMP0
READ (KLUN) LRHUC
IF (LRHUC) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%RHUC (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(SELF%RHUC,1):UBOUND(SELF%RHUC,1)))
  READ (KLUN) ZTMP1
  SELF%RHUC = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) LRQSMOD
IF (LRQSMOD) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%RQSMOD (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(SELF%RQSMOD,1):UBOUND(SELF%RQSMOD,1)))
  READ (KLUN) ZTMP1
  SELF%RQSMOD = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) LRSURF
IF (LRSURF) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%RSURF (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(SELF%RSURF,1):UBOUND(SELF%RSURF,1)))
  READ (KLUN) ZTMP1
  SELF%RSURF = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) LRN1D
IF (LRN1D) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%RN1D (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(SELF%RN1D,1):UBOUND(SELF%RN1D,1)))
  READ (KLUN) ZTMP1
  SELF%RN1D = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) LRRC1D
IF (LRRC1D) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%RRC1D (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(SELF%RRC1D,1):UBOUND(SELF%RRC1D,1)))
  READ (KLUN) ZTMP1
  SELF%RRC1D = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) LRSRC1D
IF (LRSRC1D) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%RSRC1D (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(SELF%RSRC1D,1):UBOUND(SELF%RSRC1D,1)))
  READ (KLUN) ZTMP1
  SELF%RSRC1D = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
ALLOCATE (ZTMP1(LBOUND(SELF%RCOEFRAIN,1):UBOUND(SELF%RCOEFRAIN,1)))
READ (KLUN) ZTMP1
SELF%RCOEFRAIN = ZTMP1
DEALLOCATE (ZTMP1)
ALLOCATE (ZTMP1(LBOUND(SELF%RCOEFSNOW,1):UBOUND(SELF%RCOEFSNOW,1)))
READ (KLUN) ZTMP1
SELF%RCOEFSNOW = ZTMP1
DEALLOCATE (ZTMP1)
CALL ACDC_LOAD_TADVPRS (SELF%YRADVPRCS, KLUN)
END SUBROUTINE

SUBROUTINE ACDC_COPY_TPHY0 (SELF, LDCREATED, LDFIELDAPI)
USE UTIL_TADVPRS_MOD
IMPLICIT NONE
TYPE (TPHY0), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
LOGICAL :: LLCREATED
LOGICAL :: LLFIELDAPI
LOGICAL :: LRHUC, LRN1D, LRQSMOD, LRRC1D, LRSRC1D, LRSURF
LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$ACC ENTER DATA CREATE (SELF)
  !$ACC UPDATE DEVICE (SELF)
ENDIF

LRHUC = ALLOCATED (SELF%RHUC)
IF (LRHUC) THEN
  !$ACC ENTER DATA CREATE (SELF%RHUC)
  !$ACC UPDATE DEVICE (SELF%RHUC)
  !$ACC ENTER DATA ATTACH (SELF%RHUC)
ENDIF

LRQSMOD = ALLOCATED (SELF%RQSMOD)
IF (LRQSMOD) THEN
  !$ACC ENTER DATA CREATE (SELF%RQSMOD)
  !$ACC UPDATE DEVICE (SELF%RQSMOD)
  !$ACC ENTER DATA ATTACH (SELF%RQSMOD)
ENDIF

LRSURF = ALLOCATED (SELF%RSURF)
IF (LRSURF) THEN
  !$ACC ENTER DATA CREATE (SELF%RSURF)
  !$ACC UPDATE DEVICE (SELF%RSURF)
  !$ACC ENTER DATA ATTACH (SELF%RSURF)
ENDIF

LRN1D = ALLOCATED (SELF%RN1D)
IF (LRN1D) THEN
  !$ACC ENTER DATA CREATE (SELF%RN1D)
  !$ACC UPDATE DEVICE (SELF%RN1D)
  !$ACC ENTER DATA ATTACH (SELF%RN1D)
ENDIF

LRRC1D = ALLOCATED (SELF%RRC1D)
IF (LRRC1D) THEN
  !$ACC ENTER DATA CREATE (SELF%RRC1D)
  !$ACC UPDATE DEVICE (SELF%RRC1D)
  !$ACC ENTER DATA ATTACH (SELF%RRC1D)
ENDIF

LRSRC1D = ALLOCATED (SELF%RSRC1D)
IF (LRSRC1D) THEN
  !$ACC ENTER DATA CREATE (SELF%RSRC1D)
  !$ACC UPDATE DEVICE (SELF%RSRC1D)
  !$ACC ENTER DATA ATTACH (SELF%RSRC1D)
ENDIF

CALL ACDC_COPY_TADVPRS (SELF%YRADVPRCS, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

END SUBROUTINE







SUBROUTINE ACDC_WIPE_TPHY0 (SELF, LDDELETED, LDFIELDAPI)
USE UTIL_TADVPRS_MOD
IMPLICIT NONE
TYPE (TPHY0), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
LOGICAL :: LLDELETED
LOGICAL :: LLFIELDAPI
LOGICAL :: LRHUC, LRN1D, LRQSMOD, LRRC1D, LRSRC1D, LRSURF
LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF

LRHUC = ALLOCATED (SELF%RHUC)
IF (LRHUC) THEN
  !$ACC EXIT DATA DETACH (SELF%RHUC)
  !$ACC EXIT DATA DELETE (SELF%RHUC)
ENDIF

LRQSMOD = ALLOCATED (SELF%RQSMOD)
IF (LRQSMOD) THEN
  !$ACC EXIT DATA DETACH (SELF%RQSMOD)
  !$ACC EXIT DATA DELETE (SELF%RQSMOD)
ENDIF

LRSURF = ALLOCATED (SELF%RSURF)
IF (LRSURF) THEN
  !$ACC EXIT DATA DETACH (SELF%RSURF)
  !$ACC EXIT DATA DELETE (SELF%RSURF)
ENDIF

LRN1D = ALLOCATED (SELF%RN1D)
IF (LRN1D) THEN
  !$ACC EXIT DATA DETACH (SELF%RN1D)
  !$ACC EXIT DATA DELETE (SELF%RN1D)
ENDIF

LRRC1D = ALLOCATED (SELF%RRC1D)
IF (LRRC1D) THEN
  !$ACC EXIT DATA DETACH (SELF%RRC1D)
  !$ACC EXIT DATA DELETE (SELF%RRC1D)
ENDIF

LRSRC1D = ALLOCATED (SELF%RSRC1D)
IF (LRSRC1D) THEN
  !$ACC EXIT DATA DETACH (SELF%RSRC1D)
  !$ACC EXIT DATA DELETE (SELF%RSRC1D)
ENDIF

CALL ACDC_WIPE_TADVPRS (SELF%YRADVPRCS, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$ACC EXIT DATA DELETE (SELF)
ENDIF
END SUBROUTINE



END MODULE
